import { describe, expect, it } from 'vitest'
import {
  REVIEW_DISPUTE_ACTIONS as SHARED_REVIEW_DISPUTE_ACTIONS,
  REVIEW_DISPUTE_REASONS as SHARED_REVIEW_DISPUTE_REASONS,
  REVIEW_DISPUTE_RESOLUTION_ACTIONS as SHARED_REVIEW_DISPUTE_RESOLUTION_ACTIONS,
  REVIEW_DISPUTE_STATUSES as SHARED_REVIEW_DISPUTE_STATUSES,
} from '@ts-shared/utils/moderation-catalogs'
import {
  REVIEW_DISPUTE_ACTIONS,
  REVIEW_DISPUTE_REASONS,
  REVIEW_DISPUTE_RESOLUTION_ACTIONS,
  REVIEW_DISPUTE_STATUSES,
} from './config.mts'

describe('review dispute config', () => {
  it('re-exports shared moderation catalogs', () => {
    expect(REVIEW_DISPUTE_REASONS).toBe(SHARED_REVIEW_DISPUTE_REASONS)
    expect(REVIEW_DISPUTE_STATUSES).toBe(SHARED_REVIEW_DISPUTE_STATUSES)
    expect(REVIEW_DISPUTE_ACTIONS).toBe(SHARED_REVIEW_DISPUTE_ACTIONS)
    expect(REVIEW_DISPUTE_RESOLUTION_ACTIONS).toBe(SHARED_REVIEW_DISPUTE_RESOLUTION_ACTIONS)
  })
})
