import { isMessageDescriptor } from './message-descriptors.mts'
import type { NativeConsumer, NativeConsumerManifestEntry } from './native-consumer-manifest.mts'
import { nativeKeyIdentifier } from './native-consumer-usage.mts'
import {
  getNativeCatalogLeaf,
  nativeLeafVariants,
  type NativeCatalogs,
  type NativeResourceLocale,
} from './native-resource-catalog.mts'

export function renderNativeSwiftStrings(
  consumer: NativeConsumer,
  locale: NativeResourceLocale,
  manifest: readonly NativeConsumerManifestEntry[],
  catalogs: NativeCatalogs,
): string {
  const rows = entriesForConsumer(consumer, locale, manifest, catalogs)
  return `// Generated by pnpm run native-localization:generate. Do not edit.\n${rows
    .map(([key, value]) => `"${key}" = "${swiftEscape(value)}";`)
    .join('\n')}\n`
}

export function renderNativeResx(
  consumer: NativeConsumer,
  locale: NativeResourceLocale,
  manifest: readonly NativeConsumerManifestEntry[],
  catalogs: NativeCatalogs,
): string {
  const data = entriesForConsumer(consumer, locale, manifest, catalogs)
    .map(
      ([key, value]) =>
        `  <data name="${xmlEscape(key)}" xml:space="preserve"><value>${xmlEscape(value)}</value></data>`,
    )
    .join('\n')
  return `<?xml version="1.0" encoding="utf-8"?>\n<root>\n${data}\n</root>\n`
}

export function renderNativeSwiftKeys(manifest: readonly NativeConsumerManifestEntry[]): string {
  const entries = manifest.filter(entry => entry.consumers.includes('swift'))
  return `// Generated by pnpm run native-localization:generate. Do not edit.\npublic struct UiMessageKey: Hashable, Sendable {\n    public let rawValue: String\n    public init(rawValue: String) { self.rawValue = rawValue }\n${entries.map(entry => `    public static let ${nativeKeyIdentifier(entry.key, 'swift')} = UiMessageKey(rawValue: "${entry.key}")`).join('\n')}\n}\n`
}

export function renderNativeDotnetKeys(manifest: readonly NativeConsumerManifestEntry[]): string {
  const entries = manifest.filter(entry => entry.consumers.includes('dotnet'))
  return `// Generated by pnpm run native-localization:generate. Do not edit.\n#nullable enable\nnamespace Voucha.Client.Core.Localization;\n\npublic readonly record struct UiMessageKey(string Value)\n{\n${entries.map(entry => `    public static readonly UiMessageKey ${nativeKeyIdentifier(entry.key, 'dotnet')} = new("${entry.key}");`).join('\n')}\n\n    public static IReadOnlyList<UiMessageKey> All { get; } =\n    [\n${entries.map(entry => `        ${nativeKeyIdentifier(entry.key, 'dotnet')},`).join('\n')}\n    ];\n}\n`
}

export function renderNativeSwiftDescriptors(
  manifest: readonly NativeConsumerManifestEntry[],
  catalogs: NativeCatalogs,
): string {
  const values = descriptorRows('swift', manifest, catalogs).map(({ key, descriptor }) => {
    const select = descriptor.kind === 'select-plural' ? `"${descriptor.selectParameter}"` : 'nil'
    const cases =
      descriptor.kind === 'select-plural' ? Object.keys(descriptor.cases).toSorted() : []
    return `    .${nativeKeyIdentifier(key, 'swift')}: UiMessageDescriptor(kind: .${nativeKeyIdentifier(descriptor.kind, 'swift')}, valueParameter: "${descriptor.valueParameter}", selectParameter: ${select}, numberParameters: ${JSON.stringify(descriptor.numberParameters ?? [])}, cases: ${JSON.stringify(cases)})`
  })
  return `// Generated by pnpm run native-localization:generate. Do not edit.\npublic struct UiMessageDescriptor: Sendable {\n    public enum Kind: Sendable { case plural, selectPlural }\n    public let kind: Kind\n    public let valueParameter: String\n    public let selectParameter: String?\n    public let numberParameters: [String]\n    public let cases: [String]\n}\n\npublic let uiMessageDescriptors: [UiMessageKey: UiMessageDescriptor] = [\n${values.join(',\n')}\n]\n`
}

export function renderNativeDotnetDescriptors(
  manifest: readonly NativeConsumerManifestEntry[],
  catalogs: NativeCatalogs,
): string {
  const values = descriptorRows('dotnet', manifest, catalogs).map(({ key, descriptor }) => {
    const select = descriptor.kind === 'select-plural' ? `"${descriptor.selectParameter}"` : 'null'
    const cases =
      descriptor.kind === 'select-plural' ? Object.keys(descriptor.cases).toSorted() : []
    return `        [UiMessageKey.${nativeKeyIdentifier(key, 'dotnet')}] = new(UiMessageDescriptorKind.${nativeKeyIdentifier(descriptor.kind, 'dotnet')}, "${descriptor.valueParameter}", ${select}, [${(descriptor.numberParameters ?? []).map(value => `"${value}"`).join(', ')}], [${cases.map(value => `"${value}"`).join(', ')}])`
  })
  return `// Generated by pnpm run native-localization:generate. Do not edit.\n#nullable enable\nnamespace Voucha.Client.Core.Localization;\n\npublic enum UiMessageDescriptorKind { Plural, SelectPlural }\npublic sealed record UiMessageDescriptor(UiMessageDescriptorKind Kind, string ValueParameter, string? SelectParameter, IReadOnlyList<string> NumberParameters, IReadOnlyList<string> Cases);\n\npublic static class UiMessageDescriptors\n{\n    public static IReadOnlyDictionary<UiMessageKey, UiMessageDescriptor> All { get; } =\n        new Dictionary<UiMessageKey, UiMessageDescriptor>\n        {\n${values.join(',\n')}\n        };\n}\n`
}

function entriesForConsumer(
  consumer: NativeConsumer,
  locale: NativeResourceLocale,
  manifest: readonly NativeConsumerManifestEntry[],
  catalogs: NativeCatalogs,
): Array<readonly [string, string]> {
  return manifest.flatMap(entry =>
    entry.consumers.includes(consumer)
      ? nativeLeafVariants(entry.key, getNativeCatalogLeaf(catalogs[locale], entry.key))
      : [],
  )
}

function descriptorRows(
  consumer: NativeConsumer,
  manifest: readonly NativeConsumerManifestEntry[],
  catalogs: NativeCatalogs,
) {
  return manifest.flatMap(entry => {
    if (!entry.consumers.includes(consumer)) return []
    const descriptor = getNativeCatalogLeaf(catalogs.en, entry.key)
    return isMessageDescriptor(descriptor) ? [{ key: entry.key, descriptor }] : []
  })
}

function swiftEscape(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\n', '\\n')
}

function xmlEscape(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;')
}
