import {
  Ban,
  BarChart3,
  BellCheck,
  BellPlus,
  Bookmark,
  BookmarkCheck,
  Copy,
  EyeOff,
  Flag,
  Link2,
  MessageSquare,
  MessageSquarePlus,
  MessageSquareQuote,
  MessageSquareReply,
  MoreHorizontal,
  Pencil,
  PenLine,
  Play,
  Rss,
  Send,
  Share2,
  Trash2,
  Undo2,
  UserMinus,
  UserPlus,
  X,
} from 'lucide-react'

// Semantic aliases are intentional: shared glyphs still keep distinct action names
// so UI code says what the action means instead of which icon happens to render.
export const EntityActionIcons = {
  block: Ban,
  commentCount: MessageSquare,
  copy: Copy,
  delete: Trash2,
  discussionLink: MessageSquare,
  edit: Pencil,
  follow: UserPlus,
  hide: EyeOff,
  join: UserPlus,
  leave: UserMinus,
  listen: Play,
  more: MoreHorizontal,
  mute: EyeOff,
  notificationDismiss: Trash2,
  proxyFollow: UserPlus,
  proxyMute: EyeOff,
  quote: MessageSquareQuote,
  recommendationDismiss: X,
  recommendationWithdraw: Undo2,
  referralLink: Link2,
  referralLinkCreate: Link2,
  report: Flag,
  reply: MessageSquareReply,
  rssFeed: Rss,
  save: Bookmark,
  saved: BookmarkCheck,
  sendChatMessage: Send,
  sendToFollowers: Send,
  shareDataPoint: BarChart3,
  shareWithFollowers: Share2,
  startDiscussion: MessageSquarePlus,
  subscribe: BellPlus,
  subscribed: BellCheck,
  unfollow: UserMinus,
  writeReview: PenLine,
} as const

export type EntityActionIconKey = keyof typeof EntityActionIcons
