import type {
  AdminClusteredModerationReportsResponse,
  AdminModerationReport,
  AdminModerationReportsResponse,
} from '@/components/admin/reports-client'

export const report: AdminModerationReport = {
  id: 'report-1',
  case_id: 'case-1',
  created_at: '2026-05-31T06:00:00.000Z',
  reviewed_at: null,
  reporter_user_id: 'reporter-1',
  reporter_username: 'careful-reader',
  entity_type: 'post',
  entity_id: 'post-1',
  target_content: null,
  target_label: 'Suspicious referral offer',
  target_path: '/discussion/suspicious-referral-offer',
  admin_action_path: '/discussion/suspicious-referral-offer',
  target_user_id: 'user-2',
  target_available: true,
  target_is_restricted: false,
  reason: 'spam',
  note: 'This appears to be copied across several communities.',
  status: 'pending',
  report_count: 3,
  resolved_by_id: null,
  is_system_generated: false,
  judgement: {
    recommended_action: 'remove',
    public_response: 'This content was removed for violating our spam policy.',
    internal_response:
      'Clear spam pattern: duplicated referral links posted across multiple communities within a short time window.',
    is_stale: true,
    judged_report_count: 2,
    current_report_count: 3,
  },
  post_moderation_context: null,
}

export const banEvasionReport: AdminModerationReport = {
  id: 'report-3',
  case_id: 'case-3',
  created_at: '2026-05-31T06:30:00.000Z',
  reviewed_at: null,
  reporter_user_id: 'ban-evasion-system',
  reporter_username: 'ban-evasion-system',
  entity_type: 'user',
  entity_id: 'user-2',
  target_content: null,
  target_label: '@new-account',
  target_path: '/user/new-account',
  admin_action_path: '/user/new-account/admin',
  target_user_id: 'user-2',
  target_available: true,
  target_is_restricted: false,
  reason: 'other',
  note: null,
  status: 'pending',
  report_count: 1,
  resolved_by_id: null,
  is_system_generated: true,
  judgement: null,
  post_moderation_context: null,
  community_ban_evasion: {
    community_id: 'community-1',
    community_slug: 'test-community',
    source_user_id: 'source-user-1',
    source_username: 'banned-user',
    score: 0.82,
    flagged_at: '2026-05-31T06:30:00.000Z',
  },
}

export const data: AdminModerationReportsResponse = {
  results: [
    report,
    {
      id: 'report-2',
      case_id: 'case-2',
      created_at: '2026-05-31T06:15:00.000Z',
      reviewed_at: null,
      reporter_user_id: 'reporter-2',
      reporter_username: null,
      entity_type: 'user',
      entity_id: 'user-1',
      target_content: null,
      target_label: '@promo-account',
      target_path: '/user/promo-account',
      admin_action_path: '/user/promo-account/admin',
      target_user_id: 'user-1',
      target_available: true,
      target_is_restricted: false,
      reason: 'harassment',
      note: null,
      status: 'pending',
      report_count: 1,
      resolved_by_id: null,
      is_system_generated: false,
      judgement: null,
      post_moderation_context: null,
    },
    banEvasionReport,
  ],
  page_info: {
    has_next_page: false,
    has_previous_page: false,
    start_cursor: null,
    end_cursor: null,
  },
}

export const clusteredData: AdminClusteredModerationReportsResponse = {
  cluster_mode: 'entity',
  results: [
    {
      id: 'post:post-1',
      entity_type: 'post',
      entity_id: 'post-1',
      report_count: 3,
      reporter_count: 3,
      reason_breakdown: [
        { reason: 'spam', count: 2 },
        { reason: 'harassment', count: 1 },
      ],
      first_reported_at: '2026-05-31T06:00:00.000Z',
      last_reported_at: '2026-05-31T06:20:00.000Z',
      target_content: null,
      target_label: 'Suspicious referral offer',
      target_path: '/discussion/suspicious-referral-offer',
      admin_action_path: '/discussion/suspicious-referral-offer',
      target_user_id: 'user-2',
      target_available: true,
      target_is_restricted: false,
      indicators: {
        content_hash_duplicate: true,
        embeddings_similarity: false,
        velocity_spike: true,
      },
      reports: [report, { ...report, id: 'report-3', reporter_username: 'second-reader' }],
    },
    {
      id: 'post:post-2',
      entity_type: 'post',
      entity_id: 'post-2',
      report_count: 1,
      reporter_count: 1,
      reason_breakdown: [{ reason: 'spam', count: 1 }],
      first_reported_at: '2026-05-31T06:10:00.000Z',
      last_reported_at: '2026-05-31T06:10:00.000Z',
      target_content: null,
      target_label: 'Repeated referral offer',
      target_path: '/discussion/repeated-referral-offer',
      admin_action_path: '/discussion/repeated-referral-offer',
      target_user_id: 'user-3',
      target_available: true,
      target_is_restricted: false,
      indicators: {
        content_hash_duplicate: true,
        embeddings_similarity: false,
        velocity_spike: false,
      },
      reports: [
        {
          ...report,
          id: 'report-4',
          entity_id: 'post-2',
          target_label: 'Repeated referral offer',
          target_path: '/discussion/repeated-referral-offer',
          admin_action_path: '/discussion/repeated-referral-offer',
          note: 'Same referral link appears here.',
        },
      ],
    },
  ],
  duplicate_clusters: [
    {
      id: 'content-hash:story',
      signal: 'content_hash_duplicate',
      post_count: 2,
      report_count: 4,
      reason_breakdown: [
        { reason: 'spam', count: 3 },
        { reason: 'harassment', count: 1 },
      ],
      first_reported_at: '2026-05-31T06:00:00.000Z',
      last_reported_at: '2026-05-31T06:20:00.000Z',
      clusters: [],
    },
  ],
  page_info: {
    has_next_page: false,
    has_previous_page: false,
    start_cursor: null,
    end_cursor: null,
  },
}
