sonar.projectKey=vouchington_vouchington
sonar.organization=vouchington
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/__tests__/**,**/tests/**,**/*.test.*,**/*.spec.*,playwright/tests/**,integration-tests/**
sonar.test.exclusions=**/fixtures/**,**/__fixtures__/**,**/__snapshots__/**
sonar.exclusions=**/fixtures/**,**/__fixtures__/**,**/__snapshots__/**
