import type { ScopeDefinition } from './scope-types.mts'

export const ADMIN_RESOURCE_DEFINITIONS = {
  'moderation:read': {
    action: 'read',
    audience: 'admin',
    resource: 'moderation',
    surfaces: ['oauth'],
  },
  'moderation:write': {
    action: 'write',
    audience: 'admin',
    resource: 'moderation',
    surfaces: ['oauth'],
    requires: 'moderation:read',
  },
  'account-enforcement:read': {
    action: 'read',
    audience: 'admin',
    resource: 'account-enforcement',
    surfaces: ['oauth'],
  },
  'account-enforcement:write': {
    action: 'write',
    audience: 'admin',
    resource: 'account-enforcement',
    surfaces: ['oauth'],
    requires: 'account-enforcement:read',
  },
  'site-operations:read': {
    action: 'read',
    audience: 'admin',
    resource: 'site-operations',
    surfaces: ['oauth'],
  },
  'moderation:approve': {
    action: 'write',
    audience: 'admin',
    resource: 'moderation',
    surfaces: ['oauth'],
    requires: 'moderation:read',
    requiresExactGrant: true,
  },
  'moderation:ai-rerun': {
    action: 'write',
    audience: 'admin',
    resource: 'moderation',
    surfaces: ['oauth'],
    requires: 'moderation:read',
    requiresExactGrant: true,
  },
  'moderation:agent-votes': {
    action: 'write',
    audience: 'admin',
    resource: 'moderation',
    surfaces: ['oauth'],
    requires: 'moderation:read',
    requiresExactGrant: true,
  },
  'account-enforcement:suspend': {
    action: 'write',
    audience: 'admin',
    resource: 'account-enforcement',
    surfaces: ['oauth'],
    requires: 'account-enforcement:read',
    requiresExactGrant: true,
  },
  'account-enforcement:penalize': {
    action: 'write',
    audience: 'admin',
    resource: 'account-enforcement',
    surfaces: ['oauth'],
    requires: 'account-enforcement:read',
    requiresExactGrant: true,
  },
  'account-enforcement:vote-weight': {
    action: 'write',
    audience: 'admin',
    resource: 'account-enforcement',
    surfaces: ['oauth'],
    requires: 'account-enforcement:read',
    requiresExactGrant: true,
  },
  'site-operations:queues': {
    action: 'write',
    audience: 'admin',
    resource: 'site-operations',
    surfaces: ['oauth'],
    requires: 'site-operations:read',
    requiresExactGrant: true,
  },
  'site-operations:config': {
    action: 'write',
    audience: 'admin',
    resource: 'site-operations',
    surfaces: ['oauth'],
    requires: 'site-operations:read',
    requiresExactGrant: true,
  },
  'site-operations:jobs': {
    action: 'write',
    audience: 'admin',
    resource: 'site-operations',
    surfaces: ['oauth'],
    requires: 'site-operations:read',
    requiresExactGrant: true,
  },
  'copyright-notices:read': {
    action: 'read',
    audience: 'admin',
    resource: 'copyright-notices',
    surfaces: ['oauth'],
    requiresExactGrant: true,
  },
  'analytics:read': {
    action: 'read',
    audience: 'admin',
    resource: 'analytics',
    surfaces: ['oauth'],
    requiresExactGrant: true,
  },
  'editorial:read': {
    action: 'read',
    audience: 'admin',
    resource: 'editorial',
    surfaces: ['oauth'],
    requiresExactGrant: true,
  },
  'editorial:write': {
    action: 'write',
    audience: 'admin',
    resource: 'editorial',
    surfaces: ['oauth'],
    requires: 'editorial:read',
    requiresExactGrant: true,
  },
} satisfies Record<string, ScopeDefinition>
