export type ScopeAudience = 'admin' | 'api' | 'user'
export type ScopeCredentialSurface = 'api-key' | 'oauth'
export type ScopeAction = 'read' | 'write'
export type ScopeDescriptionKey =
  | 'mcp_admin_full_access'
  | 'mcp_user_full_access'
  | 'financial_profile_read'
  | 'financial_profile_write'
  | 'spending_read'
  | 'spending_write'

export type ApiScope =
  | 'appeals:read'
  | 'appeals:write'
  | 'bookmarks:read'
  | 'bookmarks:write'
  | 'moderation:read'
  | 'moderation:write'
  | 'account-enforcement:read'
  | 'account-enforcement:write'
  | 'site-operations:read'
  | 'moderation:approve'
  | 'moderation:ai-rerun'
  | 'moderation:agent-votes'
  | 'account-enforcement:suspend'
  | 'account-enforcement:penalize'
  | 'account-enforcement:vote-weight'
  | 'site-operations:queues'
  | 'site-operations:config'
  | 'site-operations:jobs'
  | 'copyright-notices:read'
  | 'copyright-notices:write'
  | 'analytics:read'
  | 'editorial:read'
  | 'editorial:write'
  | 'cards:read'
  | 'cards:write'
  | 'communities:read'
  | 'communities:write'
  | 'data-points:read'
  | 'disputes:read'
  | 'disputes:write'
  | 'domain-ratings:read'
  | 'entity-relations:read'
  | 'entity-relations:write'
  | 'financial-profile:read'
  | 'financial-profile:write'
  | 'hostnames:read'
  | 'lists:read'
  | 'lists:write'
  | 'mcp.admin:read'
  | 'mcp.admin:write'
  | 'mcp.user:read'
  | 'mcp.user:write'
  | 'notifications:read'
  | 'notifications:write'
  | 'point-valuations:read'
  | 'point-valuations:write'
  | 'post-relations.owned-private:write'
  | 'posts:read'
  | 'posts:write'
  | 'preferences:read'
  | 'preferences:write'
  | 'profile:read'
  | 'profile:write'
  | 'recommendations:read'
  | 'reference-data:read'
  | 'referral-links:read'
  | 'referral-links:write'
  | 'reports:write'
  | 'rewards-statuses:read'
  | 'rewards-statuses:write'
  | 'rss:read'
  | 'rss-feeds:read'
  | 'rss-feed-items:read'
  | 'feeds:read'
  | 'spending:read'
  | 'spending:write'
  | 'topic-recommendations:read'
  | 'topic-recommendations:write'
  | 'topics:read'
  | 'users:read'
  | 'web-search:read'

export type ScopeDefinition = {
  action: ScopeAction
  audience: ScopeAudience
  descriptionKey?: ScopeDescriptionKey
  resource: string
  surfaces: readonly ScopeCredentialSurface[]
  requires?: string
  requiresExactGrant?: boolean
}
