export const SPECIALIZED_INGRESS = {
  'POST:/api/v1/mcp': {
    parser: 'MCP SDK JSON-RPC transport',
    evidence: 'backend/api/v1/mcp/mcp.test.mts',
    proof: 'does not disclose malformed MCP schemas before API-key authentication',
  },
  'POST:/api/v1/admin/mcp': {
    parser: 'MCP SDK JSON-RPC transport after admin OAuth admission',
    evidence: 'backend/api/v1/admin/mcp.request-boundary.test.mts',
    proof: 'answers authenticated malformed JSON with the body reader 400',
  },
  'POST:/api/v1/memberships/apple-app-store/notifications': {
    parser: 'Apple signed JWS verifier and notification decoder',
    evidence: 'backend/api/v1/memberships/__tests__/apple-notifications.test.mts',
    proof: 'rejects malformed and oversized bodies without a schema diagnostic',
  },
  'POST:/api/v1/memberships/google-play/notifications': {
    parser: 'Google Pub/Sub OIDC verifier and RTDN envelope decoder',
    evidence: 'backend/api/v1/memberships/__tests__/google-play-notifications.test.mts',
    proof: 'answers an oversized envelope with the specialized 401',
  },
  'POST:/api/v1/email-unsubscribe': {
    parser: 'signed unsubscribe token parser from query or JSON body',
    evidence: 'backend/api/v1/my/__tests__/email-preferences.test.mts',
    proof: 'rejects an invalid unsubscribe token without login',
  },
  'GET:/api/v1/auth/oauth/:provider/broker-callback': {
    parser: 'OAuth provider, state, and callback result verifier',
    evidence: 'backend/api/v1/sessions-authentication/__tests__/auth-oauth-broker.test.mts',
    proof: 'relays web and native callbacks through their dedicated handoffs',
  },
  'GET:/api/v1/auth/bluesky/callback': {
    parser:
      'AT Protocol code/state verifier (peekBlueskyAccountLinkAppState / completeBlueskyAccountLink)',
    evidence:
      'backend/api/v1/sessions-authentication/__tests__/auth-bluesky-invalid-state.test.mts',
    proof: 'invalid saved app state',
  },
  'GET:/ap/users/:userId': {
    parser: 'ActivityPub actor UUID path parser',
    evidence: 'backend/api/activitypub/actor.test.mts',
    proof: 'returns 422 for a non-UUID userId',
  },
  'POST:/ap/inbox': {
    parser: 'ActivityPub raw-body digest and HTTP signature verifier',
    evidence: 'backend/api/activitypub/inbox.test.mts',
    proof: 'body digest is mismatched',
  },
  'GET:/.well-known/webfinger': {
    parser: 'WebFinger account resource parser',
    evidence: 'backend/api/activitypub/webfinger.test.mts',
    proof: 'returns 400 when resource is missing',
  },
  'GET:/authorize': {
    parser: 'OAuth authorization request parser and redirect guard',
    evidence: 'backend/api/oauth/oauth.test.mts',
    proof: 'never redirects an authorization error to an unregistered URI',
  },
  'POST:/register': {
    parser: 'OAuth dynamic client registration body parser',
    evidence: 'backend/api/oauth/registration.test.mts',
    proof: 'malformed JSON',
  },
  'POST:/token': {
    parser: 'OAuth token form and client authentication parser',
    evidence: 'backend/api/oauth/token-protocol.test.mts',
    proof: 'rejects duplicate form parameters',
  },
  'POST:/revoke': {
    parser: 'OAuth revocation form and client authentication parser',
    evidence: 'backend/api/oauth/token-protocol.test.mts',
    proof: 'requires a registered client for token revocation',
  },
  'GET:/api/v1/oauth/authorization-requests/:id': {
    parser: 'OAuth consent authentication, session binding, and UUID path parser',
    evidence: 'backend/api/oauth/token-protocol.test.mts',
    proof: 'not-a-uuid',
  },
  'POST:/api/v1/oauth/authorization-requests/:id/decisions': {
    parser: 'OAuth consent decision parser after authentication and suspension checks',
    evidence: 'backend/api/oauth/token-protocol.test.mts',
    proof: 'Invalid id',
  },
} as const

export const SPECIALIZED_QUERY_INPUTS = {
  'GET:/api/v1/auth/oauth/:provider/broker-callback': ['state', 'code', 'error'],
  'POST:/api/v1/email-unsubscribe': ['token'],
  'GET:/api/v1/users/:idOrSlug/data-request/stream': ['request_id'],
  'GET:/.well-known/webfinger': ['resource'],
  'GET:/authorize': [
    '*',
    'code_challenge',
    'code_challenge_method',
    'resource',
    'response_type',
    'scope',
    'state',
  ],
} as const

export const SPECIALIZED_HEADER_INPUTS = {
  'POST:/api/v1/copyright-notices/:id/guest-filings': {
    parser: 'Copyright guest capability admission, preserved as a secret header',
    evidence: 'backend/api/v1/copyright-notices/guest-capability-request-validation.test.mts',
    proof: 'Copyright-Guest-Capability',
  },
  'POST:/api/v1/posts': {
    parser: 'Contribution admission Idempotency-Key parser preserves its coded 400',
    evidence: 'backend/api/v1/posts/__tests__/post.request-validation.test.mts',
    proof: 'preserves the coded 400 for a malformed Idempotency-Key',
  },
  'POST:/api/v1/rss-feed-items/:id/discussions': {
    parser: 'Contribution admission Idempotency-Key parser preserves malformed-header status',
    evidence: 'backend/api/v1/rss-feed-items/discussion.test.mts',
    proof: 'rejects a malformed Idempotency-Key header before mutation',
  },
  'POST:/api/v1/topic-recommendations': {
    parser: 'Contribution admission Idempotency-Key parser preserves its coded 400',
    evidence: 'backend/api/v1/topic-recommendations/__tests__/request-validation.test.mts',
    proof: 'lets a malformed Idempotency-Key keep its coded 400',
  },
} as const

// A newly added route with no validator must be reviewed and placed here only when its source and
// generated contract both prove it has no request input to validate.
export const NO_INPUT_OPERATIONS: readonly string[] = [
  'DELETE:/api/v1/admin/mcp',
  'DELETE:/api/v1/auth/bluesky/link',
  'DELETE:/api/v1/mcp',
  'GET:/api/v1/admin/mcp',
  'GET:/api/v1/admin/postgresql/stream',
  'GET:/api/v1/admin/topic-claims',
  'GET:/api/v1/admin/valkey/stream',
  'GET:/api/v1/auth/me',
  'GET:/api/v1/auth/mfa/status',
  'GET:/api/v1/auth/oauth/providers',
  'GET:/api/v1/captcha-config',
  'GET:/api/v1/countries',
  'GET:/api/v1/dynamic-config/namespaces',
  'GET:/api/v1/feature-flags',
  'GET:/api/v1/mcp',
  'GET:/api/v1/me/individual',
  'GET:/api/v1/memberships/me',
  'GET:/api/v1/memberships/plans',
  'GET:/api/v1/moderation/exposure',
  'GET:/api/v1/mq/backfills',
  'GET:/api/v1/mq/queues',
  'GET:/api/v1/mq/scheduled-jobs',
  'GET:/api/v1/mq/stats',
  'GET:/api/v1/mq/stream',
  'GET:/api/v1/my/aside-preferences',
  'GET:/api/v1/my/consents',
  'GET:/api/v1/my/email-preferences',
  'GET:/api/v1/my/financial-profile',
  'GET:/api/v1/my/identity',
  'GET:/api/v1/my/identity-verification',
  'GET:/api/v1/my/identity-verification/session-url',
  'GET:/api/v1/my/landing-pages',
  'GET:/api/v1/my/landing-pages/candidates',
  'GET:/api/v1/my/notifications/unread',
  'GET:/api/v1/my/profile',
  'GET:/api/v1/my/profile/links',
  'GET:/api/v1/my/topic-claims',
  'GET:/api/v1/platform-stats',
  'GET:/api/v1/psql/migrations',
  'GET:/api/v1/psql/partitions',
  'GET:/api/v1/scopes',
  'GET:/api/v1/topics/publisher-types',
  'GET:/api/v1/topics/user-tags',
  'GET:/api/v1/valkey/cache-groups',
  'POST:/api/v1/article-syncs',
  'POST:/api/v1/auth/mfa/re-auth/email/tokens',
  'POST:/api/v1/auth/passkeys/authentication/options',
  'POST:/api/v1/auth/passkeys/registration/options',
  'POST:/api/v1/auth/sessions/revocations',
  'POST:/api/v1/blacklist/dispatch',
  'POST:/api/v1/copyright-media-delivery/replays',
  'POST:/api/v1/memberships/microsoft-store/service-tickets',
  'POST:/api/v1/my/identity-verification/checkout-sessions',
  'POST:/api/v1/my/notifications/read-all',
  'GET:/.well-known/nodeinfo',
  'GET:/nodeinfo/2.0',
  'GET:/.well-known/oauth-authorization-server',
  'GET:/.well-known/oauth-protected-resource/api/v1/mcp',
  'GET:/.well-known/oauth-protected-resource/api/v1/admin/mcp',
  'GET:/client-metadata.json',
]
