#!/usr/bin/env bash
# Source this file to use db_name_from_url.
# Usage: DB_NAME=$(db_name_from_url)
# Reads DATABASE_URL from the environment. Returns an empty string when
# DATABASE_URL is unset, empty, or has no path component.
# db_host_from_url, db_port_from_url, db_user_from_url, db_password_from_url,
# db_hostaddr_from_url and SSL env extraction read DATABASE_URL and return empty
# when the URL has no matching component.
# export_pg_env_from_database_url exports PGHOST / PGPORT / PGUSER / PGPASSWORD,
# PGHOSTADDR, PGSERVICE, PGSERVICEFILE, PGTARGETSESSIONATTRS, and common
# PGSSL* env vars from DATABASE_URL only when those env vars are not already set.

url_decode() {
  local encoded=$1
  printf '%b' "${encoded//%/\\x}"
}

# Parse literal shell assignment values generated by printf %q. This does not
# expand variable references, command substitutions, or other shell expressions.
shell_unquote_env_value() {
  local raw=$1
  local out=""
  local quote=""
  local ch next
  local i=0
  local len=${#raw}

  while [ "$i" -lt "$len" ]; do
    ch=${raw:$i:1}
    if [ -z "$quote" ]; then
      if [ "$ch" = "'" ]; then
        quote="'"
      elif [ "$ch" = '"' ]; then
        quote='"'
      elif [ "$ch" = " " ] || [ "$ch" = $'\t' ]; then
        break
      elif [ "$ch" = "\\" ]; then
        i=$((i + 1))
        if [ "$i" -lt "$len" ]; then
          out+=${raw:$i:1}
        fi
      else
        out+=$ch
      fi
    elif [ "$quote" = "'" ]; then
      if [ "$ch" = "'" ]; then
        quote=""
      else
        out+=$ch
      fi
    else
      if [ "$ch" = '"' ]; then
        quote=""
      elif [ "$ch" = "\\" ]; then
        i=$((i + 1))
        if [ "$i" -lt "$len" ]; then
          next=${raw:$i:1}
          out+=$next
        fi
      else
        out+=$ch
      fi
    fi
    i=$((i + 1))
  done

  printf '%s' "$out"
}

env_value_from_file() {
  local env_file=$1
  local key=$2
  [ -f "$env_file" ] || return 0
  local raw
  raw=$(awk -v key="$key" '
    $0 ~ "^export[[:space:]]+" key "=" {
      sub("^export[[:space:]]+" key "=", "")
      print
      exit
    }
    $0 ~ "^" key "=" {
      sub("^" key "=", "")
      print
      exit
    }
  ' "$env_file")
  if [ -n "$raw" ]; then
    shell_unquote_env_value "$raw"
  fi
  return 0
}

env_database_url_from_file() {
  env_value_from_file "$1" DATABASE_URL
}

pg_host_part_is_local() {
  local host=${1:-}
  [ -z "$host" ] && return 0
  case "$host" in
    /*|localhost|::1) return 0 ;;
  esac
  local ipv4_octet='([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
  if [[ "$host" =~ ^127\.$ipv4_octet\.$ipv4_octet\.$ipv4_octet$ ]]; then
    return 0
  fi
  return 1
}

pg_host_list_is_local() {
  local hosts=${1:-}
  [ -z "$hosts" ] && return 0
  case "$hosts" in
    ,*|*,,*|*,) return 1 ;;
  esac
  local host
  local IFS=','
  for host in $hosts; do
    pg_host_part_is_local "$host" || return 1
  done
}

pg_database_target_is_local() {
  [ -n "${PGSERVICE:-}" ] && return 1
  if [ -n "${PGHOSTADDR:-}" ]; then
    pg_host_list_is_local "$PGHOSTADDR"
    return
  fi
  pg_host_list_is_local "${PGHOST:-}"
}

db_name_from_url() {
  local query_dbname
  query_dbname="$(db_query_param_from_url dbname)"
  if [ -n "$query_dbname" ]; then
    printf '%s' "$query_dbname"
    return 0
  fi

  local url="${DATABASE_URL:-}"
  [ -z "$url" ] && return 0
  # Strip query string first (handles postgres://host/db/?opts as well as postgres://host/db?opts)
  local path="${url%%\?*}"
  # Strip trailing slash if present (handles postgres://host/db/)
  path="${path%/}"
  # Strip scheme+authority: require a slash after the scheme, so host-only URLs
  # (e.g. postgres://localhost with no db path) return empty rather than the hostname.
  local url_no_scheme="${path#*://}"
  if [[ "$url_no_scheme" == *"/"* ]]; then
    path="${url_no_scheme##*/}"
  else
    path=""
  fi
  [ -n "$path" ] && url_decode "$path"
  return 0
}

db_query_param_from_url() {
  local key=$1
  local url="${DATABASE_URL:-}"
  [[ "$url" == *\?* ]] || return 0
  local query="${url#*\?}"
  local param name value matched_value
  local IFS='&'
  for param in $query; do
    name="${param%%=*}"
    if [ "$name" = "$key" ]; then
      if [[ "$param" == *=* ]]; then
        value="${param#*=}"
      else
        value=""
      fi
      matched_value=$value
    fi
  done
  [ -n "${matched_value+x}" ] && url_decode "$matched_value"
  return 0
}

db_authority_raw_from_url() {
  local url="${DATABASE_URL:-}"
  [ -z "$url" ] && return 0
  local without_query="${url%%\?*}"
  local url_no_scheme="${without_query#*://}"
  printf '%s' "${url_no_scheme%%/*}"
}

db_authority_from_url() {
  local authority
  authority="$(db_authority_raw_from_url)"
  [ -z "$authority" ] && return 0
  printf '%s' "${authority##*@}"
}

db_userinfo_from_url() {
  local authority
  authority="$(db_authority_raw_from_url)"
  [ -z "$authority" ] && return 0
  if [[ "$authority" == *@* ]]; then
    printf '%s' "${authority%@*}"
  fi
}

db_user_from_url() {
  local userinfo query_user
  query_user="$(db_query_param_from_url user)"
  if [ -n "$query_user" ]; then
    printf '%s' "$query_user"
    return 0
  fi
  userinfo="$(db_userinfo_from_url)"
  if [ -n "$userinfo" ]; then
    url_decode "${userinfo%%:*}"
  fi
  return 0
}

db_password_from_url() {
  local userinfo query_password
  query_password="$(db_query_param_from_url password)"
  if [ -n "$query_password" ]; then
    printf '%s' "$query_password"
    return 0
  fi
  userinfo="$(db_userinfo_from_url)"
  if [ -n "$userinfo" ] && [[ "$userinfo" == *:* ]]; then
    url_decode "${userinfo#*:}"
  fi
  return 0
}

db_host_from_authority_part() {
  local authority=$1
  if [[ "$authority" == \[*\]* ]]; then
    local ip="${authority%%]*}"
    printf '%s' "${ip#\[}"
    return 0
  fi
  url_decode "${authority%%:*}"
}

db_port_from_authority_part() {
  local authority=$1
  if [[ "$authority" == \[*\] ]]; then
    return 0
  fi
  if [[ "$authority" == \[*\]:* ]]; then
    printf '%s' "${authority##*:}"
    return 0
  fi
  if [[ "$authority" == *:* ]]; then
    printf '%s' "${authority##*:}"
  fi
}

db_host_from_url() {
  local authority query_host
  query_host="$(db_query_param_from_url host)"
  if [ -n "$query_host" ]; then
    printf '%s' "$query_host"
    return 0
  fi

  authority="$(db_authority_from_url)"
  if [ -n "$authority" ]; then
    local hosts=()
    local part
    local IFS=','
    for part in $authority; do
      hosts+=("$(db_host_from_authority_part "$part")")
    done
    local joined
    IFS=,
    joined="${hosts[*]}"
    printf '%s' "$joined"
  fi
  return 0
}

db_hostaddr_from_url() {
  db_query_param_from_url hostaddr
}

db_port_from_url() {
  local authority query_port
  query_port="$(db_query_param_from_url port)"
  if [ -n "$query_port" ]; then
    printf '%s' "$query_port"
    return 0
  fi

  authority="$(db_authority_from_url)"
  if [ -n "$authority" ]; then
    local ports=()
    local port part
    local IFS=','
    for part in $authority; do
      port="$(db_port_from_authority_part "$part")"
      ports+=("$port")
    done
    local joined
    IFS=,
    joined="${ports[*]}"
    [ -n "$joined" ] && printf '%s' "$joined"
  fi
  return 0
}

export_pg_ssl_env_from_database_url() {
  local param value env_name
  for param in sslmode sslcert sslkey sslrootcert sslcrl sslcrldir; do
    value="$(db_query_param_from_url "$param")"
    [ -z "$value" ] && continue
    case "$param" in
      sslmode) env_name=PGSSLMODE ;;
      sslcert) env_name=PGSSLCERT ;;
      sslkey) env_name=PGSSLKEY ;;
      sslrootcert) env_name=PGSSLROOTCERT ;;
      sslcrl) env_name=PGSSLCRL ;;
      sslcrldir) env_name=PGSSLCRLDIR ;;
    esac
    if [ -z "${!env_name:-}" ]; then
      export "$env_name=$value"
    fi
  done
}

export_pg_env_from_database_url() {
  local db_host db_hostaddr db_port db_user db_password
  db_host=$(db_host_from_url)
  db_hostaddr=$(db_hostaddr_from_url)
  db_port=$(db_port_from_url)
  db_user=$(db_user_from_url)
  db_password=$(db_password_from_url)

  if [ -n "$db_host" ] && [ -z "${PGHOST:-}" ]; then
    export PGHOST="$db_host"
  fi
  if [ -n "$db_hostaddr" ] && [ -z "${PGHOSTADDR:-}" ]; then
    export PGHOSTADDR="$db_hostaddr"
  fi
  local db_service db_servicefile
  db_service="$(db_query_param_from_url service)"
  db_servicefile="$(db_query_param_from_url servicefile)"
  if [ -n "$db_service" ] && [ -z "${PGSERVICE:-}" ]; then
    export PGSERVICE="$db_service"
  fi
  if [ -n "$db_servicefile" ] && [ -z "${PGSERVICEFILE:-}" ]; then
    export PGSERVICEFILE="$db_servicefile"
  fi
  local db_target_session_attrs
  db_target_session_attrs="$(db_query_param_from_url target_session_attrs)"
  if [ -n "$db_target_session_attrs" ] && [ -z "${PGTARGETSESSIONATTRS:-}" ]; then
    export PGTARGETSESSIONATTRS="$db_target_session_attrs"
  fi
  if [ -n "$db_port" ] && [ -z "${PGPORT:-}" ]; then
    export PGPORT="$db_port"
  fi
  if [ -n "$db_user" ] && [ -z "${PGUSER:-}" ]; then
    export PGUSER="$db_user"
  fi
  if [ -n "$db_password" ] && [ -z "${PGPASSWORD:-}" ]; then
    export PGPASSWORD="$db_password"
  fi
  export_pg_ssl_env_from_database_url
}
