import { action, collection, relation } from '../builders.mts'

export const COMMUNITY_COLLECTIONS = [
  collection({
    id: 'communities-saved',
    group: 'communities',
    routeSegment: 'communities',
    routeListType: 'saved',
    access: 'owner',
    metricKey: 'communities_saved',
    tabLabel: 'Saved',
    action: action(
      'community',
      'saved',
      'community',
      'save',
      'extracted.userProfileCollections.communities.saved_b5c120b3',
      'extracted.userProfileCollections.communities.save_1509f561',
      'extracted.userProfileCollections.communities.savedCommunity_4fd43d27',
    ),
    relation: relation(
      'relation__user__save__community',
      'community',
      'save',
      'object',
      'communities',
    ),
  }),
  collection({
    id: 'communities-proxy-following',
    group: 'communities',
    routeSegment: 'communities',
    routeListType: 'proxy-following',
    serviceListType: 'proxy_following',
    access: 'owner',
    metricKey: 'communities_proxy_following',
    tabLabel: 'Proxy Following',
    action: action(
      'community',
      'proxyFollowing',
      'community',
      'proxy_follow',
      'extracted.userProfileCollections.communities.proxyFollowing_c774648f',
      'extracted.userProfileCollections.communities.proxyFollow_a315cb28',
      'extracted.userProfileCollections.communities.proxyFollowedCommunity_8bf816e3',
    ),
    relation: relation(
      'relation__user__proxy_follow__community',
      'community',
      'proxy_follow',
      'object',
      'communities',
    ),
  }),
  collection({
    id: 'communities-proxy-muted',
    group: 'communities',
    routeSegment: 'communities',
    routeListType: 'proxy-muted',
    serviceListType: 'proxy_muted',
    access: 'owner',
    metricKey: 'communities_proxy_muted',
    tabLabel: 'Proxy Muted',
    action: action(
      'community',
      'proxyMuted',
      'community',
      'proxy_mute',
      'extracted.userProfileCollections.communities.proxyMuted_1795979b',
      'extracted.userProfileCollections.communities.proxyMute_59134c33',
      'extracted.userProfileCollections.communities.proxyMutedCommunity_96e726fc',
    ),
    relation: relation(
      'relation__user__proxy_mute__community',
      'community',
      'proxy_mute',
      'object',
      'communities',
    ),
  }),
  collection({
    id: 'communities-member',
    group: 'communities',
    topLevelTab: 'communities',
    routeSegment: 'communities',
    routeListType: 'member',
    serviceListType: 'member',
    access: 'public',
    visibilityField: 'community_memberships_visibility',
    metricGroup: 'count',
    metricKey: 'communities_member',
    tabLabel: 'Member',
    managementTab: false,
  }),
] as const
