import { action, collection, relation } from '../builders.mts'

export const POST_COLLECTIONS = [
  collection({
    id: 'posts-saved',
    group: 'posts',
    routeSegment: 'posts',
    routeListType: 'saved',
    access: 'owner',
    metricKey: 'posts_saved',
    tabLabel: 'Saved',
    action: action(
      'post',
      'saved',
      'post',
      'save',
      'extracted.userProfileCollections.postsTopics.saved_b5c120b3',
      'extracted.userProfileCollections.postsTopics.save_1509f561',
      'extracted.userProfileCollections.postsTopics.savedPost_f7486726',
    ),
    relation: relation('relation__user__save__post', 'post', 'save', 'object', 'posts'),
  }),
  collection({
    id: 'posts-hidden',
    group: 'posts',
    routeSegment: 'posts',
    routeListType: 'hidden',
    access: 'owner',
    metricKey: 'posts_hidden',
    tabLabel: 'Hidden',
    action: action(
      'post',
      'hidden',
      'post',
      'hide',
      'extracted.userProfileCollections.postsTopics.hidden_7e6fefff',
      'extracted.userProfileCollections.postsTopics.hide_ac20a57b',
      'extracted.userProfileCollections.postsTopics.hiddenPost_b1188589',
    ),
    relation: relation('relation__user__hide__post', 'post', 'hide', 'object', 'posts'),
  }),
  collection({
    id: 'posts-following',
    group: 'posts',
    routeSegment: 'posts',
    routeListType: 'following',
    access: 'owner',
    metricKey: 'posts_following',
    tabLabel: 'Following',
    action: action(
      'post',
      'following',
      'post',
      'follow',
      'extracted.userProfileCollections.postsTopics.following_344b4271',
      'extracted.userProfileCollections.postsTopics.follow_641d1ef6',
      'extracted.userProfileCollections.postsTopics.followedPost_2f15d771',
    ),
    relation: relation('relation__user__follow__post', 'post', 'follow', 'object', 'posts'),
  }),
  collection({
    id: 'posts-subscribed',
    group: 'posts',
    routeSegment: 'posts',
    routeListType: 'subscribed',
    access: 'owner',
    metricKey: 'posts_subscribed',
    tabLabel: 'Subscribed',
    action: action(
      'post',
      'subscribed',
      'post',
      'subscribe',
      'extracted.userProfileCollections.postsTopics.subscribed_25c4797c',
      'extracted.userProfileCollections.postsTopics.subscribe_cc0e38da',
      'extracted.userProfileCollections.postsTopics.postSubscription_1d561be5',
    ),
    relation: relation('relation__user__subscribe__post', 'post', 'subscribe', 'object', 'posts'),
  }),
] as const
