import { action, collection, relation } from '../builders.mts'

export const RSS_FEED_COLLECTIONS = [
  collection({
    id: 'rss-following',
    group: 'rss',
    topLevelTab: 'rss',
    routeSegment: 'rss-feeds',
    routeListType: 'following',
    access: 'public',
    visibilityField: 'rss_feed_follows_visibility',
    metricGroup: 'count',
    metricKey: 'rss_feeds_following',
    tabValue: 'rss-following',
    tabLabel: 'Followed Feeds',
    communityTab: true,
    communityTabLabel: 'Followed RSS Feeds',
    action: action(
      'rssFeed',
      'following',
      'rss_feed',
      'follow',
      'extracted.userProfileCollections.usersRssFeeds.following_344b4271',
      'extracted.userProfileCollections.usersRssFeeds.follow_641d1ef6',
      'extracted.userProfileCollections.usersRssFeeds.followedRssFeed_81ccf410',
    ),
    relation: relation(
      'relation__user__follow__rss_feed',
      'rss_feed',
      'follow',
      'object',
      'rss_feeds',
    ),
  }),
  collection({
    id: 'rss-subscribed',
    group: 'rss',
    topLevelTab: 'rss',
    routeSegment: 'rss-feeds',
    routeListType: 'subscribed',
    access: 'owner',
    metricKey: 'rss_feeds_subscribed',
    tabValue: 'rss-subscribed',
    tabLabel: 'Subscribed to Feeds',
    action: action(
      'rssFeed',
      'subscribed',
      'rss_feed',
      'subscribe',
      'extracted.userProfileCollections.usersRssFeeds.subscribed_25c4797c',
      'extracted.userProfileCollections.usersRssFeeds.subscribe_cc0e38da',
      'extracted.userProfileCollections.usersRssFeeds.rssFeedSubscription_a01f62b2',
    ),
    relation: relation(
      'relation__user__subscribe__rss_feed',
      'rss_feed',
      'subscribe',
      'object',
      'rss_feeds',
    ),
  }),
  collection({
    id: 'rss-muted',
    group: 'rss',
    topLevelTab: 'rss',
    routeSegment: 'rss-feeds',
    routeListType: 'muted',
    access: 'owner',
    metricKey: 'rss_feeds_muted',
    tabValue: 'rss-muted',
    tabLabel: 'Muted Feeds',
    action: action(
      'rssFeed',
      'muted',
      'rss_feed',
      'mute',
      'extracted.userProfileCollections.usersRssFeeds.muted_2346f214',
      'extracted.userProfileCollections.usersRssFeeds.mute_8dd6857b',
      'extracted.userProfileCollections.usersRssFeeds.mutedRssFeed_88237bc5',
    ),
    relation: relation('relation__user__mute__rss_feed', 'rss_feed', 'mute', 'object', 'rss_feeds'),
  }),
  collection({
    id: 'rss-viewed',
    group: 'rss',
    topLevelTab: 'rss',
    routeSegment: 'rss-feeds',
    routeListType: 'viewed',
    access: 'owner',
    metricKey: 'rss_feeds_viewed',
    tabValue: 'rss-viewed',
    tabLabel: 'Viewed Feeds',
    recentView: { entityType: 'rss_feed' },
  }),
] as const
