import { action, collection, relation } from '../builders.mts'

export const RSS_ITEM_DOMAIN_COLLECTIONS = [
  collection({
    id: 'rss-items-saved',
    group: 'rss',
    topLevelTab: 'rss',
    routeSegment: 'rss-feed-items',
    routeListType: 'saved',
    access: 'owner',
    metricKey: 'rss_feed_items_saved',
    tabValue: 'rss-items-saved',
    tabLabel: 'Saved Items',
    action: action(
      'rssFeedItem',
      'saved',
      'rss_feed_item',
      'save',
      'extracted.userProfileCollections.rssItemsDomains.saved_b5c120b3',
      'extracted.userProfileCollections.rssItemsDomains.save_1509f561',
      'extracted.userProfileCollections.rssItemsDomains.savedRssItem_959d8faa',
    ),
    relation: relation(
      'relation__user__save__rss_feed_item',
      'rss_feed_item',
      'save',
      'object',
      'rss_feed_items',
    ),
  }),
  collection({
    id: 'rss-items-hidden',
    group: 'rss',
    topLevelTab: 'rss',
    routeSegment: 'rss-feed-items',
    routeListType: 'hidden',
    access: 'owner',
    metricKey: 'rss_feed_items_hidden',
    tabValue: 'rss-items-hidden',
    tabLabel: 'Hidden Items',
    action: action(
      'rssFeedItem',
      'hidden',
      'rss_feed_item',
      'hide',
      'extracted.userProfileCollections.rssItemsDomains.hidden_7e6fefff',
      'extracted.userProfileCollections.rssItemsDomains.hide_ac20a57b',
      'extracted.userProfileCollections.rssItemsDomains.hiddenRssItem_f56fbf72',
    ),
    relation: relation(
      'relation__user__hide__rss_feed_item',
      'rss_feed_item',
      'hide',
      'object',
      'rss_feed_items',
    ),
  }),
  collection({
    id: 'rss-items-viewed',
    group: 'rss',
    topLevelTab: 'rss',
    routeSegment: 'rss-feed-items',
    routeListType: 'viewed',
    access: 'owner',
    metricKey: 'rss_feed_items_viewed',
    tabValue: 'rss-items-viewed',
    tabLabel: 'Viewed Items',
    recentView: { entityType: 'rss_feed_item' },
  }),
  collection({
    id: 'links-saved',
    group: 'links',
    routeSegment: 'urls',
    routeListType: 'saved',
    access: 'owner',
    metricKey: 'urls_saved',
    tabLabel: 'Saved',
    action: action(
      'url',
      'saved',
      'url',
      'save',
      'extracted.userProfileCollections.rssItemsDomains.saved_b5c120b3',
      'extracted.userProfileCollections.rssItemsDomains.save_1509f561',
      'extracted.userProfileCollections.rssItemsDomains.savedUrl_dca3adb5',
    ),
    relation: relation('relation__user__save__url', 'url', 'save', 'object', 'urls', false),
  }),
  collection({
    id: 'domains-blocked',
    group: 'domains',
    routeSegment: 'domains',
    routeListType: 'blocked',
    access: 'owner',
    metricKey: 'domains_blocked',
    tabLabel: 'Blocked',
    action: action(
      'domain',
      'blocked',
      'url_hostname',
      'block',
      'extracted.userProfileCollections.rssItemsDomains.blocked_18f2a094',
      'extracted.userProfileCollections.rssItemsDomains.block_211d0bb8',
      'extracted.userProfileCollections.rssItemsDomains.blockedDomain_c63b6900',
    ),
    relation: relation(
      'relation__user__block__url_hostname',
      'url_hostname',
      'block',
      'object',
      'url_hostnames',
      false,
    ),
  }),
  collection({
    id: 'domains-muted',
    group: 'domains',
    routeSegment: 'domains',
    routeListType: 'muted',
    access: 'owner',
    metricKey: 'domains_muted',
    tabLabel: 'Muted',
    action: action(
      'domain',
      'muted',
      'url_hostname',
      'mute',
      'extracted.userProfileCollections.rssItemsDomains.muted_2346f214',
      'extracted.userProfileCollections.rssItemsDomains.mute_8dd6857b',
      'extracted.userProfileCollections.rssItemsDomains.mutedDomain_47ae08a6',
    ),
    relation: relation(
      'relation__user__mute__url_hostname',
      'url_hostname',
      'mute',
      'object',
      'url_hostnames',
      false,
    ),
  }),
] as const
