import { action, collection, relation } from '../builders.mts'

export const TOPIC_COLLECTIONS = [
  collection({
    id: 'topics-following',
    group: 'topics',
    routeSegment: 'topics',
    routeListType: 'following',
    access: 'public',
    visibilityField: 'topic_follows_visibility',
    metricGroup: 'count',
    metricKey: 'topics_following',
    tabLabel: 'Following',
    communityTab: true,
    communityTabLabel: 'Following Topics',
    relation: relation('relation__user__follow__topic', 'topic', 'follow', 'object', 'topics'),
  }),
  collection({
    id: 'topics-blocked',
    group: 'topics',
    routeSegment: 'topics',
    routeListType: 'blocked',
    access: 'owner',
    metricKey: 'topics_blocked',
    tabLabel: 'Blocked',
    action: action(
      'topic',
      'blocked',
      'topic',
      'block',
      'extracted.userProfileCollections.postsTopics.blocked_18f2a094',
      'extracted.userProfileCollections.postsTopics.block_211d0bb8',
      'extracted.userProfileCollections.postsTopics.blockedTopic_b36feec1',
    ),
    relation: relation('relation__user__block__topic', 'topic', 'block', 'object', 'topics'),
  }),
  collection({
    id: 'topics-muted',
    group: 'topics',
    routeSegment: 'topics',
    routeListType: 'muted',
    access: 'owner',
    metricKey: 'topics_muted',
    tabLabel: 'Muted',
    action: action(
      'topic',
      'muted',
      'topic',
      'mute',
      'extracted.userProfileCollections.postsTopics.muted_2346f214',
      'extracted.userProfileCollections.postsTopics.mute_8dd6857b',
      'extracted.userProfileCollections.postsTopics.mutedTopic_62b92773',
    ),
    relation: relation('relation__user__mute__topic', 'topic', 'mute', 'object', 'topics'),
  }),
  collection({
    id: 'topics-viewed',
    group: 'topics',
    routeSegment: 'topics',
    routeListType: 'viewed',
    access: 'owner',
    metricKey: 'topics_viewed',
    tabLabel: 'Viewed',
    recentView: { entityType: 'topic' },
  }),
  collection({
    id: 'topics-subscribed-posts',
    group: 'topics',
    routeSegment: 'topics',
    routeListType: 'subscribed-posts',
    serviceListType: 'subscribed_posts',
    access: 'owner',
    metricKey: 'topics_subscribed_posts',
    tabLabel: 'Subscribed to Posts',
    action: action(
      'topic',
      'subscribedPosts',
      'topic',
      'subscribe_posts',
      'extracted.userProfileCollections.postsTopics.subscribed_25c4797c',
      'extracted.userProfileCollections.postsTopics.subscribe_cc0e38da',
      'extracted.userProfileCollections.postsTopics.topicPostSubscription_2de9655f',
    ),
    relation: relation(
      'relation__user__subscribe_posts__topic',
      'topic',
      'subscribe_posts',
      'object',
      'topics',
    ),
  }),
  collection({
    id: 'topics-subscribed-news',
    group: 'topics',
    routeSegment: 'topics',
    routeListType: 'subscribed-news',
    serviceListType: 'subscribed_news',
    access: 'owner',
    metricKey: 'topics_subscribed_news',
    tabLabel: 'Subscribed to News',
    action: action(
      'topic',
      'subscribedNews',
      'topic',
      'subscribe_rss_feed_items',
      'extracted.userProfileCollections.postsTopics.subscribed_25c4797c',
      'extracted.userProfileCollections.postsTopics.subscribe_cc0e38da',
      'extracted.userProfileCollections.postsTopics.topicNewsSubscription_913cd611',
    ),
    relation: relation(
      'relation__user__subscribe_rss_feed_items__topic',
      'topic',
      'subscribe_rss_feed_items',
      'object',
      'topics',
    ),
  }),
  collection({
    id: 'topics-dismissed',
    group: 'topics',
    routeSegment: 'topics',
    routeListType: 'dismissed-recommendations',
    serviceListType: 'dismissed_recommendations',
    access: 'owner',
    metricKey: 'topics_dismissed_recommendations',
    tabLabel: 'Dismissed',
    action: action(
      'topic',
      'dismissed',
      'topic',
      'dismiss_recommendation',
      'extracted.userProfileCollections.postsTopics.dismissed_9d747277',
      'extracted.userProfileCollections.postsTopics.dismiss_48845bff',
      'extracted.userProfileCollections.postsTopics.dismissedTopic_37c648a8',
    ),
    relation: relation(
      'relation__user__dismiss_recommendation__topic',
      'topic',
      'dismiss_recommendation',
      'object',
      'topics',
    ),
  }),
] as const
