import { action, collection, relation } from '../builders.mts'

export const USER_COLLECTIONS = [
  collection({
    id: 'users-following',
    group: 'users',
    routeSegment: 'users',
    routeListType: 'following',
    access: 'public',
    visibilityField: 'follows_visibility',
    metricGroup: 'count',
    metricKey: 'users_following',
    tabLabel: 'Following',
    communityTab: true,
    communityTabLabel: 'Following Users',
    relation: relation('relation__user__follow__user', 'user', 'follow', 'object', 'users'),
  }),
  collection({
    id: 'users-followers',
    group: 'users',
    routeSegment: 'users',
    routeListType: 'followers',
    access: 'public',
    visibilityField: 'followers_visibility',
    metricGroup: 'count',
    metricKey: 'users_followers',
    tabLabel: 'Followers',
    communityTab: true,
    communityTabLabel: 'Followers',
    relation: relation('relation__user__follow__user', 'user', 'follow', 'subject', 'users'),
  }),
  collection({
    id: 'users-blocked',
    group: 'users',
    routeSegment: 'users',
    routeListType: 'blocked',
    access: 'owner',
    metricKey: 'users_blocked',
    tabLabel: 'Blocked',
    action: action(
      'user',
      'blocked',
      'user',
      'block',
      'extracted.userProfileCollections.usersRssFeeds.blocked_18f2a094',
      'extracted.userProfileCollections.usersRssFeeds.block_211d0bb8',
      'extracted.userProfileCollections.usersRssFeeds.blockedUser_1da4e9d6',
    ),
    relation: relation('relation__user__block__user', 'user', 'block', 'object', 'users'),
  }),
  collection({
    id: 'users-muted',
    group: 'users',
    routeSegment: 'users',
    routeListType: 'muted',
    access: 'owner',
    metricKey: 'users_muted',
    tabLabel: 'Muted',
    action: action(
      'user',
      'muted',
      'user',
      'mute',
      'extracted.userProfileCollections.usersRssFeeds.muted_2346f214',
      'extracted.userProfileCollections.usersRssFeeds.mute_8dd6857b',
      'extracted.userProfileCollections.usersRssFeeds.mutedUser_a41ce167',
    ),
    relation: relation('relation__user__mute__user', 'user', 'mute', 'object', 'users'),
  }),
  collection({
    id: 'users-subscribed-posts',
    group: 'users',
    routeSegment: 'users',
    routeListType: 'subscribed-posts',
    serviceListType: 'subscribed_posts',
    access: 'owner',
    metricKey: 'users_subscribed_posts',
    tabLabel: 'Subscribed to Posts',
    action: action(
      'user',
      'subscribedPosts',
      'user',
      'subscribe',
      'extracted.userProfileCollections.usersRssFeeds.subscribed_25c4797c',
      'extracted.userProfileCollections.usersRssFeeds.subscribe_cc0e38da',
      'extracted.userProfileCollections.usersRssFeeds.userPostSubscription_459d751a',
    ),
    relation: relation('relation__user__subscribe__user', 'user', 'subscribe', 'object', 'users'),
  }),
  collection({
    id: 'users-dismissed',
    group: 'users',
    routeSegment: 'users',
    routeListType: 'dismissed-recommendations',
    serviceListType: 'dismissed_recommendations',
    access: 'owner',
    metricKey: 'users_dismissed_recommendations',
    tabLabel: 'Dismissed',
    action: action(
      'user',
      'dismissed',
      'user',
      'dismiss_recommendation',
      'extracted.userProfileCollections.usersRssFeeds.dismissed_9d747277',
      'extracted.userProfileCollections.usersRssFeeds.dismiss_48845bff',
      'extracted.userProfileCollections.usersRssFeeds.dismissedUser_89bd0201',
    ),
    relation: relation(
      'relation__user__dismiss_recommendation__user',
      'user',
      'dismiss_recommendation',
      'object',
      'users',
    ),
  }),
] as const
