import {
  renderSchemaMarkdown as renderFromPostgres,
  type SchemaMarkdownFiles,
  type SchemaSnapshot,
} from '@vouchington/postgres/pg-schema-snapshot'

export type { SchemaMarkdownFiles }

export function renderSchemaMarkdown(snapshot: SchemaSnapshot): SchemaMarkdownFiles {
  return new Map(
    [...renderFromPostgres(snapshot)].map(([path, content]) => [
      path,
      content
        .replaceAll(
          'Generated schema snapshot. Do not hand-edit. [Schema index](../README.md).',
          'Generated by `pnpm run db:snapshot:update`. Do not hand-edit. [Schema index](../README.md).',
        )
        .replaceAll(
          'Generated schema snapshot. Do not hand-edit. Full function bodies live only in the companion [`schema.json`](../schema.json).',
          'Generated by `pnpm run db:snapshot:update`. Do not hand-edit — see [schema-snapshot/README.md](../README.md) for the update flow. Full function bodies live only in the companion [`schema.json`](../schema.json).',
        ),
    ]),
  )
}
