// Authentication & Authorization
export const AUTH_REQUIRED = 'AUTH_REQUIRED'
export const FORBIDDEN = 'FORBIDDEN'
export const ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED'
export const COMMUNITY_BANNED = 'COMMUNITY_BANNED'
export const IDENTITY_REQUIRED = 'IDENTITY_REQUIRED'
export const OFFICIAL_ACCOUNT_TRUST_SIGNAL_FORBIDDEN = 'OFFICIAL_ACCOUNT_TRUST_SIGNAL_FORBIDDEN'
export const NEUTRAL_REQUIRES_EXISTING_BALLOT = 'NEUTRAL_REQUIRES_EXISTING_BALLOT'
export const BYPASS_DISABLED = 'BYPASS_DISABLED'
export const ATTESTATION_REJECTED = 'ATTESTATION_REJECTED'
export const ATTESTATION_SIGNATURE_REQUIRED = 'ATTESTATION_SIGNATURE_REQUIRED'
export const ATTESTATION_TIMESTAMP_INVALID = 'ATTESTATION_TIMESTAMP_INVALID'
export const ATTESTATION_NONCE_REPLAYED = 'ATTESTATION_NONCE_REPLAYED'

// Multi-factor authentication
export const MFA_REQUIRED = 'MFA_REQUIRED'
export const MFA_REAUTH_REQUIRED = 'MFA_REAUTH_REQUIRED'

// Validation
export const INVALID_INPUT = 'INVALID_INPUT'
export const INVALID_CONTENT_TYPE = 'INVALID_CONTENT_TYPE'
export const SYNC_EXPORT_TOO_LARGE = 'SYNC_EXPORT_TOO_LARGE'
export const SUPPORT_THREAD_INBOUND_MESSAGE_REQUIRED = 'SUPPORT_THREAD_INBOUND_MESSAGE_REQUIRED'

// Resources
export const NOT_FOUND = 'NOT_FOUND'
export const CONFLICT = 'CONFLICT'
export const FEED_NOT_DISCOVERABLE = 'FEED_NOT_DISCOVERABLE'
export const DUPLICATE_TOPIC = 'DUPLICATE_TOPIC'
export const DUPLICATE_RECOMMENDATION = 'DUPLICATE_RECOMMENDATION'

// Contribution gating
export const CONTRIBUTION_GATED = 'CONTRIBUTION_GATED'
export const EMAIL_VERIFICATION_REQUIRED = 'EMAIL_VERIFICATION_REQUIRED'
export const CONTRIBUTION_QUOTA_EXCEEDED = 'CONTRIBUTION_QUOTA_EXCEEDED'
export const IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED'
export const CONTRIBUTION_ADMISSION_IN_PROGRESS = 'CONTRIBUTION_ADMISSION_IN_PROGRESS'
export const MEMBERSHIP_REQUIRED = 'MEMBERSHIP_REQUIRED'

// Agent responses
export const AGENT_RESPONSE_QUOTA_EXCEEDED = 'AGENT_RESPONSE_QUOTA_EXCEEDED'
export const AGENT_RESPONSE_MAX_CONCURRENT = 'AGENT_RESPONSE_MAX_CONCURRENT'
export const AGENT_RESPONSE_DISABLED = 'AGENT_RESPONSE_DISABLED'

// Tag limits
export const TAG_LIMIT_REACHED = 'TAG_LIMIT_REACHED'

// Content edit windows
export const POST_CONTENT_EDIT_WINDOW_EXPIRED = 'POST_CONTENT_EDIT_WINDOW_EXPIRED'

// Thread locking
export const POST_THREAD_LOCKED = 'POST_THREAD_LOCKED'

// Rate limiting
export const RATE_LIMIT = 'RATE_LIMIT'

// User creation
export const USER_CREATION_RACE = 'USER_CREATION_RACE'

// Server errors
export const INTERNAL_ERROR = 'INTERNAL_ERROR'
export const BAD_GATEWAY = 'BAD_GATEWAY'
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'

// Entity relations wiring invariants
export const ENTITY_RELATION_ELECTION_HANDLER_UNREGISTERED =
  'ENTITY_RELATION_ELECTION_HANDLER_UNREGISTERED'
export const ENTITY_RELATION_BOOKMARK_BLOOM_HANDLER_UNREGISTERED =
  'ENTITY_RELATION_BOOKMARK_BLOOM_HANDLER_UNREGISTERED'
export const ENTITY_RELATION_POST_RELATED_URLS_GUARD_UNREGISTERED =
  'ENTITY_RELATION_POST_RELATED_URLS_GUARD_UNREGISTERED'
export const ENTITY_RELATION_BLOCKED_HOSTNAME_GUARD_UNREGISTERED =
  'ENTITY_RELATION_BLOCKED_HOSTNAME_GUARD_UNREGISTERED'
export const ENTITY_RELATION_REFERRAL_LINK_GUARD_UNREGISTERED =
  'ENTITY_RELATION_REFERRAL_LINK_GUARD_UNREGISTERED'

// Topic recommendations wiring invariants
export const TOPIC_RECOMMENDATIONS_APPROVED_HANDLER_UNREGISTERED =
  'TOPIC_RECOMMENDATIONS_APPROVED_HANDLER_UNREGISTERED'

// Topics wiring invariants
export const TOPICS_IMAGE_EXISTS_GUARD_UNREGISTERED = 'TOPICS_IMAGE_EXISTS_GUARD_UNREGISTERED'
