export type EntityRelationEntityType =
  | 'user'
  | 'post'
  | 'topic'
  | 'topic_alias'
  | 'rss_feed'
  | 'rss_feed_item'
  | 'url'
  | 'url_hostname'
  | 'image'
  | 'card'
  | 'rewards_program'
  | 'rewards_program_status'
  | 'referral_program'
  | 'review'
  | 'discussion'
  | 'community'
  | 'remote_actor'
