export const DYNAMIC_CONFIG_AUDIT_FIELDS_CORE = {
  'feature-flags': {
    memberships: 'boolean',
    membershipStripeBilling: 'boolean',
    membershipAppleBilling: 'boolean',
    membershipGoogleBilling: 'boolean',
    membershipMicrosoftBilling: 'boolean',
    chat: 'boolean',
    combinedSearch: 'boolean',
    support: 'boolean',
    fediverse: 'boolean',
  },
  'membership-billing': {
    stripe_enabled: 'boolean',
    stripe_automatic_collision_resolution_enabled: 'boolean',
    apple_app_store_enabled: 'boolean',
    apple_app_store_automatic_collision_resolution_enabled: 'boolean',
    google_play_enabled: 'boolean',
    google_play_automatic_collision_resolution_enabled: 'boolean',
    microsoft_store_enabled: 'boolean',
    microsoft_store_automatic_collision_resolution_enabled: 'boolean',
  },
  'request-client-info': {
    enforcement_enabled: 'boolean',
  },
  'vote-weight-config': {
    multiplier_mfa: 'number',
    multiplier_has_oauth: 'number',
    multiplier_2_plus_oauth: 'number',
    multiplier_oauth_1_year: 'number',
    multiplier_oauth_5_years: 'number',
    multiplier_account_30_days: 'number',
    multiplier_account_1_year: 'number',
    multiplier_account_2_years: 'number',
    multiplier_account_5_years: 'number',
    weight_new_account: 'number',
    threshold_7_days_ms: 'number',
    threshold_30_days_ms: 'number',
    threshold_1_year_ms: 'number',
    threshold_2_years_ms: 'number',
    threshold_5_years_ms: 'number',
    multiplier_plus: 'number',
    multiplier_pro: 'number',
    multiplier_admin: 'number',
  },
  'recaptcha-config': {
    enabled: 'boolean',
    blocking_enabled: 'boolean',
    block_threshold: 'number',
  },
  'turnstile-config': {
    always_approve: 'boolean',
  },
  'post-content-limits-config': {
    data_point_topic_ids_max_items: 'number',
    review_topic_ratings_max_items: 'number',
  },
  'post-related-url-display-config': {
    summary_limit: 'number',
  },
  'rate-limit-thresholds': {
    read_tier0: 'number',
    read_tier1: 'number',
    read_tier2: 'number',
    read_tier3: 'number',
    read_tier4: 'number',
    read_tier5: 'number',
    write_tier0: 'number',
    write_tier1: 'number',
    write_tier2: 'number',
    write_tier3: 'number',
    write_tier4: 'number',
    write_tier5: 'number',
    sensitive_tier0: 'number',
    sensitive_tier1: 'number',
    sensitive_tier2: 'number',
    sensitive_tier3: 'number',
    sensitive_tier4: 'number',
    sensitive_tier5: 'number',
    read_ttl: 'number',
    write_ttl: 'number',
    sensitive_ttl: 'number',
  },
  'route-rate-limit-config': {
    enabled: 'boolean',
    anon_read: 'number',
    anon_write: 'number',
    anon_sensitive: 'number',
    anon_oauth_callback: 'number',
    anon_read_ttl: 'number',
    anon_write_ttl: 'number',
    anon_sensitive_ttl: 'number',
    anon_oauth_callback_ttl: 'number',
    attested_multiplier: 'number',
    activitypub_inbox_attempt_max_requests: 'number',
    activitypub_inbox_attempt_window_seconds: 'number',
    activitypub_inbox_max_requests: 'number',
    activitypub_inbox_window_seconds: 'number',
  },
} as const
