export const DYNAMIC_CONFIG_AUDIT_FIELDS_REST = {
  'bloom-filter-config': {
    entityCacheBloomFilterEnabled: 'boolean',
    embeddingBloomFilterEnabled: 'boolean',
    urlBlocklistBloomFilterEnabled: 'boolean',
    emailBlocklistBloomFilterEnabled: 'boolean',
    bookmarkBloomFilterEnabled: 'boolean',
    apiKeyBloomFilterEnabled: 'boolean',
  },
  'rss-feed-discoverability-config': {
    enabled: 'boolean',
    make_discoverable_min_net_score: 'number',
    make_discoverable_alt_min_net_score: 'number',
    make_discoverable_min_subscriptions: 'number',
    make_undiscoverable_max_net_score: 'number',
  },
  'moderation-config': {
    ai_generated_confidence_threshold: 'number',
  },
  'bedrock-embeddings-batch-config': {
    max_inflight_jobs: 'number',
    max_requests_per_hour: 'number',
    max_requests_per_file: 'number',
    max_file_size_gb: 'number',
    max_job_size_gb: 'number',
    min_records_per_job: 'number',
    backlog_threshold: 'number',
    stale_ttl_hours: 'number',
  },
  'rss-feed-crawl-config': {
    enabled: 'boolean',
    ignore_robots_txt: 'boolean',
    tier1_sla_ms: 'number',
    tier2_sla_ms: 'number',
    tier3_sla_ms: 'number',
    tier4_sla_ms: 'number',
    tier5_sla_ms: 'number',
    capacity_budget: 'number',
  },
  'user-import-export-config': {
    sync_export_max_items: 'number',
  },
  'web-risk-config': {
    enabled: 'boolean',
  },
  'moderation-ai-config': {
    community_judgement_enabled: 'boolean',
  },
  'moderation-ai-dispatch-config': {
    auto_dispatch_enabled: 'boolean',
    auto_dispatch_remove: 'boolean',
    auto_dispatch_warn: 'boolean',
    auto_dispatch_no_action: 'boolean',
  },
  'openai-spend-cap': {
    enabled: 'boolean',
    daily_cap_microunits: 'number',
  },
  'manual-tag-limits': {
    just_joined: 'number',
    free: 'number',
    plus: 'number',
    pro: 'number',
  },
  'autotagger-paid-limits': {
    enabled: 'boolean',
    post_free_max_topics: 'number',
    post_plus_max_topics: 'number',
    post_pro_max_topics: 'number',
    rss_discoverable_llm_max_topics: 'number',
    rss_collaborative_plus_max_topics: 'number',
    rss_collaborative_pro_max_topics: 'number',
  },
  'kagi-smallweb-config': {
    enabled: 'boolean',
  },
  'app-attestation-config': {
    enabled: 'boolean',
    require_attestation_for_bypass: 'boolean',
    allow_development_attestation: 'boolean',
    request_signing_mode: 'string',
  },
  'activitypub-inbox': {
    async_delivery_enabled: 'boolean',
  },
  'oauth-authorization-broker': {
    facebook_web_enabled: 'boolean',
    facebook_native_enabled: 'boolean',
    x_web_enabled: 'boolean',
    x_native_enabled: 'boolean',
    github_web_enabled: 'boolean',
    github_native_enabled: 'boolean',
  },
  'api-egress-proxy': {
    stripe_enabled: 'boolean',
    openai_moderation_enabled: 'boolean',
    apple_oauth_enabled: 'boolean',
    github_oauth_enabled: 'boolean',
    x_oauth_enabled: 'boolean',
    bluesky_oauth_enabled: 'boolean',
    fediverse_search_enabled: 'boolean',
    bedrock_embeddings_enabled: 'boolean',
  },
} as const
