export const QUEUE_NAME = 'memberships'
export const PRIORITY_DEFAULT = 10
export const PRIORITY_DISPATCHER = 100
export const MEMBERSHIP_ENTITLEMENT_EFFECTS_INTERVAL_MS = 60_000
export const MEMBERSHIP_GRANT_EXPIRY_INTERVAL_MS = 60_000
export const STRIPE_CATALOG_RECONCILIATION_INTERVAL_MS = 300_000
export const APPLE_NOTIFICATION_RECOVERY_INTERVAL_MS = 300_000
