import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type * as Undici from 'undici'
import { v7 } from 'uuid'
import {
  ATTESTED_SESSION_EXPIRATION_SECONDS,
  EDGE_ANON_SESSION_JWT_ISSUER,
  SESSION_EXPIRATION_SECONDS,
  signDeviceJwt,
  signSessionJwt,
} from '@ts-shared/session-jwt'

const mockFetch = vi.fn<typeof Undici.fetch>()

vi.resetModules()
vi.doMock<typeof import('undici')>(import('undici'), async () => {
  const actual = await vi.importActual<typeof import('undici')>('undici')
  return { ...actual, fetch: mockFetch }
})

const { createRandomString } = await import('@voucha/test-helpers')
const { createRequest } = await import('@voucha/test-helpers/api/server')
const { Response: UndiciResponse } = await import('undici')

function maxAgeOf(cookieHeader: string[] | undefined, name: string): number | undefined {
  const cookie = cookieHeader?.find(c => c.startsWith(`${name}=`))
  const match = cookie?.match(/Max-Age=(\d+)/)
  return match ? Number(match[1]) : undefined
}

describe('POST /api/v1/auth/oauth/github/continue success', () => {
  beforeEach(() => {
    mockFetch.mockReset()
  })

  afterEach(() => {
    vi.restoreAllMocks()
  })

  it('creates a new user, mints session/device tokens, and sets auth cookies', async () => {
    const githubUserId = String(Math.floor(Math.random() * 1_000_000) + 100_000)
    const login = `test-${createRandomString(8)}`
    const email = `tests+${login}@voucha.ai`

    mockFetch
      .mockResolvedValueOnce(
        new UndiciResponse(
          JSON.stringify({
            access_token: 'ghu_test_token',
            token_type: 'bearer',
            scope: 'read:user,user:email',
          }),
        ),
      )
      .mockResolvedValueOnce(
        new UndiciResponse(
          JSON.stringify({
            id: Number(githubUserId),
            login,
            name: 'Test User',
            avatar_url: 'https://avatars.githubusercontent.com/u/1',
            email,
          }),
        ),
      )
      .mockResolvedValueOnce(
        new UndiciResponse(JSON.stringify([{ email, primary: true, verified: true }])),
      )

    // Without a trusted x-cf-worker-secret (only injected by the Cloudflare Worker
    // in production, or generated by Playwright workflows in CI — never set for
    // the plain backend-tests job), getExpectedOrigin() ignores x-forwarded-*
    // headers and falls back to `http://` + the raw Host header. Match that
    // fallback instead of depending on an env var this job never sets.
    const request = createRequest()
    const response = await request
      .post('/api/v1/auth/oauth/github/continue')
      .set('Host', 'example.com')
      .send({ code: 'fake-code', redirectUri: 'http://example.com/auth/callback/github' })
      .expect(res => {
        expect(res.status).toBeGreaterThanOrEqual(200)
        expect(res.status).toBeLessThan(300)
      })

    // A brand-new OAuth signup only inserts a bare `users` row and connects the
    // provider account — username/email_address are set later during onboarding,
    // not carried over from the provider profile. See createUser() in
    // backend/services/users/create-helpers.mts.
    expect(response.body.user).toEqual({
      id: expect.any(String),
      username: null,
      email_address: null,
      roles: [],
      profile_image_id: null,
    })

    const cookieHeader = response.headers['set-cookie'] as unknown as string[] | undefined
    expect(cookieHeader?.some(cookie => cookie.startsWith('dt='))).toBe(true)
    expect(cookieHeader?.some(cookie => cookie.startsWith('st='))).toBe(true)
  })

  it('preserves an edge-anon-issued attested device by minting a 30-day (not 2-day) st cookie', async () => {
    // Regression: deviceClass must come from getSessionTokenData() (which verifies
    // edge-anon-issued dt/st pairs), not getDeviceTokenData() (which only verifies
    // backend-issued dt tokens and silently drops dc for edge-anon devices).
    const githubUserId = String(Math.floor(Math.random() * 1_000_000) + 100_000)
    const login = `test-${createRandomString(8)}`
    const email = `tests+${login}@voucha.ai`

    mockFetch
      .mockResolvedValueOnce(
        new UndiciResponse(
          JSON.stringify({
            access_token: 'ghu_test_token',
            token_type: 'bearer',
            scope: 'read:user,user:email',
          }),
        ),
      )
      .mockResolvedValueOnce(
        new UndiciResponse(
          JSON.stringify({
            id: Number(githubUserId),
            login,
            name: 'Test User',
            avatar_url: 'https://avatars.githubusercontent.com/u/1',
            email,
          }),
        ),
      )
      .mockResolvedValueOnce(
        new UndiciResponse(JSON.stringify([{ email, primary: true, verified: true }])),
      )

    const did = v7()
    const deviceToken = await signDeviceJwt(
      { did, dc: 'attested' },
      { issuer: EDGE_ANON_SESSION_JWT_ISSUER, expiresIn: '30 days' },
    )
    const sessionToken = await signSessionJwt(
      { did, sid: v7(), uid: null },
      { issuer: EDGE_ANON_SESSION_JWT_ISSUER, expiresIn: '2 days' },
    )

    const request = createRequest()
    const response = await request
      .post('/api/v1/auth/oauth/github/continue')
      .set('Host', 'example.com')
      .set('Cookie', `dt=${deviceToken}; st=${sessionToken}`)
      .send({ code: 'fake-code', redirectUri: 'http://example.com/auth/callback/github' })
      .expect(res => {
        expect(res.status).toBeGreaterThanOrEqual(200)
        expect(res.status).toBeLessThan(300)
      })

    const cookieHeader = response.headers['set-cookie'] as unknown as string[] | undefined
    expect(maxAgeOf(cookieHeader, 'st')).toBe(ATTESTED_SESSION_EXPIRATION_SECONDS)
    expect(maxAgeOf(cookieHeader, 'st')).not.toBe(SESSION_EXPIRATION_SECONDS)
  })
})
