HTTP/1.1 403 Forbidden
content-type: application/json
x-amzn-requestid: 9a3c5e7b-1d2f-4b6a-8c0e-7f5d3b1a9e48
x-amzn-errortype: AccessDeniedException:http://internal.amazon.com/coral/com.amazon.bedrock/

{"message":"You don't have access to the model with the specified model ID."}
