// Ratchet: this set can only shrink after the registered-route completeness rollout. That rollout
// intentionally added SSE operations (event sequences are not extracted) and exposed secondary
// variants that the old walker silently dropped. Future additions indicate a new extraction gap
// and must be fixed at the source rather than silently absorbed.
export const EXPECTED_UNAVAILABLE_ROUTES: readonly string[] = [
  'DELETE:/api/v1/admin/mcp',
  'DELETE:/api/v1/mcp',
  'DELETE:/api/v1/topics/:idOrSlug',
  'GET:/api/v1/admin/article-syncs/:jobId/stream',
  'GET:/api/v1/admin/mcp',
  'GET:/api/v1/admin/postgresql/stream',
  'GET:/api/v1/admin/valkey/stream',
  'GET:/api/v1/article-syncs/:jobId',
  'GET:/api/v1/hostnames/social',
  'GET:/api/v1/hostnames/top',
  'GET:/api/v1/hostnames',
  'GET:/api/v1/images/:id/state/stream',
  'GET:/api/v1/imports/:batchId/stream',
  'GET:/api/v1/me/individual',
  'GET:/api/v1/memberships/plans',
  'GET:/api/v1/mcp',
  'GET:/api/v1/my/notifications',
  'GET:/api/v1/my/notifications/unread',
  'GET:/api/v1/my/rewards-program-statuses',
  'GET:/api/v1/mq/stream',
  'GET:/api/v1/reports',
  'GET:/api/v1/rss-feeds',
  'GET:/api/v1/search',
  'GET:/api/v1/topics/:idOrSlug/retailer',
  'GET:/api/v1/topics/aliases',
  'GET:/api/v1/topics/publisher-types',
  'GET:/api/v1/users/:id/vouch-context',
  'GET:/api/v1/users/:idOrSlug/data-request/stream',
  'GET:/api/v1/users/:username/landing-page',
  'GET:/api/v1/users/:username/landing-pages/:slug',
  'GET:/api/v1/web-search',
  'PATCH:/api/v1/my/rewards-program-statuses/:id',
  'PATCH:/api/v1/my/spending-categories/:id',
  'PATCH:/api/v1/posts/:idOrSlug',
  'PATCH:/api/v1/topic-recommendations/:id',
  'PATCH:/api/v1/topics/:idOrSlug/retailer',
  'POST:/api/v1/admin/mcp',
  'POST:/api/v1/communities/:idOrSlug/posts',
  'POST:/api/v1/conversations/:conversationId/chat',
  'POST:/api/v1/households/:id/memberships',
  'POST:/api/v1/images/:id/completions',
  'POST:/api/v1/images/upload-url',
  'POST:/api/v1/mcp',
  'POST:/api/v1/my/rewards-program-statuses',
  'POST:/api/v1/my/spending-categories',
  'POST:/api/v1/topic-recommendations',
  'POST:/api/v1/topic-recommendations/:id/approvals',
  'POST:/api/v1/topic-recommendations/:id/rejections',
  'POST:/api/v1/topics/:idOrSlug/aliases',
]

// Ratchet: this set can only shrink, mirroring EXPECTED_UNAVAILABLE_ROUTES above but for request
// bodies. Empty today — every JSON-reading mutation route's request body extracts cleanly.
export const EXPECTED_UNAVAILABLE_REQUEST_ROUTES: readonly string[] = []
