export const USER_DELETIONS_QUEUE_NAME = 'user-deletions'
export const USER_DELETIONS_LOCK_DURATION_MS = 600_000
export const USER_DELETIONS_PRIORITY_DEFAULT = 10
export const USER_DELETIONS_RECOVERY_INTERVAL_MS = 300_000
