// Canonical closed values used by the fresh-bootstrap enum generator.
export const COPYRIGHT_FINITE_VALUES = {
  copyright_trusted_flagger_expertise_areas: ['intellectual_property', 'other'],
  copyright_territorial_decision_outcomes: ['restrict', 'no_action'],
  copyright_territorial_party_roles: ['notifier', 'poster', 'reviewer'],
  copyright_eu_dispute_settlement_results: [
    'decided_for_recipient',
    'decided_for_platform',
    'withdrawn',
    'no_decision',
  ],
  copyright_restriction_human_review_actions: ['confirm', 'modify', 'reverse'],
  copyright_automatic_withholding_refusal_reasons: [
    'thresholds_unset',
    'switch_on_unrecorded',
    'received_before_switch_on',
    'claimant_unavailable',
    'claimant_suspended',
    'trust_below_minimum',
    'account_too_new',
    'claimant_daily_cap',
    'poster_daily_cap',
    'non_post_target',
  ],
  copyright_claimant_misuse_event_outcomes: [
    'notice_withdrawn',
    'notice_rejected',
    'restriction_reversed_by_counter_notice',
    'restriction_reversed_by_appeal',
  ],
  copyright_jurisdictions: ['us_dmca', 'eu_dsa', 'uk', 'other'],
  copyright_notice_action_intent_actions: ['withhold', 'restore'],
  copyright_notice_action_intent_states: [
    'pending',
    'claimed',
    'completed',
    'stale',
    'blocked',
    'failed',
  ],
  copyright_notice_appeal_recommendation_outcomes: ['confirm', 'modify', 'reverse', 'uncertain'],
  copyright_review_actions: ['confirm', 'reverse'],
  copyright_notice_correspondence_message_composition_kinds: [
    'inbound',
    'deterministic_template',
    'staff',
    'agent',
  ],
  copyright_notice_correspondence_kinds: [
    'receipt',
    'request_information',
    'restriction_notice',
    'decision_notice',
    'counter_notice_forwarding',
    'restoration_notice',
    'status_update',
    'inbound_message',
  ],
  copyright_notice_correspondence_message_directions: ['inbound', 'outbound'],
  copyright_notice_delivery_intent_channels: ['in_app', 'email'],
  copyright_notice_delivery_kinds: [
    'owner_information_notice',
    'redress_decision_notice',
    'claimant_receipt',
    'status_update',
    'poster_restriction_notice',
    'poster_review_notice',
    'poster_restoration_notice',
    'claimant_decision_notice',
    'counter_notice_forwarding',
    'staff_information_request',
    'email_intake_rejected',
    'email_intake_needs_information',
    'email_intake_received',
  ],
  copyright_notice_delivery_intent_recipient_roles: [
    'claimant',
    'poster',
    'informed_owner',
    'correspondent',
  ],
  copyright_notice_delivery_intent_states: ['pending', 'claimed', 'sent', 'failed', 'bounced'],
  copyright_notice_email_correspondence_review_actions: ['pending', 'admitted', 'rejected'],
  copyright_notice_email_correspondence_review_kinds: [
    'complaint',
    'supplement',
    'appeal',
    'counter_notice',
    'withdrawal',
    'court_or_ccb_hold',
  ],
  copyright_notice_email_intake_link_kinds: ['initial', 'thread'],
  copyright_notice_email_intake_parse_statuses: ['succeeded', 'failed'],
  copyright_notice_email_intake_review_decisions: ['approved', 'rejected', 'legal_process'],
  copyright_notice_email_thread_reference_kinds: ['message_id', 'reply_reference'],
  copyright_notice_form_screening_recommendations: ['not_obviously_invalid', 'invalid_or_spam'],
  copyright_notice_legal_hold_assessment_ccb_claim_kinds: ['claim', 'counterclaim'],
  copyright_notice_legal_hold_assessment_proceeding_kinds: ['federal_court', 'ccb'],
  copyright_notice_legal_hold_resolution_kinds: ['dismissed', 'proceeding_ended', 'superseded'],
  copyright_notice_lifecycle_change_recovery_sources: ['durable_review', 'durable_decision'],
  copyright_notice_lifecycle_change_replay_reasons: ['operator_replay'],
  copyright_notice_submission_kinds: [
    'complaint',
    'notice',
    'supplement',
    'appeal',
    'counter_notice',
    'withdrawal',
    'court_or_ccb_hold',
  ],
  copyright_notice_submission_source_kinds: ['signed_in_form', 'guest_form', 'email', 'staff'],
  copyright_notice_legal_bases: ['copyright'],
  copyright_repeat_infringer_disposition_kinds: ['withdrawn', 'duplicate', 'abusive'],
  copyright_repeat_infringer_review_outcomes: [
    'warning',
    'no_action',
    'restrict',
    'terminate',
    'reinstatement',
  ],
  copyright_staydown_match_kinds: ['exact', 'perceptual'],
  copyright_territorial_decision_automation_disclosures: ['human'],
  copyright_territorial_notice_routing_destinations: ['staff_queue'],
  copyright_territorial_redress_decision_staff_dispositions: ['maintain', 'revoke'],
} as const
