import { MODERATOR_ACTION_TYPES } from '@ts-shared/utils/moderation-catalogs'

// Canonical contribution, moderation and protocol domains.
export const DOMAIN_FINITE_VALUES = {
  post_admission_routes: [
    'internal',
    'authored.create',
    'posts.create',
    'communities.posts.create',
    'rss-feed-items.discussions.create',
    'stories.discussions.create',
    'topic-recommendations.create',
    'my.import.topics.recommendation',
  ],
  post_admission_scope_categories: [
    'internal',
    'global',
    'community',
    'rss_item',
    'story',
    'topic_recommendation',
    'my.import.topics',
  ],
  contribution_policy_sources: [
    'discussion',
    'review',
    'comment',
    'data_point',
    'link',
    'story',
    'rss_item_discussion',
    'topic_recommendation',
    'article',
    'blog_post',
  ],
  post_admission_committed_statuses: ['created'],
  moderation_transparency_categories: [
    ...new Set([
      ...MODERATOR_ACTION_TYPES,
      ...([
        'accept',
        'deny',
        'reduce',
        'agent_moderation',
        'community_ai',
        'openai_omni',
        'spam_detection',
        'post_clearance_reject',
        'remove',
        'approve',
        'reject',
        'ban',
        'lift_ban',
        'activate_restriction',
        'lift_restriction',
        'warn',
        'lock',
        'unlock',
        'pin',
        'unpin',
        'suspend',
        'unsuspend',
        'remove_member',
        'change_role',
        'resolve_report',
        'dismiss_report',
        'resolve_appeal',
        'dismiss_appeal',
        'spam',
        'harassment',
        'misinformation',
        'illegal_content',
        'other',
        'vote_manipulation',
      ] as const),
    ]),
  ].toSorted(),
  moderation_training_human_actions: [
    'reinstate',
    'keep_removed',
    'label_only',
    'dismiss',
    'resolve_accept',
    'resolve_reduce',
    'resolve_remove',
    'resolve_annotate',
    'report_reviewed',
    'report_dismissed',
    'report_actioned',
    'clearance_approved',
    'clearance_rejected',
    'clearance_pending',
    'clearance_in_review',
    'approve_publication',
    'reject_publication',
    'unpublish_post',
    'accuracy_upvote',
    'accuracy_downvote',
    'accuracy_unvote',
    'save_prompt_test_run',
  ],
  post_publication_source_cursor_kinds: [
    'review',
    'data',
    'relation',
    'alias_source',
    'alias_relation',
    'static',
    'slug',
    'feed',
  ],
  post_publication_receipt_cursor_kinds: ['typed'],
  url_hostname_block_sources: ['admin', 'google_web_risk', 'parent_hostname'],
  http_request_methods: [
    'GET',
    'HEAD',
    'POST',
    'PUT',
    'DELETE',
    'CONNECT',
    'OPTIONS',
    'TRACE',
    'PATCH',
  ],
  membership_google_play_acknowledgement_skip_reasons: ['no_longer_eligible'],
  notification_target_intents: ['notifications_inbox'],
  oauth_authorization_result_kinds: ['authenticated', 'mfa_required', 'connected'],
  post_publication_reasons: [
    'post_created',
    'post_updated',
    'post_content_reset',
    'post_audience_changed',
    'post_archived',
    'post_deleted',
    'post_topics_changed',
    'post_related_urls_changed',
    'post_ratings_changed',
    'post_clearance_changed',
    'post_moderation_flag_changed',
    'community_publication_changed',
    'moderation_appeal_resolved',
    'author_suspension_changed',
    'author_deleted',
    'community_visibility_changed',
    'rss_feed_discoverability_changed',
    'rss_feed_enablement_changed',
    'rss_feed_source_changed',
  ],
} as const
