// Canonical closed values used by the fresh-bootstrap enum generator.
export const GENERAL_FINITE_VALUES = {
  ai_usage_record_pricing_statuses: ['priced', 'unpriced'],
  oauth_callback_modes: ['web', 'native'],
  bluesky_link_authorization_statuses: [
    'pending',
    'callback_claimed',
    'handoff_ready',
    'attached',
    'revoked',
    'expired',
    'rejected',
  ],
  classifier_run_terminal_failure_kinds: [
    'provider-error',
    'invalid-result',
    'context-rejected',
    'attempts-exhausted',
    'client-unavailable',
    'sweep-bound-exceeded',
  ],
  community_post_review_platform_override_actions: ['approve', 'reject', 'unpublish', 'restore'],
  classifier_scope_categories: ['global', 'community_ai'],
  email_security_verdicts: ['pass', 'fail', 'gray', 'processing_failed', 'unknown'],
  image_binding_families: ['post', 'surface'],
  image_surface_placement_surface_kinds: [
    'user-profile-image',
    'topic-logo-image',
    'topic-hero-image',
    'community-profile-image',
    'community-banner-image',
    'user-profile-link-image',
  ],
  mcp_call_audit_event_outcomes: [
    'accepted',
    'tool_error',
    'invalid_request',
    'invalid_arguments',
    'not_found',
    'role_denied',
    'plan_denied',
    'scopes_undeclared',
    'insufficient_scope',
    'rate_limited',
  ],
  mcp_call_audit_event_surfaces: ['mcp', 'admin_mcp'],
  media_delivery_desired_states: ['allow', 'withheld'],
  media_placement_retirement_reasons: ['asset_deleted', 'owner_removed'],
  membership_google_play_recovery_sweeps: ['notifications', 'active_sources', 'acknowledgements'],
  moderation_transparency_metrics: [
    'reports',
    'moderation_actions',
    'automated_moderation',
    'appeals',
  ],
  oauth_authorization_server_event_types: [
    'consent_approved',
    'consent_denied',
    'access_token_revoked',
    'refresh_family_revoked',
    'refresh_reuse_detected',
  ],
  oauth_authorization_providers: ['facebook', 'x', 'github'],
  oauth_authorization_purposes: ['authenticate', 'connect'],
  oauth_authorization_statuses: [
    'pending',
    'callback_received',
    'exchanging',
    'completion_ready',
    'completed',
    'rejected',
    'expired',
  ],
  oauth_client_types: ['public', 'confidential'],
  oauth_client_token_endpoint_auth_methods: ['none', 'client_secret_basic'],
  post_admission_quota_consumption_modes: ['all_windows', 'daily_only'],
  post_admission_reservation_states: ['in_progress', 'committed'],
  post_classifier_local_outcome_classifications: ['ai', 'human'],
  post_publication_identity_bridge_families: [
    'post',
    'community',
    'rss_feed_item',
    'author',
    'rss_feed',
    'topic_alias',
    'story',
  ],
  post_topic_alias_source_types: ['title', 'markdown', 'explicit'],
  user_deletion_external_work_kinds: [
    'cloudflare-cache-tag',
    'entity-relation-effects',
    's3-export',
    'stripe-customer',
  ],
  user_deletion_request_current_phases: [
    'posts',
    'votes',
    'user-relations',
    'credentials',
    'account-data',
    'relation-impacts',
    'external-work',
    'finalize',
  ],
  digest_frequencies: ['none', 'daily', 'weekly'],
  curated_aside_item_types: ['topic', 'source', 'community'],
} as const
