export {
  MODERATION_REPORT_ENTITY_TYPES,
  type ModerationReportEntityType,
  MODERATION_REPORT_REASONS,
  MODERATION_REPORT_REASON_OPTIONS,
  MODERATION_REPORT_REASON_SEVERITY_ORDER,
  MODERATION_REPORT_REASON_SEVERITY_RANK,
  type ModerationReportReason,
} from './moderation-policy.mts'

export const DUPLICATE_CLUSTER_THRESHOLD = 3
