/** Part 4 CSV from the Commission page “Implementing Regulation laying down templates concerning transparency reporting obligations,” downloaded 2026-10-03 from https://ec.europa.eu/newsroom/dae/redirection/document/113334; SHA-256 c9d8986a04c01a6ae4b84583f3479323eceb884489608474c7d0976fb20eb9e6. */
export const DSA_REPORT_PART4_TEMPLATE = [
  'Applicability,Service,Reporting period,Category of illegal content,"Description of the sub-category ""Other""",Number of notices received ,Number of notices received from Trusted flaggers,Number of specific items of information included in the total number of notices,Number of specific items of information included in the total number of notices by Trusted Flaggers (Trusted Flagger notices),Median time to take action,Median time to take action (Trusted Flagger notices),Number of actions taken on the basis of the law,Number of actions taken on the basis of the law (Trusted Flagger notices),Number of actions taken on the basis of the terms and conditions of the service,Number of actions taken on the basis of the terms and conditions of the service (Trusted Flagger notices),Contextual information on Number of notices received ,Contextual information on Number of notices received from Trusted flaggers,Contextual information on Number of specific items of information included in the total number of notices,Contextual information on Number of specific items of information included in the total number of notices by Trusted Flaggers (Trusted Flagger notices),Contextual information on Median time to take action,Contextual information on Median time to take action (Trusted Flagger notices),Contextual information on Number of actions taken on the basis of the law,Contextual information on Number of actions taken on the basis of the law (Trusted Flagger notices),Contextual information on Number of actions taken on the basis of the terms and conditions of the service,Contextual information on Number of actions taken on the basis of the terms and conditions of the service (Trusted Flagger notices)',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,TOTAL,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_ANIMAL_WELFARE,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_ANIMAL_HARM,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_UNLAWFUL_SALE_ANIMALS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_CONSUMER_INFORMATION,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_HIDDEN_ADVERTISEMENT,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_INSUFFICIENT_INFORMATION_ON_TRADERS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_MISLEADING_INFO_GOODS_SERVICES,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_MISLEADING_INFO_CONSUMER_RIGHTS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_NONCOMPLIANCE_PRICING,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_CYBER_VIOLENCE,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_CYBER_BULLYING_INTIMIDATION,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_CYBER_HARASSMENT,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_CYBER_INCITEMENT,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_CYBER_STALKING,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_NON_CONSENSUAL_IMAGE_SHARING,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_NON_CONSENSUAL_MATERIAL_DEEPFAKE,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_CYBER_VIOLENCE_AGAINST_WOMEN,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_BULLYING_AGAINST_GIRLS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_CYBER_HARASSMENT_AGAINST_WOMEN,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_CYBER_STALKING_AGAINST_WOMEN,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_FEMALE_GENDERED_DISINFORMATION,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_INCITEMENT_AGAINST_WOMEN,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_NON_CONSENSUAL_IMAGE_SHARING_AGAINST_WOMEN,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_NON_CONSENSUAL_MATERIAL_DEEPFAKE_AGAINST_WOMEN,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_DATA_PROTECTION_AND_PRIVACY_VIOLATIONS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_BIOMETRIC_DATA_BREACH,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_DATA_FALSIFICATION,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_MISSING_PROCESSING_GROUND,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_RIGHT_TO_BE_FORGOTTEN,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_ILLEGAL_OR_HARMFUL_SPEECH,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_DEFAMATION,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_DISCRIMINATION,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_HATE_SPEECH,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_INTELLECTUAL_PROPERTY_INFRINGEMENTS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_COPYRIGHT_INFRINGEMENT,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_DESIGN_INFRINGEMENT,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_GEOGRAPHIC_INDICATIONS_INFRINGEMENT,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_PATENT_INFRINGEMENT,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_TRADE_SECRET_INFRINGEMENT,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_TRADEMARK_INFRINGEMENT,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_NEGATIVE_EFFECTS_ON_CIVIC_DISCOURSE_OR_ELECTIONS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_MISINFORMATION_DISINFORMATION,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_VIOLATION_EU_LAW,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_VIOLATION_NATIONAL_LAW,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_PROTECTION_OF_MINORS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_AGE_SPECIFIC_RESTRICTIONS_MINORS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_CHILD_SEXUAL_ABUSE_MATERIAL_DEEPFAKE,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_GROOMING_SEXUAL_ENTICEMENT_MINORS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_UNSAFE_CHALLENGES,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_RISK_FOR_PUBLIC_SECURITY,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_ILLEGAL_ORGANIZATIONS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_RISK_ENVIRONMENTAL_DAMAGE,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_RISK_PUBLIC_HEALTH,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_TERRORIST_CONTENT,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_SCAMS_AND_FRAUD,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_IMPERSONATION_ACCOUNT_HIJACKING,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_INAUTHENTIC_ACCOUNTS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_INAUTHENTIC_LISTINGS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_INAUTHENTIC_USER_REVIEWS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_PHISHING,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_PYRAMID_SCHEMES,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_SELF_HARM,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_CONTENT_PROMOTING_EATING_DISORDERS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_SELF_MUTILATION,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_SUICIDE,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_UNSAFE_AND_PROHIBITED_PRODUCTS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_PROHIBITED_PRODUCTS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_UNSAFE_PRODUCTS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_VIOLENCE,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_COORDINATED_HARM,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_INCITEMENT_VIOLENCE_HATRED,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_HUMAN_EXPLOITATION,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_HUMAN_TRAFFICKING,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_TRAFFICKING_WOMEN_GIRLS,,,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,KEYWORD_OTHER,"Text to detail the ""Other"" keyword.",,,,,,,,,,,,,,,,,,,,',
  '"Only for providers of hosting services, including online platforms",,YYYY-MM-DD/YYYY-MM-DD,STATEMENT_CATEGORY_NOT_SPECIFIED_NOTICE,,,,,,,,,,,,,,,,,,,,,',
]
  .join('\n')
  .concat('\n')

/** Part 7 CSV from the Commission page “Implementing Regulation laying down templates concerning transparency reporting obligations,” downloaded 2026-10-03 from https://ec.europa.eu/newsroom/dae/redirection/document/113341; SHA-256 c355cf9369a115fa51f9c9626cc7917bc24b48db7d6dc6cff3028c81de388aad. */
export const DSA_REPORT_PART7_TEMPLATE = [
  'Applicability,Service,Reporting period,Section,Indicator,Scope,Value,Contextual Information',
  'All,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Number of complaints submitted to the internal-complaints mechanism,Total number,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Number of complaints submitted to the internal-complaints mechanism,Decisions upheld,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Number of complaints submitted to the internal-complaints mechanism,Decisions partially reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Number of complaints submitted to the internal-complaints mechanism,Decisions reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Number of complaints submitted to the internal-complaints mechanism,Median time,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Number of complaints submitted to the internal-complaints mechanism,Decision omitted,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Number of restrictions newly imposed as a result of an internal complaint,Total number,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to remove or disable access to or restrict visibility of information,Total number,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to remove or disable access to or restrict visibility of information,Decisions upheld,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to remove or disable access to or restrict visibility of information,Decisions partially reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to remove or disable access to or restrict visibility of information,Decisions reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to remove or disable access to or restrict visibility of information,Median time,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to suspend or terminate the provision of the service,Total number,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to suspend or terminate the provision of the service,Decisions upheld,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to suspend or terminate the provision of the service,Decisions partially reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to suspend or terminate the provision of the service,Decisions reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to suspend or terminate the provision of the service,Median time,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to suspend or terminate an account ,Total number,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to suspend or terminate an account ,Decisions upheld,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to suspend or terminate an account ,Decisions partially reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to suspend or terminate an account ,Decisions reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to suspend or terminate an account ,Median time,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to restrict the ability to monetise information,Total number,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to restrict the ability to monetise information,Decisions upheld,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to restrict the ability to monetise information,Decisions partially reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to restrict the ability to monetise information,Decisions reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision to restrict the ability to monetise information,Median time,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision not to take action on a notice submitted in accordance with Article 16,Total number,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision not to take action on a notice submitted in accordance with Article 16,Decisions upheld,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision not to take action on a notice submitted in accordance with Article 16,Decisions partially reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision not to take action on a notice submitted in accordance with Article 16,Decisions reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision not to take action on a notice submitted in accordance with Article 16,Median time,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision not to take action on a notice submitted by a Trusted Flagger in accordance with Article 16,Total number,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision not to take action on a notice submitted by a Trusted Flagger in accordance with Article 16,Decisions upheld,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision not to take action on a notice submitted by a Trusted Flagger in accordance with Article 16,Decisions partially reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision not to take action on a notice submitted by a Trusted Flagger in accordance with Article 16,Decisions reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Internal complaints mechanism,Complaint regarding a decision not to take action on a notice submitted by a Trusted Flagger in accordance with Article 16,Median time,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Out-of-court dispute settlement bodies,Number of disputes submitted to out-of-court dispute settlement bodies,Total number,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Out-of-court dispute settlement bodies,Number of disputes submitted to out-of-court dispute settlement bodies,Decisions upheld,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Out-of-court dispute settlement bodies,Number of disputes submitted to out-of-court dispute settlement bodies,Decisions partially reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Out-of-court dispute settlement bodies,Number of disputes submitted to out-of-court dispute settlement bodies,Decisions reversed,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Out-of-court dispute settlement bodies,Number of disputes submitted to out-of-court dispute settlement bodies,Median time,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Out-of-court dispute settlement bodies,Number of disputes submitted to out-of-court dispute settlement bodies,Decision omitted,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Out-of-court dispute settlement bodies,Number of disputes submitted to out-of-court dispute settlement bodies,Percentage of outcomes implemented,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Suspensions imposed on repeated offenders,Number of suspensions enacted for the provision of manifestly illegal content ,Total number,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Suspensions imposed on repeated offenders,Number of suspensions enacted for the provision of manifestly unfounded notices,Total number,,',
  'Only for providers of online platforms,,YYYY-MM-DD/YYYY-MM-DD,Suspensions imposed on repeated offenders,Number of suspensions enacted for the provision of manifestly unfounded complaints,Total number,,',
]
  .join('\n')
  .concat('\n')
