#!/usr/bin/env node

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { htmlPage, renderMarkdownToHtml } from './render-docs-page.mts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DEFAULT_CATALOG_PATH = resolve(__dirname, '..', 'api-fixtures/v1/mcp.json')
const PAGE_TITLE = 'Voucha MCP Servers'

// Structural view of api-fixtures/v1/mcp.json, generated by
// backend/services/mcp-tools/catalog/build-mcp-catalog.test.mts (`pnpm run mcp:catalog`).
type CatalogTool = {
  tool: {
    name: string
    description?: string
    inputSchema: unknown
    annotations?: Record<string, unknown>
    _meta?: { 'voucha/requiredScopes'?: string[] }
  }
  plan?: string
  roles: string[] | null
  api: { method: string; path: string }[] | null
}

type CatalogServer = { name: string; path: string; surface: string; tools: CatalogTool[] }

type Catalog = { servers: CatalogServer[] }

function codeList(values: readonly string[]): string {
  return values.map(value => `\`${value}\``).join(', ') || 'none'
}

function jsonFence(value: unknown): string {
  const json = JSON.stringify(value, null, 2)
  const longestRun = Math.max(0, ...[...json.matchAll(/`+/g)].map(([run]) => run.length))
  const fence = '`'.repeat(Math.max(3, longestRun + 1))
  return `${fence}json\n${json}\n${fence}`
}

function toolMarkdown({ tool, plan, roles, api }: CatalogTool): string {
  const facts = [
    ...(plan === undefined ? [] : [`- **Minimum plan:** ${plan}`]),
    `- **Roles:** ${roles === null ? 'any authenticated user' : codeList(roles)}`,
    `- **Required scopes:** ${codeList(tool['_meta']?.['voucha/requiredScopes'] ?? [])}`,
    `- **Annotations:** ${codeList(
      Object.entries(tool.annotations ?? {}).map(([key, value]) => `${key}: ${String(value)}`),
    )}`,
    `- **REST equivalent:** ${
      api === null ? 'none' : codeList(api.map(({ method, path }) => `${method} ${path}`))
    }`,
  ]
  return [
    `### \`${tool.name}\``,
    tool.description ?? '',
    facts.join('\n'),
    'Input schema:',
    jsonFence(tool.inputSchema),
  ]
    .filter(Boolean)
    .join('\n\n')
}

function serverMarkdown(server: CatalogServer): string {
  return [
    `## \`${server.name}\``,
    `Endpoint: \`POST ${server.path}\` · Surface: \`${server.surface}\` · Tools: ${server.tools.length}`,
    ...server.tools.map(toolMarkdown),
  ].join('\n\n')
}

export function catalogMarkdown(catalog: Catalog): string {
  return [
    `# ${PAGE_TITLE}`,
    'Every tool each Voucha Model Context Protocol server can list, generated from the tool ' +
      'registry. A caller sees the subset its plan, roles and granted scopes allow. The ' +
      'machine-readable catalog is [mcp.json](mcp.json).',
    ...catalog.servers.map(serverMarkdown),
  ].join('\n\n')
}

async function readCatalog(catalogPath: string): Promise<{ raw: string; catalog: Catalog }> {
  const raw = await readFile(catalogPath, 'utf8').catch((error: NodeJS.ErrnoException) => {
    throw new Error(`Cannot read MCP catalog at ${catalogPath}: ${error.message}`, {
      cause: error,
    })
  })
  let catalog: Partial<Catalog>
  try {
    catalog = JSON.parse(raw) as Partial<Catalog>
  } catch (error) {
    throw new Error(`Cannot parse MCP catalog at ${catalogPath}: ${(error as Error).message}`, {
      cause: error,
    })
  }
  if (!Array.isArray(catalog.servers))
    throw new Error(`MCP catalog at ${catalogPath} has no servers array`)
  return { raw, catalog: { servers: catalog.servers } }
}

export async function renderMcpDocs({
  outputDir,
  catalogPath = DEFAULT_CATALOG_PATH,
}: {
  outputDir: string
  catalogPath?: string
}): Promise<void> {
  const { raw, catalog } = await readCatalog(catalogPath)
  const html = htmlPage(PAGE_TITLE, await renderMarkdownToHtml(catalogMarkdown(catalog)))
  await mkdir(outputDir, { recursive: true })
  await Promise.all([
    writeFile(join(outputDir, 'index.html'), html),
    writeFile(join(outputDir, 'mcp.json'), raw),
  ])
}

export async function main(argv: string[]): Promise<number> {
  const [outputDir] = argv
  if (!outputDir) {
    console.error('Usage: render-mcp-docs.mts <output-dir>')
    return 2
  }
  try {
    await renderMcpDocs({ outputDir })
  } catch (error) {
    console.error((error as Error).message)
    return 1
  }
  return 0
}

/* v8 ignore start -- direct-execution entry; the CLI test spawns it in a child process, and
   main() (the testable half) is covered directly in render-mcp-docs.test.mts. */
const invokedPath = process.argv[1]
if (invokedPath !== undefined && fileURLToPath(import.meta.url) === resolve(invokedPath)) {
  process.exit(await main(process.argv.slice(2)))
}
/* v8 ignore stop */
