HTTP/1.1 401 Unauthorized
content-type: application/json
request-id: req_messageserrorauthenticat

{"type":"error","error":{"type":"authentication_error","message":"invalid x-api-key"},"request_id":"req_messageserrorauthenticat"}
