HTTP/1.1 400 Bad Request
content-type: application/json
request-id: req_messageserrorcreditbalan

{"type":"error","error":{"type":"invalid_request_error","message":"Your credit balance is too low to access the Anthropic API. Please go to Plans & Billing to upgrade or purchase credits."},"request_id":"req_messageserrorcreditbalan"}
