import type { ApiFixtureCase } from './types.mts'

export const copyrightDsaApiFixtureCases: ApiFixtureCase[] = [
  {
    id: 'web.copyright.eu.transparency-report-csv',
    method: 'GET',
    path: '/api/v1/copyright-eu-reports',
    route: { routeTemplate: '/api/v1/copyright-eu-reports' },
    query: {
      period_start: '2026-01-01T00:00:00.000Z',
      period_end: '2026-02-01T00:00:00.000Z',
      format: 'csv_notices',
    },
    auth: 'fixture-admin',
    status: 200,
    body: 'Applicability,Service,Reporting period\r\n',
    backendResponseContractKey: 'GET:/api/v1/copyright-eu-reports#implicit-2',
    consumers: ['web'],
    migratedFrom: ['backend/api/v1/copyright-notices/eu-copyright-report-route.mts'],
  },
  {
    id: 'web.copyright.eu.transparency-report',
    method: 'GET',
    path: '/api/v1/copyright-eu-reports',
    route: { routeTemplate: '/api/v1/copyright-eu-reports' },
    query: {
      period_start: '2026-01-01T00:00:00.000Z',
      period_end: '2026-02-01T00:00:00.000Z',
    },
    auth: 'fixture-admin',
    status: 200,
    body: {
      copyright_eu_report: {
        period_start: '2026-01-01T00:00:00.000Z',
        period_end: '2026-02-01T00:00:00.000Z',
        generated_at: '2026-02-01T00:01:00.000Z',
        receipt_count: 0,
        statement_of_reasons_count: 0,
        redress_request_count: 0,
        redress_decision_count: 0,
        supervised_complaint_count: 0,
        escalation_count: 0,
        notices_received_count: 0,
        notices_received_trusted_flagger_count: 0,
        notified_items_count: 0,
        notified_items_trusted_flagger_count: 0,
        actions_on_law_count: 0,
        actions_on_law_trusted_flagger_count: 0,
        actions_on_terms_count: 0,
        actions_on_terms_trusted_flagger_count: 0,
        notices_processed_by_automated_means_count: 0,
        restrictions_imposed_by_automated_means_count: 0,
        complaints_by_submitter: { notifier: 0, poster: 0, reviewer: 0 },
        complaints_by_decision_type: {
          restrict: { received: 0, upheld: 0, partially_reversed: 0, reversed: 0 },
          no_action: { received: 0, upheld: 0, partially_reversed: 0, reversed: 0 },
          no_action_trusted_flagger: { received: 0, upheld: 0, partially_reversed: 0, reversed: 0 },
        },
      },
    },
    consumers: ['web'],
    migratedFrom: ['backend/api/v1/copyright-notices/eu-copyright-report-route.mts'],
  },
  {
    id: 'copyright.dsa-statement.replay',
    method: 'POST',
    path: '/api/v1/copyright-dsa-statement-submissions/00000000-0000-7000-8000-000000001221/replays',
    route: {
      routeTemplate: '/api/v1/copyright-dsa-statement-submissions/:id/replays',
      pathParams: { id: '00000000-0000-7000-8000-000000001221' },
    },
    auth: 'fixture-admin',
    status: 200,
    body: { replayed: true },
    consumers: [],
    migratedFrom: ['backend/api/v1/copyright-notices/dsa-statement-replay-route.mts'],
  },
]
