import type { ApiFixtureCase } from './types.mts'

export const nativeUserProfileHeaderApiFixtureCases: ApiFixtureCase[] = [
  {
    id: 'native.users.profile.default',
    method: 'GET',
    path: '/api/v1/users/alice',
    query: { include_bio: '1' },
    route: {
      routeTemplate: '/api/v1/users/:username',
      pathParams: { username: 'alice' },
    },
    auth: 'fixture-user',
    status: 200,
    backendResponseContractKey: 'GET:/api/v1/users/:idOrSlug#self',
    body: {
      user: {
        __entity_type: 'user',
        id: 'user-abc',
        username: 'alice',
        profile_image_id: 'avatar-1',
        profile_image_placement: {
          placement_id: 'placement-user-avatar-1',
          placement_revision: 2,
          image_id: 'avatar-1',
        },
        markdown: 'Hello',
        roles: ['user'],
        cards_visibility: 'everyone',
        rewards_program_statuses_visibility: 'everyone',
        spending_categories_visibility: 'everyone',
        follows_visibility: 'everyone',
        topic_follows_visibility: 'everyone',
        rss_feed_follows_visibility: 'everyone',
        community_memberships_visibility: 'everyone',
        followers_visibility: 'everyone',
        likes_visibility: 'everyone',
        direct_messages_audience: 'users',
        default_post_broadcast: 'everyone',
        default_post_privacy: 'public',
        engagement_emails_enabled: true,
        news_digest_frequency: 'weekly',
        moderation_emails_enabled: true,
        community_digest_frequency: 'weekly',
        moderation_email_cadence: 'daily',
        moderation_email_days_of_week: [1, 2, 3, 4, 5],
        moderation_email_time_of_day: '09:00',
        moderation_email_timezone: 'America/Los_Angeles',
        fediverse_federation_enabled: false,
      },
      user_bio_html: '<p>Hello</p>',
      user_metrics: {
        __entity_type: 'user_metrics',
        id: 'user-abc',
        count: {
          comments: 2,
          discussions: 3,
          reviews: 4,
          users_following: 5,
          users_followers: 6,
          topics_following: 7,
          rss_feeds_following: 8,
          communities_member: 9,
        },
        viewer_count: {
          comments: 7,
          discussions: 2,
          reviews: 1,
        },
        bookmarks: {
          follow: { topics: 1, posts: 2, users: 3 },
        },
        bookmarkers: { follow: 4 },
        bookmarks__updated_at: '2026-07-01T16:00:00Z',
      },
      profile_links: [
        {
          id: 'link-1',
          user_id: 'user-abc',
          link_type: 'url',
          name: 'Site',
          url: 'https://example.test',
          handle: null,
          image_id: 'profile-link-image-1',
          image_placement: {
            placement_id: 'placement-profile-link-image-1',
            placement_revision: 1,
            image_id: 'profile-link-image-1',
          },
          url_id: null,
          sort_order: 0,
          created_at: '2026-07-01T16:00:00Z',
          updated_at: '2026-07-01T16:00:00Z',
        },
      ],
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [
      'https://github.com/vouchington/vouchington-clients/blob/main/dotnet-clients/tests/Voucha.Client.Core.Tests/Api/VouchaApiClientUserNotificationTests.cs',
    ],
  },
  {
    id: 'native.users.vouch-context.default',
    method: 'GET',
    path: '/api/v1/users/user-abc/vouch-context',
    route: {
      routeTemplate: '/api/v1/users/:id/vouch-context',
      pathParams: { id: 'user-abc' },
    },
    auth: 'fixture-user',
    status: 200,
    backendResponseContractKey: 'GET:/api/v1/users/:id/vouch-context',
    body: {
      positive_by_following: { total: 0, users: [] },
      negative_by_following: { total: 0, users: [] },
      election_vote: {
        __entity_type: 'election_vote',
        user_id: 'fixture-user',
        entity_id: 'user-abc',
        choice: 'like',
        created_at: '2026-07-01T16:00:00Z',
      },
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  {
    id: 'native.users.profile.restricted',
    method: 'GET',
    path: '/api/v1/users/restricted',
    query: { include_bio: '1' },
    route: {
      routeTemplate: '/api/v1/users/:idOrSlug',
      pathParams: { idOrSlug: 'restricted' },
    },
    auth: 'none',
    status: 200,
    body: {
      user: {
        __entity_type: 'user',
        id: 'user-restricted',
        username: 'restricted',
        markdown: 'Private collections',
        roles: ['user'],
      },
      user_bio_html: '<p>Private collections</p>',
      user_metrics: {
        __entity_type: 'user_metrics',
        id: 'user-restricted',
        count: {
          comments: 2,
          discussions: 3,
          reviews: 4,
          users_following: 0,
          users_followers: 0,
          topics_following: 0,
          rss_feeds_following: 0,
          communities_member: 0,
        },
        bookmarks: {
          follow: { topics: 0, posts: 0, users: 0 },
        },
        bookmarkers: { follow: 0 },
        bookmarks__updated_at: '2026-07-01T16:00:00Z',
      },
      profile_links: [],
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
]
