import { nativeModerationFixtureCase as fixtureCase } from './native-moderation-fixture-case.mts'

export const nativeModerationReportApiFixtureCases = [
  fixtureCase({
    id: 'native.moderation.reports.default',
    backendResponseContractKey: 'GET:/api/v1/reports#staff',
    method: 'GET',
    path: '/api/v1/reports',
    query: { limit: '25', status: 'pending' },
    route: { routeTemplate: '/api/v1/reports' },
    migratedFrom: ['backend/api/v1/reports/reports.mts'],
  }),
  fixtureCase({
    id: 'native.moderation.reports.member.default',
    backendResponseContractKey: 'GET:/api/v1/reports#member',
    method: 'GET',
    path: '/api/v1/reports',
    query: { limit: '25', status: 'pending' },
    route: { routeTemplate: '/api/v1/reports' },
    auth: 'fixture-user',
    body: {
      reports: [
        {
          id: 'report-1',
          case_id: 'case-1',
          created_at: '2026-06-01T12:00:00.000Z',
          reviewed_at: null,
          entity_type: 'post',
          entity_id: 'post-1',
          reason: 'spam',
          status: 'pending',
          report_count: 3,
          target_available: true,
          target_label: 'Native post',
          target_content: {
            kind: 'post',
            text: 'Native post',
            declared_language: null,
            lingua_rs_detected_language: null,
          },
          target_path: '/review/native-post',
          post_moderation_context: null,
        },
      ],
      page_info: { has_next_page: false, end_cursor: null },
    },
    migratedFrom: ['backend/api/v1/reports/reports.mts'],
  }),
  fixtureCase({
    id: 'native.moderation.reports.clustered.default',
    backendResponseContractKey: 'GET:/api/v1/reports#clustered',
    method: 'GET',
    path: '/api/v1/reports',
    query: { cluster: 'entity', limit: '25', status: 'pending' },
    route: { routeTemplate: '/api/v1/reports' },
    migratedFrom: ['backend/api/v1/reports/reports.mts'],
  }),
  fixtureCase({
    id: 'native.moderation.report-judgement.default',
    method: 'POST',
    path: '/api/v1/reports/report-1/judgements',
    route: {
      routeTemplate: '/api/v1/reports/:reportId/judgements',
      pathParams: { reportId: 'report-1' },
    },
    status: 202,
    migratedFrom: ['backend/api/v1/reports/reports.mts'],
  }),
  fixtureCase({
    id: 'native.moderation.report-resolution.reviewed',
    method: 'PATCH',
    path: '/api/v1/reports/report-1',
    requestBody: { status: 'reviewed' },
    route: {
      routeTemplate: '/api/v1/reports/:id',
      pathParams: { id: 'report-1' },
    },
    body: {
      report: {
        id: 'report-1',
        case_id: 'case-1',
        created_at: '2026-06-01T12:00:00.000Z',
        reviewed_at: '2026-06-01T12:30:00.000Z',
        reporter_user_id: 'user-1',
        entity_type: 'user',
        entity_id: 'user-2',
        reason: 'harassment',
        note: 'Repeated contact.',
        status: 'reviewed',
        resolved_by_id: 'admin-1',
      },
    },
    migratedFrom: ['backend/api/v1/reports/reports.mts'],
  }),
  fixtureCase({
    id: 'native.moderation.admin-warning.report',
    method: 'POST',
    path: '/api/v1/admin/warnings',
    requestBody: {
      userId: 'user-2',
      reason: 'Repeated harassment',
      publicMessage: 'Stop contacting this user.',
      reportId: 'report-1',
      resolveReport: true,
    },
    route: { routeTemplate: '/api/v1/admin/warnings' },
    status: 201,
    body: {
      warning: {
        id: 'warning-1',
        case_id: 'case-1',
        user_id: 'user-2',
        community_id: null,
        issued_by_id: 'admin-1',
        reason: 'Repeated harassment',
        public_message: 'Stop contacting this user.',
        report_id: 'report-1',
        revoked_at: null,
        revoked_by_id: null,
        created_at: '2026-06-01T12:30:00.000Z',
      },
    },
    migratedFrom: ['backend/api/v1/admin/warnings.mts'],
  }),
  fixtureCase({
    id: 'native.moderation.ban-evasion.confirm',
    method: 'POST',
    path: '/api/v1/communities/community-1/ban-evasion/user-2',
    route: {
      routeTemplate: '/api/v1/communities/:idOrSlug/ban-evasion/:userId',
      pathParams: { idOrSlug: 'community-1', userId: 'user-2' },
    },
    status: 204,
    body: null,
    migratedFrom: ['backend/api/v1/communities/ban-evasion.mts'],
  }),
  fixtureCase({
    id: 'native.moderation.ban-evasion.dismiss',
    method: 'DELETE',
    path: '/api/v1/communities/community-1/ban-evasion/user-2',
    route: {
      routeTemplate: '/api/v1/communities/:idOrSlug/ban-evasion/:userId',
      pathParams: { idOrSlug: 'community-1', userId: 'user-2' },
    },
    status: 204,
    body: null,
    migratedFrom: ['backend/api/v1/communities/ban-evasion.mts'],
  }),
]
