import {
  nativeDomainTopic,
  nativeHostname,
  nativeHostnameElection,
  nativeLatestCrawl,
  nativeModeratedHostname,
  nativePageInfo,
  nativeTopUrl,
  nativeUrl,
} from './native-domain-url-data.mts'
import type { ApiFixtureCase } from './types.mts'

const sharedCase: Pick<ApiFixtureCase, 'auth' | 'status' | 'consumers'> = {
  auth: 'fixture-user',
  status: 200,
  consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
}

export const nativeDomainUrlApiFixtureCases: ApiFixtureCase[] = [
  {
    ...sharedCase,
    id: 'native.hostnames.default',
    method: 'GET',
    path: '/api/v1/hostnames',
    query: { limit: '25', query: 'example' },
    route: { routeTemplate: '/api/v1/hostnames' },
    backendResponseContractKey: 'GET:/api/v1/hostnames',
    migratedFrom: ['web/types/hostnames.ts'],
    body: {
      results: [{ __entity_type: 'hostname', id: 'hostname-1' }],
      page_info: nativePageInfo,
      hostnames: { 'hostname-1': nativeHostname },
      topics: { 'topic-1': nativeDomainTopic },
      hostname_elections: { 'hostname-1': nativeHostnameElection },
      top_urls_by_hostname_id: {
        'hostname-1': [
          { id: nativeTopUrl.id, pathname: nativeTopUrl.pathname, url: nativeTopUrl.url },
        ],
      },
      election_votes: {
        'hostname-1': {
          __entity_type: 'election_vote',
          created_at: '2026-01-01T00:00:00Z',
          entity_id: 'hostname-1',
          choice: 'like',
          user_id: 'user-1',
        },
      },
    },
  },
  {
    ...sharedCase,
    id: 'native.hostname.default',
    method: 'GET',
    path: '/api/v1/hostnames/hostname-1',
    route: {
      routeTemplate: '/api/v1/hostnames/:id',
      pathParams: { id: 'hostname-1' },
    },
    backendResponseContractKey: 'GET:/api/v1/hostnames/:id#public',
    migratedFrom: ['web/types/hostnames.ts'],
    body: {
      hostname: nativeHostname,
      topic: null,
      top_urls: [nativeTopUrl],
      rss_feeds: [
        {
          __entity_type: 'rss_feed',
          id: 'rss-feed-1',
          title: 'Example Feed',
          is_enabled: true,
          is_discoverable: true,
          etag: null,
          last_modified_at: null,
          last_fetched_at: null,
          feed_type: 'article',
          rss_feed_url: {
            __entity_type: 'url',
            id: 'url-feed-1',
            url: 'https://example.com/feed.xml',
            pathname: '/feed.xml',
            search_params: {},
            canonical_url_id: null,
            hostname: nativeModeratedHostname,
          },
          home_page_url: null,
          hostname: null,
          topic: nativeDomainTopic,
          publisher_type: null,
          podcast_show: null,
        },
      ],
      hostname_election: nativeHostnameElection,
      election_vote: null,
    },
  },
  {
    ...sharedCase,
    id: 'native.urls.default',
    method: 'GET',
    path: '/api/v1/urls',
    query: { limit: '25', query: 'example' },
    route: { routeTemplate: '/api/v1/urls' },
    backendResponseContractKey: 'GET:/api/v1/urls#public',
    migratedFrom: ['web/types/api-responses/urls-onboarding-and-trends.ts'],
    body: {
      results: [
        {
          __entity_type: 'url',
          id: 'url-1',
          url: nativeTopUrl.url,
          pathname: nativeTopUrl.pathname,
          canonical_url_id: null,
          search_params: {},
          hostname: nativeHostname,
        },
      ],
      page_info: nativePageInfo,
    },
  },
  {
    ...sharedCase,
    id: 'native.url.default',
    method: 'GET',
    path: '/api/v1/urls/url-1',
    route: {
      routeTemplate: '/api/v1/urls/:id',
      pathParams: { id: 'url-1' },
    },
    backendResponseContractKey: 'GET:/api/v1/urls/:id#privileged',
    auth: 'fixture-admin',
    migratedFrom: ['web/types/api-responses/urls-onboarding-and-trends.ts'],
    body: {
      url: nativeUrl,
      latest_crawl: null,
      can_view_latest_crawl: true,
      can_view_crawl_history: true,
      can_trigger_crawl: true,
      url_type: 'url',
      rss_feed_id: null,
    },
  },
  {
    ...sharedCase,
    id: 'native.url-crawls.default',
    method: 'GET',
    path: '/api/v1/urls/url-1/crawls',
    query: { limit: '25' },
    route: {
      routeTemplate: '/api/v1/urls/:id/crawls',
      pathParams: { id: 'url-1' },
    },
    backendResponseContractKey: 'GET:/api/v1/urls/:id/crawls#privileged',
    auth: 'fixture-admin',
    migratedFrom: ['web/types/api-responses/urls-onboarding-and-trends.ts'],
    body: {
      results: [nativeLatestCrawl],
      page_info: nativePageInfo,
    },
  },
  {
    ...sharedCase,
    id: 'native.url-crawl.default',
    method: 'GET',
    path: '/api/v1/urls/url-1/crawls/crawl-1',
    route: {
      routeTemplate: '/api/v1/urls/:id/crawls/:crawlId',
      pathParams: { id: 'url-1', crawlId: 'crawl-1' },
    },
    backendResponseContractKey: 'GET:/api/v1/urls/:id/crawls/:crawlId#privileged',
    auth: 'fixture-admin',
    migratedFrom: ['web/types/api-responses/urls-onboarding-and-trends.ts'],
    body: {
      crawl: {
        ...nativeLatestCrawl,
        markdown: '# Native client guide\n\nFixture content for native URL crawl details.',
      },
      og_image_sideload: null,
    },
  },
  {
    ...sharedCase,
    id: 'native.url-crawl-trigger.default',
    method: 'POST',
    path: '/api/v1/urls/url-1/crawl',
    route: {
      routeTemplate: '/api/v1/urls/:id/crawl',
      pathParams: { id: 'url-1' },
    },
    auth: 'fixture-admin',
    migratedFrom: ['backend/api/v1/urls/README.md'],
    body: { success: true, message: 'Crawl enqueued', target: 'html_url', enqueued_count: 1 },
  },
]
