import { nativeHostnameElection } from './native-domain-url-data.mts'
import {
  hostnameId,
  publicInstanceAttributes,
  instanceTopic,
  topicElection,
  topicId,
  publicUnclassifiedAttributes,
  unclassifiedTopic,
  unclassifiedTopicId,
  publicUnknownRegistrationsAttributes,
  unknownRegistrationsTopic,
  unknownRegistrationsTopicId,
} from './native-fediverse-data.mts'
import type { ApiFixtureCase } from './types.mts'

export const nativeFediverseApiFixtureCases: ApiFixtureCase[] = [
  {
    id: 'native.fediverse.instances.default',
    method: 'GET',
    path: '/api/v1/fediverse/instances',
    query: { limit: '25', sort: 'best' },
    route: { routeTemplate: '/api/v1/fediverse/instances' },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [
        {
          __entity_type: 'topic',
          id: topicId,
          name: instanceTopic.name,
          slug: instanceTopic.slug,
          topic_type: instanceTopic.topic_type,
        },
        {
          __entity_type: 'topic',
          id: unclassifiedTopicId,
          name: unclassifiedTopic.name,
          slug: unclassifiedTopic.slug,
          topic_type: unclassifiedTopic.topic_type,
        },
      ],
      page_info: { has_next_page: true, start_cursor: 'first', end_cursor: 'next' },
      topics: { [topicId]: instanceTopic, [unclassifiedTopicId]: unclassifiedTopic },
      topics_metrics: {},
      fediverse_instances: {
        [topicId]: publicInstanceAttributes,
        [unclassifiedTopicId]: publicUnclassifiedAttributes,
      },
      topic_elections: { [topicId]: topicElection },
      hostname_elections: {
        [hostnameId]: { ...nativeHostnameElection, id: hostnameId },
      },
      markdown_to_html: { [topicId]: '<p>A community-run Mastodon instance.</p>' },
      bookmarks: {},
      election_votes: {},
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  {
    id: 'native.fediverse.instances.page-2',
    method: 'GET',
    path: '/api/v1/fediverse/instances',
    query: { limit: '25', after: 'next' },
    route: { routeTemplate: '/api/v1/fediverse/instances' },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [
        {
          __entity_type: 'topic',
          id: unknownRegistrationsTopicId,
          name: unknownRegistrationsTopic.name,
          slug: unknownRegistrationsTopic.slug,
          topic_type: unknownRegistrationsTopic.topic_type,
        },
      ],
      page_info: { has_next_page: false, start_cursor: 'next', end_cursor: 'last' },
      topics: { [unknownRegistrationsTopicId]: unknownRegistrationsTopic },
      topics_metrics: {},
      fediverse_instances: {
        [unknownRegistrationsTopicId]: publicUnknownRegistrationsAttributes,
      },
      topic_elections: {},
      hostname_elections: {},
      markdown_to_html: {},
      bookmarks: {},
      election_votes: {},
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  {
    id: 'native.fediverse.instances.empty',
    method: 'GET',
    path: '/api/v1/fediverse/instances',
    query: { q: 'no-match-fixture-query' },
    route: { routeTemplate: '/api/v1/fediverse/instances' },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [],
      page_info: { has_next_page: false, start_cursor: null, end_cursor: null },
      topics: {},
      topics_metrics: {},
      fediverse_instances: {},
      topic_elections: {},
      hostname_elections: {},
      markdown_to_html: {},
      bookmarks: {},
      election_votes: {},
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  {
    id: 'native.fediverse.instance.slug',
    method: 'GET',
    path: '/api/v1/fediverse/instances/social-example',
    route: {
      routeTemplate: '/api/v1/fediverse/instances/:id',
      pathParams: { id: 'social-example' },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      topic: instanceTopic,
      fediverse_instance: publicInstanceAttributes,
      topic_election: topicElection,
      hostname_election: { ...nativeHostnameElection, id: hostnameId },
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  {
    id: 'native.fediverse.instance.uuid',
    method: 'GET',
    path: `/api/v1/fediverse/instances/${unclassifiedTopicId}`,
    route: {
      routeTemplate: '/api/v1/fediverse/instances/:id',
      pathParams: { id: unclassifiedTopicId },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      topic: unclassifiedTopic,
      fediverse_instance: publicUnclassifiedAttributes,
      topic_election: null,
      hostname_election: null,
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
]
