import { timestamp, user } from './data.mts'

export const author = {
  __entity_type: 'user',
  id: user.id,
  username: user.username,
  roles: [],
  profile_image_id: null,
}

export const otherUser = {
  __entity_type: 'user',
  id: 'comment-user-2',
  username: 'commenter',
  roles: [],
  profile_image_id: null,
}

const moderationNulls = {
  clearance_reason: null,
  clearance_updated_at: null,
  spam_detection_created_at: null,
  spam_detection_flagged: null,
  spam_detection_results: null,
  spam_detection_score: null,
  updated_by_id: null,
}

export const rootPost = {
  __entity_type: 'post',
  id: 'comment-root-post',
  slug: 'comment-root',
  post_type: 'discussion',
  title: 'Comment thread fixture',
  markdown: 'Root post markdown',
  parent_id: null,
  root_id: null,
  created_by_id: user.id,
  created_by: author,
  created_at: timestamp,
  updated_at: timestamp,
  deleted_at: null,
  deleted_by_id: null,
  archived_at: null,
  archived_by_id: null,
  locked_at: null,
  locked_by_id: null,
  broadcast: 'everyone',
  privacy: 'public',
  is_anonymous: false,
  community_id: null,
  clearance_status: null,
  ...moderationNulls,
  can_edit_content: true,
  can_delete: true,
  can_lock: true,
}

export const topLevelComment = {
  __entity_type: 'post',
  id: 'comment-a',
  slug: null,
  post_type: 'comment',
  title: '',
  markdown: 'Top-level native comment',
  parent_id: rootPost.id,
  root_id: rootPost.id,
  created_by_id: user.id,
  created_by: author,
  created_at: timestamp,
  updated_at: timestamp,
  deleted_at: null,
  deleted_by_id: null,
  archived_at: null,
  archived_by_id: null,
  locked_at: null,
  locked_by_id: null,
  broadcast: 'everyone',
  privacy: 'public',
  is_anonymous: false,
  community_id: null,
  clearance_status: null,
  ...moderationNulls,
  can_edit_content: true,
  can_delete: true,
  can_lock: true,
}

export const nestedComment = {
  __entity_type: 'post',
  id: 'comment-b',
  slug: null,
  post_type: 'comment',
  title: '',
  markdown: 'Nested reply with votes',
  parent_id: topLevelComment.id,
  root_id: rootPost.id,
  created_by_id: otherUser.id,
  created_by: otherUser,
  created_at: timestamp,
  updated_at: timestamp,
  deleted_at: null,
  deleted_by_id: null,
  archived_at: null,
  archived_by_id: null,
  locked_at: null,
  locked_by_id: null,
  broadcast: 'everyone',
  privacy: 'public',
  is_anonymous: false,
  community_id: null,
  clearance_status: null,
  ...moderationNulls,
  can_edit_content: false,
  can_delete: false,
  can_lock: false,
}

export const anonymousComment = {
  __entity_type: 'post',
  id: 'comment-c',
  slug: null,
  post_type: 'comment',
  title: '',
  markdown: 'Anonymous native reply',
  parent_id: rootPost.id,
  root_id: rootPost.id,
  created_by_id: null,
  created_by: null,
  created_at: timestamp,
  updated_at: timestamp,
  deleted_at: null,
  deleted_by_id: null,
  archived_at: null,
  archived_by_id: null,
  locked_at: null,
  locked_by_id: null,
  broadcast: 'everyone',
  privacy: 'public',
  is_anonymous: true,
  community_id: null,
  clearance_status: null,
  ...moderationNulls,
  can_edit_content: false,
  can_delete: false,
  can_lock: false,
}

export const deletedComment = {
  __entity_type: 'post',
  id: 'comment-d',
  slug: null,
  post_type: 'comment',
  title: '',
  markdown: null,
  parent_id: nestedComment.id,
  root_id: rootPost.id,
  created_by_id: null,
  created_by: null,
  created_at: timestamp,
  updated_at: timestamp,
  deleted_at: timestamp,
  deleted_by_id: user.id,
  archived_at: null,
  archived_by_id: null,
  locked_at: null,
  locked_by_id: null,
  broadcast: 'everyone',
  privacy: 'public',
  is_anonymous: false,
  community_id: null,
  clearance_status: null,
  ...moderationNulls,
  can_edit_content: false,
  can_delete: false,
  can_lock: false,
}
