import { encodeCursor } from '@modules/pagination'
import { pageInfo } from './data.mts'
import type { ApiFixtureCase } from './types.mts'
import {
  authorizedCard,
  authorizedId,
  cardCursorScope,
  cardMigratedFrom,
  cardTopic,
  primaryCard,
  primaryId,
  secondCard,
  secondTopicId,
} from './native-card-data.mts'

const consumers = ['web', 'swift-core', 'swift-ui', 'dotnet-core'] as const

export const nativeCardApiFixtureCases: ApiFixtureCase[] = [
  {
    id: 'native.card-topics.search.default',
    method: 'GET',
    path: '/api/v1/topics',
    route: { routeTemplate: '/api/v1/topics' },
    query: { q: 'Freedom', topic_types: 'card', limit: '10' },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [
        {
          __entity_type: 'topic',
          id: cardTopic.id,
          name: cardTopic.name,
          slug: cardTopic.slug,
          topic_type: cardTopic.topic_type,
        },
      ],
      page_info: pageInfo,
      topics: { [cardTopic.id]: cardTopic },
      topic_elections: {},
      election_votes: {},
      topics_metrics: {},
    },
    consumers: [...consumers],
    migratedFrom: cardMigratedFrom,
  },
  {
    id: 'native.cards.empty',
    method: 'GET',
    path: '/api/v1/my/cards',
    route: { routeTemplate: '/api/v1/my/cards' },
    query: { limit: '25' },
    auth: 'fixture-user',
    status: 200,
    body: { results: [], page_info: pageInfo },
    consumers: [...consumers],
    migratedFrom: cardMigratedFrom,
  },
  {
    id: 'native.cards.page-1',
    method: 'GET',
    path: '/api/v1/my/cards',
    route: { routeTemplate: '/api/v1/my/cards' },
    query: { limit: '2' },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [authorizedCard, secondCard],
      page_info: {
        has_next_page: true,
        start_cursor: encodeCursor({ id: authorizedCard.id, scope: cardCursorScope }),
        end_cursor: encodeCursor({ id: secondCard.id, scope: cardCursorScope }),
      },
    },
    consumers: [...consumers],
    migratedFrom: cardMigratedFrom,
  },
  {
    id: 'native.cards.page-2',
    method: 'GET',
    path: '/api/v1/my/cards',
    route: { routeTemplate: '/api/v1/my/cards' },
    query: {
      limit: '2',
      after: encodeCursor({ id: secondCard.id, scope: cardCursorScope }),
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [primaryCard],
      page_info: {
        has_next_page: false,
        start_cursor: encodeCursor({ id: primaryCard.id, scope: cardCursorScope }),
        end_cursor: null,
      },
    },
    consumers: [...consumers],
    migratedFrom: cardMigratedFrom,
  },
  {
    id: 'native.cards.create.default',
    method: 'POST',
    path: '/api/v1/my/cards',
    route: { routeTemplate: '/api/v1/my/cards' },
    requestBody: { card_id: secondTopicId },
    auth: 'fixture-user',
    status: 201,
    body: { card: secondCard },
    consumers: [...consumers],
    migratedFrom: cardMigratedFrom,
  },
  {
    id: 'native.cards.update.full',
    method: 'PATCH',
    path: `/api/v1/my/cards/${authorizedId}`,
    route: {
      routeTemplate: '/api/v1/my/cards/:id',
      pathParams: { id: authorizedId },
    },
    requestBody: {
      opened_on: authorizedCard.opened_on,
      closed_on: authorizedCard.closed_on,
      credit_limit: authorizedCard.credit_limit,
      received_sign_up_bonus_on: authorizedCard.received_sign_up_bonus_on,
      is_authorized_user: true,
      authorized_user_of_id: primaryId,
      note: authorizedCard.note,
    },
    auth: 'fixture-user',
    status: 200,
    body: { card: authorizedCard },
    consumers: [...consumers],
    migratedFrom: cardMigratedFrom,
  },
  {
    id: 'native.cards.update.clear',
    method: 'PATCH',
    path: `/api/v1/my/cards/${authorizedId}`,
    route: {
      routeTemplate: '/api/v1/my/cards/:id',
      pathParams: { id: authorizedId },
    },
    requestBody: {
      opened_on: null,
      closed_on: null,
      credit_limit: null,
      received_sign_up_bonus_on: null,
      is_authorized_user: false,
      authorized_user_of_id: null,
      note: null,
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      card: {
        ...authorizedCard,
        opened_on: null,
        credit_limit: null,
        is_authorized_user: false,
        authorized_user_of_id: null,
        note: null,
        authorized_user_of_card: null,
      },
    },
    consumers: [...consumers],
    migratedFrom: cardMigratedFrom,
  },
  {
    id: 'native.cards.delete.default',
    method: 'DELETE',
    path: `/api/v1/my/cards/${authorizedId}`,
    route: {
      routeTemplate: '/api/v1/my/cards/:id',
      pathParams: { id: authorizedId },
    },
    auth: 'fixture-user',
    status: 204,
    body: null,
    consumers: [...consumers],
    migratedFrom: cardMigratedFrom,
  },
]
