export const newExpectedParameters = {
  'GET:/api/v1/admin/warnings': ['after', 'limit', 'userId'],
  'GET:/api/v1/availability': ['kind', 'value'],
  'GET:/api/v1/appeals/:id': ['consistency'],
  'GET:/api/v1/communities': [
    'after',
    'eligible_post_type',
    'feed_category',
    'has_list_items',
    'has_list_type',
    'limit',
    'list_scope',
    'list_type',
    'member_id',
    'q',
    'sort',
    'topic',
  ],
  'GET:/api/v1/communities/:idOrSlug/applications': ['after', 'limit', 'status'],
  'GET:/api/v1/communities/:idOrSlug/automod/recent-actions': [
    'after',
    'agent',
    'content_type',
    'limit',
    'max_confidence',
    'post_type',
    'source',
    'window',
  ],
  'GET:/api/v1/communities/:idOrSlug/bans': ['after', 'limit'],
  'GET:/api/v1/communities/:idOrSlug/invites': ['after', 'limit'],
  'GET:/api/v1/communities/:idOrSlug/list-items/domains': ['after', 'limit'],
  'GET:/api/v1/communities/:idOrSlug/list-items/posts': ['after', 'limit'],
  'GET:/api/v1/communities/:idOrSlug/list-items/rss-feeds': ['after', 'limit'],
  'GET:/api/v1/communities/:idOrSlug/list-items/topics': ['after', 'limit'],
  'GET:/api/v1/communities/:idOrSlug/list-items/urls': ['after', 'limit'],
  'GET:/api/v1/communities/:idOrSlug/members': ['after', 'limit', 'role'],
  'GET:/api/v1/communities/:idOrSlug/moderation-analytics': ['range'],
  'GET:/api/v1/communities/:idOrSlug/moderation-queue': ['after', 'limit', 'source'],
  'GET:/api/v1/communities/:idOrSlug/moderator-stats': ['window'],
  'GET:/api/v1/communities/:idOrSlug/modlog': ['action_type', 'after', 'limit'],
  'GET:/api/v1/communities/:idOrSlug/news': [
    'after',
    'feed_type',
    'has_related_posts',
    'limit',
    'q',
    'time_range',
  ],
  'GET:/api/v1/communities/:idOrSlug/posts': ['after', 'limit', 'q', 'sort'],
  'GET:/api/v1/communities/:idOrSlug/posts/pending': ['after', 'limit'],
  'GET:/api/v1/communities/:idOrSlug/restrictions': ['after', 'limit'],
  'GET:/api/v1/copyright-notices/:id/eu-dispute-settlements': ['after', 'limit'],
  'GET:/api/v1/copyright-notices/:id/eu-dispute-settlements/staff': ['after', 'limit'],
  'GET:/api/v1/copyright-notices/:id/territorial-complaints': ['after', 'limit'],
  'GET:/api/v1/copyright-trusted-flaggers': ['after', 'limit'],
  'GET:/api/v1/crawlers': ['after', 'hostname_id', 'limit', 'referral_program_id'],
  'GET:/api/v1/curated-aside-items': ['type'],
  'GET:/api/v1/fediverse/instances': [
    'after',
    'integration_status',
    'limit',
    'open_registrations',
    'q',
    'software',
    'sort',
  ],
  'GET:/api/v1/hostnames/blocked': ['after', 'limit'],
  'GET:/api/v1/hostnames/compare': ['ids'],
  'GET:/api/v1/hostnames/social': ['after', 'limit'],
  'GET:/api/v1/hostnames/top': ['after', 'limit', 'topic'],
  'GET:/api/v1/lists/contains': ['entity_id', 'item_type'],
  'GET:/api/v1/localization': ['consumer', 'locales', 'selectors'],
  'GET:/api/v1/my/conversations': ['after', 'limit'],
  'GET:/api/v1/recommended-topics': [
    'after',
    'limit',
    'rss_feed',
    'sort',
    'spending_category',
    'topic_types',
  ],
  'GET:/api/v1/report-integrity/flags': ['after', 'limit', 'status'],
  'GET:/api/v1/report-integrity/penalties': [
    'after',
    'limit',
    'source_flag_id',
    'status',
    'user_id',
  ],
  'GET:/api/v1/search': ['limit', 'q'],
  'GET:/api/v1/topic-recommendations': ['after', 'limit', 'q', 'status'],
  'GET:/api/v1/topic-recommendations/duplicates': [
    'topic_aliases',
    'topic_markdown',
    'topic_slug',
    'topic_title',
  ],
  'GET:/api/v1/trending-communities': ['after', 'limit'],
  'GET:/api/v1/trending-posts': [
    'after',
    'limit',
    'min_score',
    'post_type',
    'time_range',
    'topic_id',
  ],
  'GET:/api/v1/trending-topics': ['after', 'limit', 'min_score', 'time_range'],
  'GET:/api/v1/urls': ['after', 'contentTypeId', 'hostnameId', 'limit', 'query'],
  'GET:/api/v1/vote-integrity/flags': ['after', 'limit', 'status'],
  'GET:/api/v1/vote-integrity/penalties': [
    'after',
    'limit',
    'source',
    'source_flag_id',
    'status',
    'user_id',
  ],
  'GET:/api/v1/web-search': ['limit', 'query'],
} as const
