export const newExpectedParameters = {
  'GET:/api/v1/admin/warnings': ['after', 'limit', 'userId'],
  'GET:/api/v1/availability': ['kind', 'value'],
  'GET:/api/v1/communities': [
    'after',
    'eligible_post_type',
    'feed_category',
    'has_list_items',
    'has_list_type',
    'limit',
    'list_scope',
    'list_type',
    'member_id',
    'q',
    'sort',
    'topic',
  ],
  'GET:/api/v1/crawlers': ['after', 'hostname_id', 'limit', 'referral_program_id'],
  'GET:/api/v1/curated-aside-items': ['type'],
  'GET:/api/v1/fediverse/instances': [
    'after',
    'integration_status',
    'limit',
    'open_registrations',
    'q',
    'software',
    'sort',
  ],
  'GET:/api/v1/hostnames/blocked': ['after', 'limit'],
  'GET:/api/v1/hostnames/compare': ['ids'],
  'GET:/api/v1/hostnames/social': ['after', 'limit'],
  'GET:/api/v1/hostnames/top': ['after', 'limit', 'topic'],
  'GET:/api/v1/lists/contains': ['entity_id', 'item_type'],
  'GET:/api/v1/localization': ['consumer', 'locales', 'selectors'],
  'GET:/api/v1/my/conversations': ['after', 'limit'],
  'GET:/api/v1/recommended-topics': [
    'after',
    'limit',
    'rss_feed',
    'sort',
    'spending_category',
    'topic_types',
  ],
  'GET:/api/v1/report-integrity/flags': ['after', 'limit', 'status'],
  'GET:/api/v1/report-integrity/penalties': [
    'after',
    'limit',
    'source_flag_id',
    'status',
    'user_id',
  ],
  'GET:/api/v1/search': ['limit', 'q'],
  'GET:/api/v1/topic-recommendations': ['after', 'limit', 'q', 'status'],
  'GET:/api/v1/topic-recommendations/duplicates': [
    'topic_aliases',
    'topic_markdown',
    'topic_slug',
    'topic_title',
  ],
  'GET:/api/v1/trending-communities': ['after', 'limit'],
  'GET:/api/v1/trending-posts': [
    'after',
    'limit',
    'min_score',
    'post_type',
    'time_range',
    'topic_id',
  ],
  'GET:/api/v1/trending-topics': ['after', 'limit', 'min_score', 'time_range'],
  'GET:/api/v1/urls': ['after', 'contentTypeId', 'hostnameId', 'limit', 'query'],
  'GET:/api/v1/vote-integrity/flags': ['after', 'limit', 'status'],
  'GET:/api/v1/vote-integrity/penalties': [
    'after',
    'limit',
    'source',
    'source_flag_id',
    'status',
    'user_id',
  ],
  'GET:/api/v1/web-search': ['limit', 'query'],
} as const
