import {
  community,
  pageInfo,
  post,
  rssFeed,
  rssFeedItem,
  timestamp,
  topic,
  user,
  notification,
} from './data.mts'
import { electionVotes, swiftRssFeedItemElection } from './election-data.mts'
import { storyId, swiftStoryClusterSidecars } from './story-cluster-data.mts'

export const swiftPost = {
  id: post.id,
  slug: 'fixture-post',
  post_type: 'discussion',
  title: post.title,
  markdown: post.markdown,
  html: null,
  parent_id: null,
  root_id: null,
  created_by_id: user.id,
  created_at: post.created_at,
  broadcast: null,
  privacy: 'public',
  is_anonymous: false,
  community_id: community.id,
  clearance_status: null,
  deleted_at: null,
  deleted_by_id: null,
  locked_at: null,
  locked_by_id: null,
  archived_at: null,
  archived_by_id: null,
  clearance_reason: null,
  clearance_updated_at: null,
  updated_by_id: null,
}

export const swiftNotification = {
  __entity_type: 'notification',
  id: notification.id,
  user_id: user.id,
  entity_type: 'post',
  post_id: post.id,
  rss_feed_item_id: null,
  actor_user_id: user.id,
  moderation_report_id: null,
  review_dispute_id: null,
  user_warning_id: null,
  copyright_notice_id: null,
  conversation_id: null,
  community_id: null,
  event_key: null,
  title: 'Fixture notification',
  body: 'A shared API fixture notification.',
  actor_label: null,
  target_path: `/discussion/${swiftPost.slug}`,
  target_entity: null,
  target_intent: null,
  read_at: null,
  pushed_at: null,
  created_at: notification.created_at,
  updated_at: notification.created_at,
}

export const friendUser = {
  __entity_type: 'user',
  id: 'friend-1',
  username: 'friend',
  display_account: { id: 'friend-account-1', name: 'Friendly User' },
  roles: [],
  profile_image_id: null,
  markdown: null,
}

export const swiftRssFeedSource = {
  __entity_type: rssFeed.__entity_type,
  id: rssFeed.id,
  title: rssFeed.title,
  is_enabled: rssFeed.is_enabled,
  is_discoverable: rssFeed.is_discoverable,
  etag: null,
  last_modified_at: null,
  last_fetched_at: rssFeed.last_fetched_at,
  feed_type: rssFeed.feed_type,
  publisher_type: rssFeed.publisher_type,
  rss_feed_url: {
    __entity_type: 'url',
    id: 'feed-url-1',
    hostname: {
      __entity_type: 'hostname',
      id: 'feed-hostname-1',
      hostname: 'example.com',
      topic_id: null,
      blocked: false,
      crawlable: true,
      skip_web_risk: false,
      link_rel_follow: true,
      votes_score_net: 0,
      votes_count_up: 0,
      votes_count_down: 0,
    },
    canonical_url_id: null,
    url: 'https://example.com/feed.xml',
    pathname: '/feed.xml',
    search_params: {},
  },
  home_page_url: null,
  hostname: null,
  topic: {
    ...topic,
    created_by: { ...topic.created_by, __entity_type: 'user' },
    updated_by: { ...topic.updated_by, __entity_type: 'user' },
  },
  podcast_show: null,
}

const swiftRssFeedItem = {
  id: rssFeedItem.id,
  rss_feed_id: rssFeed.id,
  title: 'Test Article',
  description: 'A short snippet',
  content: null,
  link: 'https://example.com/article',
  published_at: timestamp,
  creator: null,
  categories: rssFeedItem.categories,
  media_content: {
    url: 'https://example.com/video.mp4',
    type: 'video/mp4',
    medium: 'video',
    duration: null,
  },
}

export const swiftRssFeedItemsFeedBody = {
  results: [{ id: swiftRssFeedItem.id, story_id: storyId }],
  page_info: pageInfo,
  ...swiftStoryClusterSidecars(swiftRssFeedItem),
  rss_feed_item_elections: { [swiftRssFeedItem.id]: swiftRssFeedItemElection },
  election_votes: { [swiftRssFeedItem.id]: electionVotes[swiftRssFeedItem.id] },
}
