/* eslint-disable max-lines */
import { community, notification, pageInfo, post, user } from './data.mts'
import { electionVotes, postElection } from './election-data.mts'
import { rssFeedItemsFeedBody } from './rss-feed-items-data.mts'
import {
  swiftNotification,
  swiftPost,
  swiftRssFeedItemsFeedBody,
  swiftRssFeedSource,
} from './swift-data.mts'
import { swiftPodcastEpisodeChaptersBody, swiftPodcastEpisodeBody } from './swift-podcast-data.mts'
import { swiftUserApiFixtureCases } from './swift-user-cases.mts'
import { nativeFediverseApiFixtureCases } from './native-fediverse-cases.mts'
import { nativeBlueskyApiFixtureCases } from './native-bluesky-cases.mts'
import type { ApiFixtureCase } from './types.mts'

export const swiftApiFixtureCases: ApiFixtureCase[] = [
  ...nativeFediverseApiFixtureCases,
  ...nativeBlueskyApiFixtureCases,
  {
    id: 'swift.posts.feed.default',
    method: 'GET',
    path: '/api/v1/feeds/posts/any',
    query: { limit: '20', sort: 'hot' },
    route: {
      routeTemplate: '/api/v1/feeds/posts/:feed_type',
      pathParams: { feed_type: 'any' },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [{ entity_id: post.id }],
      page_info: pageInfo,
      posts: { [post.id]: swiftPost },
      users: { [user.id]: user },
      communities: { [community.id]: community },
      posts_metrics: {},
      post_elections: { [post.id]: postElection },
      election_votes: { [post.id]: electionVotes[post.id] },
    },
    consumers: ['swift-ui', 'dotnet-core'],
    migratedFrom: [
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/ui/Tests/VouchaUITests/VouchaUITests.swift',
    ],
  },
  {
    id: 'swift.notifications.default',
    method: 'GET',
    path: '/api/v1/my/notifications',
    query: { limit: '20' },
    route: { routeTemplate: '/api/v1/my/notifications' },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [
        { __entity_type: 'notification', id: notification.id, read_at: null },
        {
          __entity_type: 'notification',
          id: '00000000-0000-7000-8000-000000000101',
          read_at: null,
        },
        {
          __entity_type: 'notification',
          id: '00000000-0000-7000-8000-000000000102',
          read_at: null,
        },
      ],
      page_info: pageInfo,
      notifications: {
        [notification.id]: swiftNotification,
        '00000000-0000-7000-8000-000000000101': {
          ...swiftNotification,
          id: '00000000-0000-7000-8000-000000000101',
          entity_type: 'community_application_decision',
          community_id: community.id,
          target_path: null,
          target_entity: { __entity_type: 'community', id: community.id },
        },
        '00000000-0000-7000-8000-000000000102': {
          ...swiftNotification,
          id: '00000000-0000-7000-8000-000000000102',
          entity_type: 'community_activity_digest',
          target_path: null,
          target_intent: 'notifications_inbox',
        },
      },
      communities: {
        [community.id]: { id: community.id, slug: community.slug, name: community.name },
      },
    },
    consumers: ['swift-ui', 'dotnet-core'],
    migratedFrom: [
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/ui/Tests/VouchaUITests/VouchaUITests.swift',
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/ui/Tests/VouchaUITests/VouchaUIWriteTests.swift',
    ],
  },
  {
    id: 'native.notifications.redirect-target.default',
    method: 'GET',
    path: '/api/v1/my/notifications/notification-1/redirect-target',
    route: {
      routeTemplate: '/api/v1/my/notifications/:id/redirect-target',
      pathParams: { id: 'notification-1' },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      target_url: '/rss-feed-items/item-1',
    },
    consumers: ['swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  ...swiftUserApiFixtureCases,
  {
    id: 'native.my.email-addresses.empty',
    method: 'GET',
    path: '/api/v1/my/email-addresses',
    query: { limit: '1', after: 'fixture-owner-scoped-email-cursor' },
    route: { routeTemplate: '/api/v1/my/email-addresses' },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [],
      page_info: { has_next_page: false, start_cursor: null, end_cursor: null },
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  {
    id: 'native.my.email-addresses.request.default',
    method: 'POST',
    path: '/api/v1/my/email-addresses',
    route: { routeTemplate: '/api/v1/my/email-addresses' },
    auth: 'fixture-user',
    status: 200,
    requestBody: { email_address: ' Tests+Native-User@Voucha.ai ' },
    body: { email_address: 'tests+native-user@voucha.ai' },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  {
    id: 'native.my.email-addresses.verify.default',
    method: 'POST',
    path: '/api/v1/my/email-addresses/tests%2Bnative-user%40voucha.ai/verifications',
    route: {
      routeTemplate: '/api/v1/my/email-addresses/:email/verifications',
      pathParams: { email: 'tests+native-user@voucha.ai' },
    },
    auth: 'fixture-user',
    status: 200,
    requestBody: { token: 'ABCD1234' },
    body: {
      results: [
        {
          email_address: 'tests+native-user@voucha.ai',
          is_primary: true,
          created_at: '2026-07-11T12:00:00.000Z',
        },
      ],
      page_info: { has_next_page: false, start_cursor: null, end_cursor: null },
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  {
    id: 'native.my.email-preferences.default',
    method: 'GET',
    path: '/api/v1/my/email-preferences',
    route: { routeTemplate: '/api/v1/my/email-preferences' },
    auth: 'fixture-user',
    status: 200,
    body: {
      email_preferences: {
        engagement_emails_enabled: true,
        news_digest_frequency: 'weekly',
        moderation_emails_enabled: true,
        community_digest_frequency: 'weekly',
        moderation_email_cadence: 'daily',
        moderation_email_days_of_week: [1, 2, 3, 4, 5],
        moderation_email_time_of_day: '09:00',
        moderation_email_timezone: 'America/Los_Angeles',
      },
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  {
    id: 'swift.my.identity.default',
    method: 'GET',
    path: '/api/v1/my/identity',
    route: { routeTemplate: '/api/v1/my/identity' },
    auth: 'fixture-user',
    status: 200,
    backendResponseContractKey: 'GET:/api/v1/my/identity',
    body: {
      identity: {
        __entity_type: 'user',
        id: 'user-abc',
        username: 'alice',
        roles: ['user'],
        is_official_account: false,
        profile_image_id: null,
        markdown: null,
        email_address: 'tests+api-fixtures@voucha.ai',
        membership_plan: null,
        verification_status: null,
        suspended_at: null,
        cards_visibility: 'everyone',
        rewards_program_statuses_visibility: 'everyone',
        spending_categories_visibility: 'everyone',
        follows_visibility: 'everyone',
        topic_follows_visibility: 'everyone',
        rss_feed_follows_visibility: 'everyone',
        community_memberships_visibility: 'everyone',
        followers_visibility: 'everyone',
        likes_visibility: 'everyone',
        direct_messages_audience: 'users',
        default_post_broadcast: 'everyone',
        default_post_privacy: 'public',
        engagement_emails_enabled: true,
        news_digest_frequency: 'weekly',
        moderation_emails_enabled: true,
        community_digest_frequency: 'weekly',
        moderation_email_cadence: 'daily',
        moderation_email_days_of_week: [1, 2, 3, 4, 5],
        moderation_email_time_of_day: '09:00',
        moderation_email_timezone: 'America/Los_Angeles',
        fediverse_federation_enabled: false,
        bluesky_account: { did: 'did:plc:z72i7hdynmk6r22z27h6tvur', handle: 'alice.bsky.social' },
      },
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/core/Tests/VouchaCoreTests/VouchaCoreTests.swift',
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/ui/Tests/VouchaUITests/VouchaUITests.swift',
    ],
  },
  {
    id: 'native.identity-verification-attempts.grant.default',
    method: 'POST',
    path: '/api/v1/admin/users/00000000-0000-7000-8000-000000000003/identity-verification-attempts',
    route: {
      routeTemplate: '/api/v1/admin/users/:userId/identity-verification-attempts',
      pathParams: { userId: '00000000-0000-7000-8000-000000000003' },
    },
    auth: 'fixture-admin',
    status: 201,
    backendResponseContractKey: 'POST:/api/v1/admin/users/:userId/identity-verification-attempts',
    requestBody: { note: 'Provider terminal error reviewed by support.' },
    body: { granted: true },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/admin/identity-verification.mts'],
  },
  {
    id: 'native.auth.sessions.default',
    method: 'GET',
    path: '/api/v1/auth/sessions',
    query: { limit: '1', after: 'fixture-owner-scoped-session-cursor' },
    route: { routeTemplate: '/api/v1/auth/sessions' },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [
        {
          id: '0193f16e-0fd0-7c16-9d28-e340b9f3b36d',
          device_id: '0193f16e-19f1-7f32-bd1c-30d79ea27564',
          device_name: 'Mac',
          user_agent:
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Safari/605.1.15',
          ip_address: '203.0.113.10',
          created_at: '2026-07-06T12:00:00.000Z',
          last_seen_at: '2026-07-06T12:15:00.000Z',
          expires_at: '2026-07-08T12:15:00.000Z',
          is_current: true,
        },
        {
          id: '0193f16e-24ab-78fb-8f68-c9b2f99d864f',
          device_id: '0193f16e-2d8c-7659-8bb8-8b516d0d6f1c',
          device_name: 'iPhone',
          user_agent: 'Voucha/1 CFNetwork/1568.100.1 Darwin/24.0.0',
          ip_address: null,
          created_at: '2026-07-05T18:30:00.000Z',
          last_seen_at: '2026-07-06T11:45:00.000Z',
          expires_at: '2026-08-05T11:45:00.000Z',
          is_current: false,
        },
      ],
      page_info: pageInfo,
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  {
    id: 'swift.my.profile.default',
    method: 'GET',
    path: '/api/v1/my/profile',
    route: { routeTemplate: '/api/v1/my/profile' },
    auth: 'fixture-user',
    status: 200,
    body: {
      profile: {
        id: 'user-abc',
        markdown: 'Hello world',
      },
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/core/Tests/VouchaCoreTests/VouchaCoreTests.swift',
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/ui/Tests/VouchaUITests/VouchaUITests.swift',
    ],
  },
  {
    id: 'swift.rss-feeds.default',
    method: 'GET',
    path: '/api/v1/rss-feeds',
    query: { limit: '25' },
    route: { routeTemplate: '/api/v1/rss-feeds' },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [swiftRssFeedSource],
      page_info: pageInfo,
      bookmarks: {
        [swiftRssFeedSource.id]: {
          follow: true,
        },
      },
      topic_elections: {},
      hostname_elections: {},
    },
    consumers: ['swift-ui', 'dotnet-core'],
    migratedFrom: [
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/ui/Tests/VouchaUITests/VouchaUITests.swift',
    ],
  },
  {
    id: 'swift.rss-feed-items.feed.default',
    method: 'GET',
    path: '/api/v1/feeds/rss_feed_items/any',
    query: { limit: '20', media_type: 'video' },
    route: {
      routeTemplate: '/api/v1/feeds/rss_feed_items/:feed_type',
      pathParams: { feed_type: 'any' },
    },
    auth: 'fixture-user',
    status: 200,
    body: swiftRssFeedItemsFeedBody,
    consumers: ['swift-ui', 'dotnet-core'],
    migratedFrom: [
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/ui/Tests/VouchaUITests/VouchaUITests.swift',
    ],
  },
  {
    id: 'swift.integration.rss-feed-items.video',
    method: 'GET',
    path: '/api/v1/feeds/rss_feed_items/any',
    query: { limit: '20', media_type: 'video' },
    route: {
      routeTemplate: '/api/v1/feeds/rss_feed_items/:feed_type',
      pathParams: { feed_type: 'any' },
    },
    auth: 'fixture-user',
    status: 200,
    body: rssFeedItemsFeedBody,
    consumers: ['swift-core', 'dotnet-core'],
    migratedFrom: [
      'backend/scripts/tests/seed-swift-integration.mts',
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/core/Tests/VouchaIntegrationTests/VouchaIntegrationTests.swift',
    ],
  },
  {
    id: 'swift.integration.rss-feed-items.audio',
    method: 'GET',
    path: '/api/v1/feeds/rss_feed_items/any',
    query: { limit: '20', media_type: 'audio' },
    route: {
      routeTemplate: '/api/v1/feeds/rss_feed_items/:feed_type',
      pathParams: { feed_type: 'any' },
    },
    auth: 'fixture-user',
    status: 200,
    body: swiftPodcastEpisodeBody,
    consumers: ['swift-core', 'dotnet-core'],
    migratedFrom: [
      'backend/scripts/tests/seed-swift-integration.mts',
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/core/Tests/VouchaIntegrationTests/VouchaIntegrationTests.swift',
    ],
  },
  {
    id: 'swift.podcast-playback-position.default',
    method: 'GET',
    path: '/api/v1/podcast-episodes/episode-1/playback-position',
    route: {
      routeTemplate: '/api/v1/podcast-episodes/:id/playback-position',
      pathParams: { id: 'episode-1' },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      playback_position: {
        completed_at: null,
        position_seconds: 45.5,
      },
    },
    consumers: ['swift-core', 'dotnet-core'],
    migratedFrom: [
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/core/Tests/VouchaCoreTests/CoreModelDecodingTests.swift',
    ],
  },
  {
    id: 'swift.podcast-episode-chapters.default',
    method: 'GET',
    path: '/api/v1/podcast-episodes/episode-1/chapters',
    route: {
      routeTemplate: '/api/v1/podcast-episodes/:id/chapters',
      pathParams: { id: 'episode-1' },
    },
    auth: 'fixture-user',
    status: 200,
    body: swiftPodcastEpisodeChaptersBody,
    consumers: ['web', 'swift-core', 'dotnet-core'],
    migratedFrom: [],
  },
]
