import { pageInfo } from './data.mts'
import type { ApiFixtureCase } from './types.mts'

export const swiftIdentitySessionApiFixtureCases: ApiFixtureCase[] = [
  {
    id: 'swift.my.identity.default',
    method: 'GET',
    path: '/api/v1/my/identity',
    route: { routeTemplate: '/api/v1/my/identity' },
    auth: 'fixture-user',
    status: 200,
    backendResponseContractKey: 'GET:/api/v1/my/identity',
    body: {
      identity: {
        __entity_type: 'user',
        id: 'user-abc',
        username: 'alice',
        roles: ['user'],
        is_official_account: false,
        profile_image_id: null,
        markdown: null,
        email_address: 'tests+api-fixtures@voucha.ai',
        membership_plan: null,
        verification_status: null,
        suspended_at: null,
        cards_visibility: 'everyone',
        rewards_program_statuses_visibility: 'everyone',
        spending_categories_visibility: 'everyone',
        follows_visibility: 'everyone',
        topic_follows_visibility: 'everyone',
        rss_feed_follows_visibility: 'everyone',
        community_memberships_visibility: 'everyone',
        followers_visibility: 'everyone',
        likes_visibility: 'everyone',
        direct_messages_audience: 'users',
        default_post_broadcast: 'everyone',
        default_post_privacy: 'public',
        engagement_emails_enabled: true,
        news_digest_frequency: 'weekly',
        moderation_emails_enabled: true,
        community_digest_frequency: 'weekly',
        moderation_email_cadence: 'daily',
        moderation_email_days_of_week: [1, 2, 3, 4, 5],
        moderation_email_time_of_day: '09:00',
        moderation_email_timezone: 'America/Los_Angeles',
        fediverse_federation_enabled: false,
        bluesky_account: { did: 'did:plc:z72i7hdynmk6r22z27h6tvur', handle: 'alice.bsky.social' },
      },
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/core/Tests/VouchaCoreTests/VouchaCoreTests.swift',
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/ui/Tests/VouchaUITests/VouchaUITests.swift',
    ],
  },
  {
    id: 'native.identity-verification-attempts.grant.default',
    method: 'POST',
    path: '/api/v1/admin/users/00000000-0000-7000-8000-000000000003/identity-verification-attempts',
    route: {
      routeTemplate: '/api/v1/admin/users/:userId/identity-verification-attempts',
      pathParams: { userId: '00000000-0000-7000-8000-000000000003' },
    },
    auth: 'fixture-admin',
    status: 201,
    backendResponseContractKey: 'POST:/api/v1/admin/users/:userId/identity-verification-attempts',
    requestBody: { note: 'Provider terminal error reviewed by support.' },
    body: { granted: true },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/admin/identity-verification.mts'],
  },
  {
    id: 'native.auth.sessions.default',
    method: 'GET',
    path: '/api/v1/auth/sessions',
    query: { limit: '1', after: 'fixture-owner-scoped-session-cursor' },
    route: { routeTemplate: '/api/v1/auth/sessions' },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [
        {
          id: '0193f16e-0fd0-7c16-9d28-e340b9f3b36d',
          device_id: '0193f16e-19f1-7f32-bd1c-30d79ea27564',
          device_name: 'Mac',
          user_agent:
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Safari/605.1.15',
          ip_address: '203.0.113.10',
          created_at: '2026-07-06T12:00:00.000Z',
          last_seen_at: '2026-07-06T12:15:00.000Z',
          expires_at: '2026-07-08T12:15:00.000Z',
          is_current: true,
        },
        {
          id: '0193f16e-24ab-78fb-8f68-c9b2f99d864f',
          device_id: '0193f16e-2d8c-7659-8bb8-8b516d0d6f1c',
          device_name: 'iPhone',
          user_agent: 'Voucha/1 CFNetwork/1568.100.1 Darwin/24.0.0',
          ip_address: null,
          created_at: '2026-07-05T18:30:00.000Z',
          last_seen_at: '2026-07-06T11:45:00.000Z',
          expires_at: '2026-08-05T11:45:00.000Z',
          is_current: false,
        },
      ],
      page_info: pageInfo,
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [],
  },
  {
    id: 'swift.my.profile.default',
    method: 'GET',
    path: '/api/v1/my/profile',
    route: { routeTemplate: '/api/v1/my/profile' },
    auth: 'fixture-user',
    status: 200,
    body: {
      profile: {
        id: 'user-abc',
        markdown: 'Hello world',
      },
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: [
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/core/Tests/VouchaCoreTests/VouchaCoreTests.swift',
      'https://github.com/vouchington/vouchington-clients/blob/main/swift-clients/ui/Tests/VouchaUITests/VouchaUITests.swift',
    ],
  },
]
