import { community, communityPost, pageInfo, timestamp, user } from './web-community-data.mts'
import type { ApiFixtureCase } from './types.mts'

export const webCommunityModerationQueueApiFixtureCases: ApiFixtureCase[] = [
  {
    id: 'web.communities.modlog.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/modlog`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/modlog',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [{ __entity_type: 'moderator_action', id: 'modlog-1' }],
      page_info: pageInfo,
      moderator_actions: {
        'modlog-1': {
          id: 'modlog-1',
          community_id: community.id,
          actor_user_id: user.id,
          action_type: 'approve',
          post_id: communityPost.id,
          target_user_id: null,
          report_id: null,
          review_dispute_id: null,
          community_application_id: null,
          reason: 'Looks good.',
          metadata: {},
          created_at: timestamp,
        },
      },
      users: { [user.id]: user },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/modlog.mts'],
  },
  {
    id: 'web.communities.moderation-queue.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/moderation-queue`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/moderation-queue',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      entries: [
        {
          id: 'queue-1',
          case_id: 'case-1',
          entity_type: 'post',
          entity_id: communityPost.id,
          status: 'pending',
          queue_source: 'report',
          reason: 'spam',
          note: null,
          report_count: 1,
          created_at: timestamp,
          reviewed_at: null,
          target_available: true,
          target_label: communityPost.title,
          target_content: null,
          target_path: '/discussion/fixture-post',
          target_user_id: null,
          reporter_user_id: user.id,
          reporter_username: null,
          resolved_by_id: null,
          judgement: null,
          admin_action_path: null,
          community_ban_evasion: null,
          post_moderation_context: null,
          is_system_generated: false,
        },
      ],
      page_info: pageInfo,
      viewer_tier: 'moderator',
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/moderation-queue.mts'],
  },
]
