import { community, communityPost, pageInfo, timestamp, user } from './web-community-data.mts'
import type { ApiFixtureCase } from './types.mts'

const automodFlagPostId = '00000000-0000-7000-8000-000000000902'
const nextAutomodFlagPostId = '00000000-0000-7000-8000-000000000901'
const automodFlagCursor = Buffer.from(
  JSON.stringify({ created_at: '2026-01-01T00:00:00.000000Z', id: automodFlagPostId }),
).toString('base64url')

const automodFlagEntry = {
  id: automodFlagPostId,
  entity_type: 'post',
  entity_id: automodFlagPostId,
  status: 'pending',
  queue_source: 'automod_flag',
  reason: null,
  report_count: 0,
  created_at: timestamp,
  reviewed_at: null,
  target_available: true,
  target_label: 'Flagged post',
  target_content: {
    kind: 'post',
    text: 'Flagged post',
    declared_language: null,
    lingua_rs_detected_language: null,
  },
  target_path: '/discussion/flagged-post',
  target_user_id: user.id,
  resolved_by_id: null,
  judgement: null,
  admin_action_path: '/discussion/flagged-post',
  community_ban_evasion: null,
  post_moderation_context: null,
}

export const webCommunityModerationQueueApiFixtureCases: ApiFixtureCase[] = [
  {
    id: 'web.communities.modlog.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/modlog`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/modlog',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [{ __entity_type: 'moderator_action', id: 'modlog-1' }],
      page_info: pageInfo,
      moderator_actions: {
        'modlog-1': {
          id: 'modlog-1',
          community_id: community.id,
          actor_user_id: user.id,
          action_type: 'approve',
          post_id: communityPost.id,
          target_user_id: null,
          report_id: null,
          review_dispute_id: null,
          community_application_id: null,
          reason: 'Looks good.',
          metadata: {},
          created_at: timestamp,
        },
      },
      users: { [user.id]: user },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/modlog.mts'],
  },
  {
    id: 'web.communities.moderation-queue.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/moderation-queue`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/moderation-queue',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      entries: [
        {
          id: 'queue-1',
          case_id: 'case-1',
          entity_type: 'post',
          entity_id: communityPost.id,
          status: 'pending',
          queue_source: 'report',
          reason: 'spam',
          note: null,
          report_count: 1,
          created_at: timestamp,
          reviewed_at: null,
          target_available: true,
          target_label: communityPost.title,
          target_content: null,
          target_path: '/discussion/fixture-post',
          target_user_id: null,
          reporter_user_id: user.id,
          reporter_username: null,
          resolved_by_id: null,
          judgement: null,
          admin_action_path: null,
          community_ban_evasion: null,
          post_moderation_context: null,
          is_system_generated: false,
        },
      ],
      page_info: pageInfo,
      viewer_tier: 'moderator',
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/moderation-queue.mts'],
  },
  {
    id: 'native.communities.moderation-queue.automod-flag.page-1',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/moderation-queue`,
    query: { source: 'automod_flag', limit: '1' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/moderation-queue',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      entries: [automodFlagEntry],
      page_info: { has_next_page: true, start_cursor: null, end_cursor: automodFlagCursor },
      viewer_tier: 'moderator',
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/moderation-queue.mts'],
  },
  {
    id: 'native.communities.moderation-queue.automod-flag.page-2',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/moderation-queue`,
    query: { source: 'automod_flag', limit: '1', after: automodFlagCursor },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/moderation-queue',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      entries: [
        {
          ...automodFlagEntry,
          id: nextAutomodFlagPostId,
          entity_id: nextAutomodFlagPostId,
          target_label: 'Next flagged post',
          target_content: { ...automodFlagEntry.target_content, text: 'Next flagged post' },
          target_path: '/discussion/next-flagged-post',
          admin_action_path: '/discussion/next-flagged-post',
        },
      ],
      page_info: { has_next_page: false, start_cursor: null, end_cursor: null },
      viewer_tier: 'moderator',
    },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/moderation-queue.mts'],
  },
  {
    id: 'native.communities.moderation-queue.automod-flag.member',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/moderation-queue`,
    query: { source: 'automod_flag', limit: '1' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/moderation-queue',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: { entries: [], page_info: pageInfo, viewer_tier: 'member' },
    consumers: ['swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/moderation-queue.mts'],
  },
]
