/* eslint-disable max-lines */
import {
  archivedCommunity,
  community,
  communityAiAgent,
  communityDomainListItemPage,
  communityListItemsPostsBody,
  communityRssFeedListItemPage,
  communityTopicListItemPage,
  communityUrlListItemPage,
  communityMetrics,
  communityPost,
  communityPostsBody,
  communitySearchBody,
  pageInfo,
  rssFeed,
  topic,
  user,
} from './web-community-data.mts'
import { communityMember, communityOwner } from './web-community-member-data.mts'
import { communityHostname, communityUrl } from './web-community-url-data.mts'
import { storyMemberIds, storyPostIds, webStoryClusterRssFeedItems } from './story-cluster-data.mts'
import type { ApiFixtureCase } from './types.mts'

export const webCommunityApiFixtureCases: ApiFixtureCase[] = [
  {
    id: 'web.communities.search.default',
    method: 'GET',
    path: '/api/v1/communities',
    query: { q: 'test' },
    route: { routeTemplate: '/api/v1/communities' },
    auth: 'fixture-user',
    status: 200,
    body: communitySearchBody,
    consumers: ['web', 'dotnet-core'],
    migratedFrom: ['web/test-helpers/api-responses/communities.ts'],
  },
  {
    id: 'web.communities.show.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      community: {
        ...community,
        profile_image_id: 'community-profile-image-1',
        profile_image_placement: {
          placement_id: 'placement-community-profile-image-1',
          placement_revision: 2,
          image_id: 'community-profile-image-1',
        },
        banner_image_id: 'community-banner-image-1',
        banner_image_placement: {
          placement_id: 'placement-community-banner-image-1',
          placement_revision: 5,
          image_id: 'community-banner-image-1',
        },
      },
      user: communityOwner,
      membership: null,
      community_metrics: communityMetrics,
    },
    consumers: ['web', 'dotnet-core'],
    migratedFrom: ['web/test-helpers/api-responses/communities.ts'],
  },
  {
    id: 'web.communities.ai-agent.default',
    method: 'PUT',
    path: `/api/v1/communities/${community.slug}/ai-agents/self-promotion`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/ai-agents/:agentSlug',
      pathParams: { communitySlug: community.slug, agentSlug: 'self-promotion' },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      community_ai_agent: communityAiAgent,
    },
    consumers: ['web', 'dotnet-core'],
    migratedFrom: ['web/test-helpers/api-responses/communities.ts'],
  },
  {
    id: 'web.communities.archive.default',
    method: 'PATCH',
    path: `/api/v1/communities/${community.slug}`,
    requestBody: { archive: true },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: { community: archivedCommunity },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/community.mts'],
  },
  {
    id: 'web.communities.members.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/members`,
    query: { limit: '25' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/members',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [{ __entity_type: 'community_member', id: communityMember.id }],
      page_info: pageInfo,
      community_members: { [communityMember.id]: communityMember },
      users: { [user.id]: user },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/members.mts'],
  },
  {
    id: 'web.communities.posts.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/posts`,
    query: { limit: '25' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/posts',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: communityPostsBody,
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/posts.mts'],
  },
  {
    id: 'web.communities.news.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/news`,
    query: { limit: '25' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/news',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [],
      page_info: pageInfo,
      posts: {},
      posts_metrics: {},
      users: {},
      stories: {},
      story_member_ids: storyMemberIds,
      story_post_ids: storyPostIds,
      rss_feed_items: webStoryClusterRssFeedItems,
      rss_feed_item_elections: {},
      rss_feed_item_thumbnail_url: {},
      rss_feed_item_embeds: {},
      related_posts_by_url_id: {},
      election_votes: {},
      bookmarks: {},
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/news.mts'],
  },
  {
    id: 'web.communities.list-items.topics.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/list-items/topics`,
    query: { limit: '25' },
    route: {
      routeTemplate: '/api/v1/communities/:idOrSlug/list-items/topics',
      pathParams: { idOrSlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      ...communityTopicListItemPage,
      topics: { [topic.id]: topic },
      topics_metrics: {
        [topic.id]: {
          __entity_type: 'topic_metrics',
          id: topic.id,
          bookmarks: { follow: 0 },
          bookmarks__updated_at: '2026-01-01T00:00:00Z',
          count: {
            'data-points': 0,
            discussions: 0,
            latest: 0,
            news: 0,
            reviews: 0,
          },
          ratings: {
            count: {
              '1': 0,
              '2': 0,
              '3': 0,
              '4': 0,
              '5': 0,
            },
          },
          ratings__updated_at: '2026-01-01T00:00:00Z',
        },
      },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/list-items.mts'],
  },
  {
    id: 'web.communities.list-items.rss-feeds.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/list-items/rss-feeds`,
    query: { limit: '25' },
    route: {
      routeTemplate: '/api/v1/communities/:idOrSlug/list-items/rss-feeds',
      pathParams: { idOrSlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      ...communityRssFeedListItemPage,
      rss_feeds: {
        [rssFeed.id]: {
          ...rssFeed,
          etag: null,
          home_page_url: null,
          last_modified_at: null,
          rss_feed_url: {
            id: 'url-feed-1',
            url: 'https://example.com/feed.xml',
          },
        },
      },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/list-items.mts'],
  },
  {
    id: 'web.communities.list-items.posts.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/list-items/posts`,
    query: { limit: '25' },
    route: {
      routeTemplate: '/api/v1/communities/:idOrSlug/list-items/posts',
      pathParams: { idOrSlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: communityListItemsPostsBody,
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/list-items.mts'],
  },
  {
    id: 'web.communities.list-items.domains.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/list-items/domains`,
    query: { limit: '25' },
    route: {
      routeTemplate: '/api/v1/communities/:idOrSlug/list-items/domains',
      pathParams: { idOrSlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      ...communityDomainListItemPage,
      url_hostnames: { [communityHostname.id]: communityHostname },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/list-items.mts'],
  },
  {
    id: 'web.communities.list-items.urls.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/list-items/urls`,
    query: { limit: '25' },
    route: {
      routeTemplate: '/api/v1/communities/:idOrSlug/list-items/urls',
      pathParams: { idOrSlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: { ...communityUrlListItemPage, urls: { [communityUrl.id]: communityUrl } },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/list-items.mts'],
  },
  {
    id: 'web.communities.list-items.counts.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/list-items/counts`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/list-items/counts',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: { topic: 1, rss_feed: 1, post: 1, url: 1, url_hostname: 1 },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/list-items.mts'],
  },
  {
    id: 'web.communities.application-questions.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/application-questions`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/application-questions',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      questions: [
        {
          __entity_type: 'community_application_question',
          id: 'question-1',
          community_id: community.id,
          question: 'Why do you want to join?',
          field_type: 'long_text',
          required: true,
          options: null,
          order_index: 0,
          created_at: community.created_at,
          deleted_at: null,
        },
      ],
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/application-questions.mts'],
  },
  {
    id: 'web.communities.pinned-posts.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/pinned-posts`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/pinned-posts',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      pinned_posts: [
        {
          __entity_type: 'community_pinned_post',
          community_id: community.id,
          post_id: communityPost.id,
          order_index: 0,
          pinned_by_id: user.id,
          created_at: community.created_at,
        },
      ],
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/pinned-posts.mts'],
  },
]
