/* eslint-disable max-lines */
import {
  community,
  communityAiAgent,
  communityPost,
  pageInfo,
  timestamp,
  user,
} from './web-community-data.mts'
import type { ApiFixtureCase } from './types.mts'

export const webCommunityModerationApiFixtureCases: ApiFixtureCase[] = [
  {
    id: 'web.communities.applications.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/applications`,
    query: { limit: '25' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/applications',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: { results: [], page_info: pageInfo, community_applications: {} },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/applications.mts'],
  },
  {
    id: 'web.communities.invites.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/invites`,
    query: { limit: '25' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/invites',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: { results: [], page_info: pageInfo, community_invites: {} },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/invites.mts'],
  },
  {
    id: 'web.communities.bans.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/bans`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/bans',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: { results: [], page_info: pageInfo, community_bans: {}, users: {} },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/bans.mts'],
  },
  {
    id: 'web.communities.restrictions.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/restrictions`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/restrictions',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [],
      page_info: pageInfo,
      community_restrictions: {},
      raid_mode_suggestion: {
        velocity_spike: false,
        flag_count: 0,
        latest_flagged_at: null,
      },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/restrictions.mts'],
  },
  {
    id: 'web.communities.modmail.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/modmail`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/modmail',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: { results: [], page_info: pageInfo },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/modmail.mts'],
  },
  {
    id: 'web.communities.modmail-messages.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/modmail/00000000-0000-7000-8000-000000000501/messages`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/modmail/:threadId/messages',
      pathParams: {
        communitySlug: community.slug,
        threadId: '00000000-0000-7000-8000-000000000501',
      },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [
        {
          id: '00000000-0000-7000-8000-000000000602',
          conversation_id: '00000000-0000-7000-8000-000000000501',
          body_text: 'Please review this moderation thread.',
          created_by_id: user.id,
          sender_username: user.username,
          created_at: timestamp,
          updated_at: timestamp,
          deleted_at: null,
        },
      ],
      page_info: {
        ...pageInfo,
        start_cursor: 'eyJpZCI6IjAwMDAwMDAwLTAwMDAtNzAwMC04MDAwLTAwMDAwMDAwMDYwMiJ9',
      },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/modmail.mts'],
  },
  {
    id: 'web.communities.modmail.page-2',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/modmail`,
    query: {
      after:
        'eyJ0aW1lc3RhbXAiOiIyMDI2LTA3LTAxVDEyOjAwOjAwLjAwMDAwMFoiLCJpZCI6IjAwMDAwMDAwLTAwMDAtNzAwMC04MDAwLTAwMDAwMDAwMDUwMSJ9',
      limit: '25',
    },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/modmail',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [
        {
          id: '00000000-0000-7000-8000-000000000502',
          channel_type: 'modmail',
          title: '',
          community_id: community.id,
          subject_user_id: user.id,
          assigned_mod_id: null,
          assigned_at: null,
          resolved_at: null,
          resolved_by_id: null,
          created_by_id: user.id,
          created_at: timestamp,
          updated_at: timestamp,
        },
      ],
      page_info: {
        ...pageInfo,
        start_cursor:
          'eyJ0aW1lc3RhbXAiOiIyMDI2LTAxLTAxVDAwOjAwOjAwLjAwMDAwMFoiLCJpZCI6IjAwMDAwMDAwLTAwMDAtNzAwMC04MDAwLTAwMDAwMDAwMDUwMiJ9',
      },
    },
    consumers: ['swift-core', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/modmail.mts'],
  },
  {
    id: 'web.communities.modmail-messages.page-2',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/modmail/00000000-0000-7000-8000-000000000501/messages`,
    query: {
      after: 'eyJpZCI6IjAwMDAwMDAwLTAwMDAtNzAwMC04MDAwLTAwMDAwMDAwMDYwMSJ9',
      limit: '25',
    },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/modmail/:threadId/messages',
      pathParams: {
        communitySlug: community.slug,
        threadId: '00000000-0000-7000-8000-000000000501',
      },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [
        {
          id: '00000000-0000-7000-8000-000000000600',
          conversation_id: '00000000-0000-7000-8000-000000000501',
          body_text: 'Earlier modmail context.',
          created_by_id: user.id,
          sender_username: user.username,
          created_at: timestamp,
          updated_at: timestamp,
          deleted_at: null,
        },
      ],
      page_info: {
        ...pageInfo,
        start_cursor: 'eyJpZCI6IjAwMDAwMDAwLTAwMDAtNzAwMC04MDAwLTAwMDAwMDAwMDYwMCJ9',
      },
    },
    consumers: ['swift-core', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/modmail-messages.mts'],
  },
  {
    id: 'web.communities.saved-replies.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/saved-replies`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/saved-replies',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [
        {
          id: '00000000-0000-7000-8000-000000000700',
          community_id: community.id,
          title: 'Greeting',
          body: 'Thanks for writing in.',
          order_index: 0,
          created_by_id: user.id,
          created_at: timestamp,
          updated_at: timestamp,
          deleted_at: null,
        },
      ],
      page_info: {
        ...pageInfo,
        start_cursor:
          'eyJyYW5raW5nIjowLCJpZCI6IjAwMDAwMDAwLTAwMDAtNzAwMC04MDAwLTAwMDAwMDAwMDcwMCJ9',
      },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/saved-replies.mts'],
  },
  {
    id: 'web.communities.saved-reply.create.default',
    method: 'POST',
    path: `/api/v1/communities/${community.slug}/saved-replies`,
    requestBody: { title: 'Greeting', body: 'Thanks for writing in.' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/saved-replies',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 201,
    body: {
      reply: {
        id: '00000000-0000-7000-8000-000000000700',
        community_id: community.id,
        title: 'Greeting',
        body: 'Thanks for writing in.',
        order_index: 0,
        created_by_id: user.id,
        created_at: timestamp,
        updated_at: timestamp,
        deleted_at: null,
      },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/saved-replies.mts'],
  },
  {
    id: 'web.communities.saved-replies.page-2',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/saved-replies`,
    query: {
      after: 'eyJyYW5raW5nIjowLCJpZCI6IjAwMDAwMDAwLTAwMDAtNzAwMC04MDAwLTAwMDAwMDAwMDcwMSJ9',
      limit: '25',
    },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/saved-replies',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [
        {
          id: '00000000-0000-7000-8000-000000000702',
          community_id: community.id,
          title: 'Follow-up',
          body: 'Here is the earlier saved reply.',
          order_index: 1,
          created_by_id: user.id,
          created_at: timestamp,
          updated_at: timestamp,
          deleted_at: null,
        },
      ],
      page_info: {
        ...pageInfo,
        start_cursor:
          'eyJyYW5raW5nIjoxLCJpZCI6IjAwMDAwMDAwLTAwMDAtNzAwMC04MDAwLTAwMDAwMDAwMDcwMiJ9',
      },
    },
    consumers: ['swift-core', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/saved-replies.mts'],
  },
  {
    id: 'web.communities.modlog.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/modlog`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/modlog',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      results: [{ __entity_type: 'moderator_action', id: 'modlog-1' }],
      page_info: pageInfo,
      moderator_actions: {
        'modlog-1': {
          id: 'modlog-1',
          community_id: community.id,
          actor_id: user.id,
          action_type: 'approve',
          post_id: communityPost.id,
          target_user_id: null,
          report_id: null,
          review_dispute_id: null,
          community_application_id: null,
          reason: 'Looks good.',
          metadata: {},
          created_at: timestamp,
        },
      },
      users: { [user.id]: user },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/modlog.mts'],
  },
  {
    id: 'web.communities.moderation-queue.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/moderation-queue`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/moderation-queue',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      entries: [
        {
          id: 'queue-1',
          case_id: 'case-1',
          entity_type: 'post',
          entity_id: communityPost.id,
          status: 'pending',
          queue_source: 'report',
          reason: 'spam',
          note: null,
          report_count: 1,
          created_at: timestamp,
          reviewed_at: null,
          target_available: true,
          target_label: communityPost.title,
          target_content: null,
          target_path: '/discussion/fixture-post',
          target_user_id: null,
          reporter_user_id: user.id,
          reporter_username: null,
          resolved_by_id: null,
          judgement: null,
          admin_action_path: null,
          community_ban_evasion: null,
          post_moderation_context: null,
          is_system_generated: false,
        },
      ],
      page_info: pageInfo,
      viewer_tier: 'moderator',
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/moderation-queue.mts'],
  },
  {
    id: 'web.communities.moderation-analytics.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/moderation-analytics`,
    query: { range: '30d' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/moderation-analytics',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      scope: { type: 'community', community_id: community.id },
      range: '30d',
      period_start: '2026-01-01T00:00:00Z',
      period_end: '2026-01-31T00:00:00Z',
      queue_volume: {
        total_reports: 0,
        pending_reports: 0,
        reports_over_time: [],
        clearance_actions_over_time: [],
        moderator_actions_over_time: [],
      },
      rule_violations: { reasons: [], reasons_over_time: [] },
      appeals: {
        total_closed: 0,
        accepted: 0,
        reduced: 0,
        denied: 0,
        dismissed: 0,
        success_rate: null,
      },
      moderator_workload: { moderators: [], users: {} },
      automod_performance: {
        total_actions: 0,
        auto_removes: 0,
        reviewed_count: 0,
        false_positive_count: 0,
        false_positive_rate: null,
        actions_over_time: [],
        confidence_distribution: [],
        sources: [],
      },
      new_user_friction: { first_posts: 0, rejected_first_posts: 0, rejection_rate: null },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/moderation-analytics.mts'],
  },
  {
    id: 'web.communities.moderator-stats.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/moderator-stats`,
    query: { window: '30' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/moderator-stats',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      window: 30,
      stats: [{ actor_id: user.id, total: 3, counts: { approve: 2, remove: 1 } }],
      users: { [user.id]: user },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/moderator-stats.mts'],
  },
  {
    id: 'web.communities.moderator-vacation.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/moderator-vacation`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/moderator-vacation',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      suppress_community_digests_while_on_vacation: false,
      vacation: {
        community_id: community.id,
        user_id: user.id,
        starts_at: timestamp,
        ends_at: null,
        created_at: timestamp,
        updated_at: timestamp,
      },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/moderator-vacation.mts'],
  },
  {
    id: 'web.communities.ai-agents.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/ai-agents`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/ai-agents',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: { community_ai_agents: [communityAiAgent] },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/ai-agents.mts'],
  },
  {
    id: 'web.communities.agent-prompts.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/agent-prompts`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/agent-prompts',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      community_agent_prompts: [
        {
          id: 'prompt-1',
          community_id: community.id,
          created_by_id: 'user-1',
          slot_allocated: true,
          on_flag_action: 'none',
          activated_at: timestamp,
          deactivated_at: null,
          deleted_at: null,
          deleted_by_id: null,
          agent_id: 'agent-1',
          prompt: 'Welcome new members.',
          model_name: 'gpt-5.4-nano',
          model_provider: 'openai',
          created_at: timestamp,
          updated_at: timestamp,
        },
      ],
      slot_info: {
        limit: 3,
        limits_by_plan: { plus: 3, pro: 10 },
        remaining: 2,
        used: 1,
      },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/agent-prompts.mts'],
  },
  {
    id: 'web.communities.agent-prompts.history.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/agent-prompts/history`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/agent-prompts/history',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      entries: [
        {
          id: 'prompt-history-1',
          community_id: community.id,
          agent_prompt_id: 'prompt-1',
          action: 'created',
          changed_by: { id: user.id, username: user.username },
          previous_fields: {},
          next_fields: { prompt: 'Welcome new members.' },
          changed_fields: {},
          created_at: timestamp,
        },
      ],
      next_cursor: null,
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/agent-prompts-history.mts'],
  },
  {
    id: 'web.communities.automod-simulate.default',
    method: 'POST',
    path: `/api/v1/communities/${community.slug}/automod/simulate`,
    requestBody: { prompt_id: 'prompt-1' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/automod/simulate',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      simulation: {
        prompt_id: 'prompt-1',
        time_window_hours: 24,
        sample_count: 0,
        would_flag_count: 0,
        would_unpublish_count: 0,
        false_positive_estimate: null,
      },
      results: [],
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/automod.mts'],
  },
  {
    id: 'web.communities.automod-recent-actions.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/automod/recent-actions`,
    query: { window: '24h', limit: '25', source: 'agent_moderation' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/automod/recent-actions',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      automod_actions: [
        {
          source_key: 'agent_moderation:post-1',
          source_type: 'agent_moderation',
          post_id: communityPost.id,
          community_id: community.id,
          agent_moderation_id: 'agent-moderation-1',
          moderator_slug: communityAiAgent.slug,
          title: communityPost.title,
          authored_title: communityPost.title,
          declared_language: null,
          lingua_rs_detected_language: null,
          markdown_preview: 'Hello from the community.',
          post_type: communityPost.post_type,
          post_href: `/discussion/${communityPost.slug}`,
          created_at: timestamp,
          action_at: timestamp,
          confidence_score: 0.82,
          flagged: true,
          reason: 'Low quality',
          categories: ['quality'],
          model_output: { flagged: true, reason: 'Low quality', confidence_score: 0.82 },
          current_state: 'rejected',
          feedback_label: null,
        },
      ],
      stats: {
        total_count: 1,
        false_positive_count: 0,
        false_positive_rate: 0,
      },
      page_info: { has_next_page: false, end_cursor: null },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/automod-recent-actions.mts'],
  },
  {
    id: 'web.communities.automod-feedback.create.default',
    method: 'POST',
    path: `/api/v1/communities/${community.slug}/automod/recent-actions/agent_moderation%3Apost-1/feedback`,
    requestBody: {
      outcome: 'true_positive',
      action: 'keep_removed',
      reason_code: 'correct',
      note: 'Matches the community rules.',
    },
    route: {
      routeTemplate:
        '/api/v1/communities/:communitySlug/automod/recent-actions/:sourceKey/feedback',
      pathParams: { communitySlug: community.slug, sourceKey: 'agent_moderation:post-1' },
    },
    auth: 'fixture-user',
    status: 201,
    body: {
      feedback: {
        id: 'automod-feedback-1',
        source_type: 'agent_moderation',
        event_type: 'automod_reviewed',
        label: 'true_positive',
        human_action: 'keep_removed',
        reason_code: 'correct',
        note: 'Matches the community rules.',
        label_confidence: 1,
        actor_user_id: user.id,
        community_id: community.id,
        post_id: communityPost.id,
        agent_moderation_id: 'agent-moderation-1',
        moderation_report_id: null,
        moderation_appeal_id: null,
        review_dispute_id: null,
        post_clearance_change_id: null,
        input_sha256: null,
        metadata: {
          source_key: 'agent_moderation:post-1',
          outcome: 'true_positive',
          source_type: 'agent_moderation',
        },
        applied_action: true,
        created_at: timestamp,
        updated_at: timestamp,
      },
      applied_action: true,
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/automod-recent-actions.mts'],
  },
  {
    id: 'web.communities.moderation-results.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/posts/${communityPost.id}/moderation-results`,
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/posts/:postId/moderation-results',
      pathParams: { communitySlug: community.slug, postId: communityPost.id },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      community_agent_moderations: [],
      platform_moderation: { status: 'in_review' },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/moderation-results.mts'],
  },
  {
    id: 'web.communities.warning.create.default',
    method: 'POST',
    path: `/api/v1/communities/${community.slug}/warnings`,
    requestBody: {
      userId: user.id,
      reason: 'Spam in community',
      publicMessage: 'Please read the community rules.',
      resolveReport: false,
    },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/warnings',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 201,
    body: {
      warning: {
        id: 'warning-1',
        issued_by_id: user.id,
        community_id: community.id,
        reason: 'Spam in community',
        public_message: 'Please read the community rules.',
        report_id: null,
        revoked_at: null,
        revoked_by_id: null,
        created_at: timestamp,
      },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/warnings.mts'],
  },
  {
    id: 'web.communities.post-type-settings.update.default',
    method: 'PATCH',
    path: `/api/v1/communities/${community.slug}/post-type-settings`,
    requestBody: { allow_review_posts: true, allow_data_point_posts: true },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/post-type-settings',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      community: {
        ...community,
        allow_review_posts: true,
        allow_data_point_posts: true,
      },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/post-type-settings.mts'],
  },
]
