import {
  community,
  communityAiAgent,
  communityPost,
  timestamp,
  user,
} from './web-community-data.mts'
import type { ApiFixtureCase } from './types.mts'

export const webCommunityAutomodApiFixtureCases: ApiFixtureCase[] = [
  {
    id: 'web.communities.automod-simulate.default',
    method: 'POST',
    path: `/api/v1/communities/${community.slug}/automod/simulate`,
    requestBody: { prompt_id: 'prompt-1' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/automod/simulate',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      simulation: {
        prompt_id: 'prompt-1',
        time_window_hours: 24,
        sample_count: 0,
        would_flag_count: 0,
        community_automod_action: 'record_only',
        false_positive_estimate: null,
      },
      results: [],
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/automod.mts'],
  },
  {
    id: 'web.communities.automod-settings.update.default',
    method: 'PATCH',
    path: `/api/v1/communities/${community.slug}/automod-settings`,
    requestBody: { automod_action: 'review_queue' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/automod-settings',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: { community: { ...community, automod_action: 'review_queue' } },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/automod-settings.mts'],
  },
  {
    id: 'web.communities.automod-recent-actions.default',
    method: 'GET',
    path: `/api/v1/communities/${community.slug}/automod/recent-actions`,
    query: { window: '24h', limit: '25', source: 'agent_moderation' },
    route: {
      routeTemplate: '/api/v1/communities/:communitySlug/automod/recent-actions',
      pathParams: { communitySlug: community.slug },
    },
    auth: 'fixture-user',
    status: 200,
    body: {
      automod_actions: [
        {
          source_key: 'agent_moderation:post-1',
          source_type: 'agent_moderation',
          post_id: communityPost.id,
          community_id: community.id,
          agent_moderation_id: 'agent-moderation-1',
          moderator_slug: communityAiAgent.slug,
          title: communityPost.title,
          authored_title: communityPost.title,
          declared_language: null,
          lingua_rs_detected_language: null,
          markdown_preview: 'Hello from the community.',
          post_type: communityPost.post_type,
          post_href: `/discussion/${communityPost.slug}`,
          created_at: timestamp,
          action_at: timestamp,
          confidence_score: 0.82,
          is_flagged: true,
          categories: ['quality'],
          model_output: { flagged: true, confidence_score: 0.82 },
          current_state: 'rejected',
          feedback_label: null,
        },
      ],
      stats: {
        total_count: 1,
        false_positive_count: 0,
        false_positive_rate: 0,
      },
      page_info: { has_next_page: false, end_cursor: null },
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/automod-recent-actions.mts'],
  },
  {
    id: 'web.communities.automod-feedback.create.default',
    method: 'POST',
    path: `/api/v1/communities/${community.slug}/automod/recent-actions/agent_moderation%3Apost-1/feedback`,
    requestBody: {
      outcome: 'true_positive',
      action: 'keep_removed',
      reason_code: 'correct',
      note: 'Matches the community rules.',
    },
    route: {
      routeTemplate:
        '/api/v1/communities/:communitySlug/automod/recent-actions/:sourceKey/feedback',
      pathParams: { communitySlug: community.slug, sourceKey: 'agent_moderation:post-1' },
    },
    auth: 'fixture-user',
    status: 201,
    body: {
      feedback: {
        id: 'automod-feedback-1',
        source_type: 'agent_moderation',
        event_type: 'automod_reviewed',
        label: 'true_positive',
        human_action: 'keep_removed',
        reason_code: 'correct',
        note: 'Matches the community rules.',
        label_confidence: 1,
        actor_user_id: user.id,
        community_id: community.id,
        post_id: communityPost.id,
        agent_moderation_id: 'agent-moderation-1',
        moderation_report_id: null,
        moderation_appeal_id: null,
        review_dispute_id: null,
        post_clearance_change_id: null,
        input_sha256: null,
        metadata: {
          source_key: 'agent_moderation:post-1',
          outcome: 'true_positive',
          source_type: 'agent_moderation',
        },
        applied_action: true,
        created_at: timestamp,
        updated_at: timestamp,
      },
      applied_action: true,
    },
    consumers: ['web', 'swift-core', 'swift-ui', 'dotnet-core'],
    migratedFrom: ['backend/api/v1/communities/automod-recent-actions.mts'],
  },
]
