// Reviewed storage-column contracts for the prelaunch finite-value conversion.
export const FINITE_COLUMN_CONTRACTS_6 = [
  ['oauth_refresh_tokens', 'scopes', 'api_scopes', true],
  [
    'post_admission_quota_consumptions',
    'consumption_mode',
    'post_admission_quota_consumption_modes',
    false,
  ],
  ['post_admission_quota_consumptions', 'source', 'contribution_policy_sources', false],
  ['post_admission_reservations', 'committed_status', 'post_admission_committed_statuses', false],
  ['post_admission_reservations', 'post_type', 'post_types', false],
  ['post_admission_reservations', 'route', 'post_admission_routes', false],
  ['post_admission_reservations', 'scope', 'post_admission_scope_categories', false],
  ['post_admission_reservations', 'source', 'contribution_policy_sources', false],
  ['post_admission_reservations', 'state', 'post_admission_reservation_states', false],
  [
    'post_classifier_local_outcomes',
    'classification',
    'post_classifier_local_outcome_classifications',
    false,
  ],
  [
    'post_clearance_changes',
    'moderation_transparency_categories',
    'moderation_transparency_categories',
    true,
  ],
  ['post_publication_dirty_work', 'reasons', 'post_publication_reasons', true],
  ['post_publication_dirty_work_keys', 'post_type', 'post_types', false],
  [
    'post_publication_identity_bridge_cleanup_progress',
    'family',
    'post_publication_identity_bridge_cleanup_families',
    false,
  ],
  ['post_publication_identity_snapshot_keys', 'post_type', 'post_types', false],
  [
    'post_publication_identity_snapshots',
    'receipt_cursor_kind',
    'post_publication_receipt_cursor_kinds',
    false,
  ],
  [
    'post_publication_identity_snapshots',
    'source_cursor_kind',
    'post_publication_source_cursor_kinds',
    false,
  ],
  ['post_revisions', 'revision_type', 'revision_types', false],
  ['post_topic_alias_sources', 'source', 'post_topic_alias_source_types', false],
  ['posts', 'post_type', 'post_types', false],
  ['posts', 'privacy', 'privacy_types', false],
  ['retained_identity_cleanup_progress', 'family', 'retained_identity_cleanup_families', false],
  ['retained_image_placement_bindings', 'binding_family', 'image_binding_families', false],
  ['review_disputes', 'reason', 'review_dispute_reasons', false],
  ['review_disputes', 'recommended_action', 'review_dispute_actions', false],
] as const
