// Reviewed storage-column contracts for the prelaunch finite-value conversion.
export const FINITE_COLUMN_CONTRACTS_1 = [
  ['admin_import_batches', 'import_type', 'import_entity_types', false],
  [
    'agent_moderations',
    'moderation_transparency_category',
    'moderation_transparency_categories',
    false,
  ],
  ['ai_usage_records', 'pricing_status', 'ai_usage_record_pricing_statuses', false],
  ['activitypub_inbox_deliveries', 'request_method', 'http_request_methods', false],
  ['api_keys', 'scopes', 'api_scopes', true],
  ['bluesky_link_authorizations', 'callback_mode', 'oauth_callback_modes', false],
  ['bluesky_link_authorizations', 'status', 'bluesky_link_authorization_statuses', false],
  ['classifier_candidates', 'candidate_kind', 'classifier_candidate_kinds', false],
  ['classifier_decision_batches', 'scope_category', 'classifier_scope_categories', false],
  ['classifier_prompt_versions', 'model_provider', 'classifier_model_providers', false],
  ['classifier_runs', 'terminal_failure_kind', 'classifier_run_terminal_failure_kinds', false],
  ['classifiers', 'candidate_kind', 'classifier_candidate_kinds', false],
  ['classifiers', 'primitive', 'classifier_primitives', false],
  ['communities', 'automod_action', 'community_automod_actions', false],
  ['communities', 'visibility', 'privacy_types', false],
  ['community_post_reviews', 'automod_action', 'community_automod_actions', false],
  [
    'community_post_reviews',
    'platform_override_action',
    'community_post_review_platform_override_actions',
    false,
  ],
  ['community_prompt_classifier_results', 'candidate_kind', 'classifier_candidate_kinds', false],
  ['community_prompt_classifier_results', 'scope_category', 'classifier_scope_categories', false],
  [
    'copyright_automatic_withholding_refusals',
    'reason',
    'copyright_automatic_withholding_refusal_reasons',
    false,
  ],
  [
    'copyright_claimant_misuse_events',
    'outcome',
    'copyright_claimant_misuse_event_outcomes',
    false,
  ],
  [
    'copyright_eu_dispute_settlement_outcomes',
    'result',
    'copyright_eu_dispute_settlement_results',
    false,
  ],
  ['copyright_eu_dispute_settlement_referrals', 'jurisdiction', 'copyright_jurisdictions', false],
  [
    'copyright_eu_dispute_settlement_referrals',
    'referred_by_party',
    'copyright_territorial_party_roles',
    false,
  ],
  ['copyright_eu_supervised_complaints', 'jurisdiction', 'copyright_jurisdictions', false],
] as const
