// Reviewed storage-column contracts for the prelaunch finite-value conversion.
export const FINITE_COLUMN_CONTRACTS_2 = [
  ['copyright_eu_transparency_reports', 'jurisdiction', 'copyright_jurisdictions', false],
  ['copyright_jurisdiction_policy_approvals', 'jurisdiction', 'copyright_jurisdictions', false],
  ['copyright_notice_action_intents', 'action', 'copyright_notice_action_intent_actions', false],
  [
    'copyright_notice_action_intents',
    'completed_at_reason',
    'copyright_notice_action_intent_states',
    false,
  ],
  ['copyright_notice_action_intents', 'state', 'copyright_notice_action_intent_states', false],
  [
    'copyright_notice_appeal_recommendations',
    'recommendation',
    'copyright_notice_appeal_recommendation_outcomes',
    false,
  ],
  ['copyright_notice_appeal_reviews', 'action', 'copyright_review_actions', false],
  [
    'copyright_notice_correspondence_messages',
    'composition_kind',
    'copyright_notice_correspondence_message_composition_kinds',
    false,
  ],
  [
    'copyright_notice_correspondence_messages',
    'correspondence_kind',
    'copyright_notice_correspondence_kinds',
    false,
  ],
  [
    'copyright_notice_correspondence_messages',
    'direction',
    'copyright_notice_correspondence_message_directions',
    false,
  ],
  [
    'copyright_notice_delivery_intents',
    'channel',
    'copyright_notice_delivery_intent_channels',
    false,
  ],
  ['copyright_notice_delivery_intents', 'delivery_kind', 'copyright_notice_delivery_kinds', false],
  [
    'copyright_notice_delivery_intents',
    'recipient_role',
    'copyright_notice_delivery_intent_recipient_roles',
    false,
  ],
  ['copyright_notice_delivery_intents', 'state', 'copyright_notice_delivery_intent_states', false],
  [
    'copyright_notice_email_correspondence_reviews',
    'action',
    'copyright_notice_email_correspondence_review_actions',
    false,
  ],
  [
    'copyright_notice_email_correspondence_reviews',
    'kind',
    'copyright_notice_email_correspondence_review_kinds',
    false,
  ],
  [
    'copyright_notice_email_intake_notice_links',
    'link_kind',
    'copyright_notice_email_intake_link_kinds',
    false,
  ],
  [
    'copyright_notice_email_intake_parses',
    'status',
    'copyright_notice_email_intake_parse_statuses',
    false,
  ],
  [
    'copyright_notice_email_intake_reviews',
    'decision',
    'copyright_notice_email_intake_review_decisions',
    false,
  ],
  ['copyright_notice_email_intakes', 'dkim_verdict', 'email_security_verdicts', false],
  ['copyright_notice_email_intakes', 'dmarc_verdict', 'email_security_verdicts', false],
  ['copyright_notice_email_intakes', 'spam_verdict', 'email_security_verdicts', false],
  ['copyright_notice_email_intakes', 'spf_verdict', 'email_security_verdicts', false],
  ['copyright_notice_email_intakes', 'virus_verdict', 'email_security_verdicts', false],
  [
    'copyright_notice_email_thread_references',
    'reference_kind',
    'copyright_notice_email_thread_reference_kinds',
    false,
  ],
] as const
