// Reviewed storage-column contracts for the prelaunch finite-value conversion.
export const FINITE_COLUMN_CONTRACTS_4 = [
  [
    'copyright_trusted_flaggers',
    'area_of_expertise',
    'copyright_trusted_flagger_expertise_areas',
    false,
  ],
  ['curated_aside_items', 'aside_type', 'curated_aside_item_types', false],
  ['dynamic_configuration_revisions', 'revision_type', 'revision_types', false],
  ['image_placements', 'binding_family', 'image_binding_families', false],
  [
    'image_surface_placement_activations',
    'surface_kind',
    'image_surface_placement_surface_kinds',
    false,
  ],
  ['image_surface_placements', 'binding_family', 'image_binding_families', false],
  ['image_surface_placements', 'surface_kind', 'image_surface_placement_surface_kinds', false],
  ['user_lists', 'visibility', 'list_visibilities', false],
  ['mcp_call_audit_events', 'outcome', 'mcp_call_audit_event_outcomes', false],
  ['mcp_call_audit_events', 'surface', 'mcp_call_audit_event_surfaces', false],
  ['media_delivery_registry_changes', 'desired_state', 'media_delivery_desired_states', false],
  ['media_delivery_registry_records', 'desired_state', 'media_delivery_desired_states', false],
  ['media_placements', 'retirement_reason', 'media_placement_retirement_reasons', false],
  [
    'membership_google_play_acknowledgements',
    'skip_reason',
    'membership_google_play_acknowledgement_skip_reasons',
    false,
  ],
  [
    'membership_google_play_recovery_cursors',
    'id',
    'membership_google_play_recovery_families',
    false,
  ],
  [
    'membership_microsoft_store_recovery_cursors',
    'id',
    'membership_microsoft_store_recovery_families',
    false,
  ],
  ['moderation_appeals', 'recommended_action', 'moderation_appeal_actions', false],
  ['moderation_appeals', 'resolution_action', 'moderation_appeal_actions', false],
  ['moderation_report_judgements', 'recommended_action', 'moderation_judgement_actions', false],
  ['moderation_reports', 'original_reason', 'moderation_report_reasons', false],
  ['moderation_reports', 'reason', 'moderation_report_reasons', false],
  ['moderation_reports', 'resolution_action', 'moderation_report_resolution_actions', false],
  ['moderation_training_feedbacks', 'event_type', 'moderation_training_event_types', false],
  ['moderation_training_feedbacks', 'human_action', 'moderation_training_human_actions', false],
  ['moderation_training_feedbacks', 'label', 'moderation_training_labels', false],
] as const
