// Reviewed storage-column contracts for the prelaunch finite-value conversion.
export const FINITE_COLUMN_CONTRACTS_5 = [
  ['moderation_training_feedbacks', 'source_type', 'moderation_training_source_types', false],
  [
    'moderation_transparency_daily_rollups',
    'category',
    'moderation_transparency_categories',
    false,
  ],
  ['moderation_transparency_daily_rollups', 'metric', 'moderation_transparency_metrics', false],
  [
    'moderation_transparency_released_daily_rollups',
    'category',
    'moderation_transparency_categories',
    false,
  ],
  [
    'moderation_transparency_released_daily_rollups',
    'metric',
    'moderation_transparency_metrics',
    false,
  ],
  [
    'notification_push_intent_subscription_receipts',
    'status',
    'notification_push_endpoint_statuses',
    false,
  ],
  ['notification_push_intents', 'status', 'notification_push_intent_statuses', false],
  ['notifications', 'target_intent', 'notification_target_intents', false],
  ['oauth_access_tokens', 'scopes', 'api_scopes', true],
  ['oauth_authorization_codes', 'scopes', 'api_scopes', true],
  ['oauth_authorization_requests', 'scopes', 'api_scopes', true],
  [
    'oauth_authorization_server_events',
    'event_type',
    'oauth_authorization_server_event_types',
    false,
  ],
  ['oauth_authorization_server_events', 'scopes', 'api_scopes', true],
  ['oauth_authorizations', 'callback_mode', 'oauth_callback_modes', false],
  ['oauth_authorizations', 'provider', 'oauth_authorization_providers', false],
  ['oauth_authorizations', 'purpose', 'oauth_authorization_purposes', false],
  ['oauth_authorizations', 'result_kind', 'oauth_authorization_result_kinds', false],
  ['oauth_authorizations', 'status', 'oauth_authorization_statuses', false],
  ['oauth_clients', 'client_type', 'oauth_client_types', false],
  ['oauth_clients', 'grant_types', 'oauth_grant_types', true],
  ['oauth_clients', 'response_types', 'oauth_response_types', true],
  ['oauth_clients', 'scopes', 'api_scopes', true],
  [
    'oauth_clients',
    'token_endpoint_auth_method',
    'oauth_client_token_endpoint_auth_methods',
    false,
  ],
  ['oauth_grants', 'scopes', 'api_scopes', true],
  ['oauth_refresh_token_families', 'scopes', 'api_scopes', true],
] as const
