// Reviewed storage-column contracts for the prelaunch finite-value conversion.
export const FINITE_COLUMN_CONTRACTS_3 = [
  [
    'copyright_notice_form_screenings',
    'recommendation',
    'copyright_notice_form_screening_recommendations',
    false,
  ],
  [
    'copyright_notice_legal_hold_assessments',
    'ccb_claim_kind',
    'copyright_notice_legal_hold_assessment_ccb_claim_kinds',
    false,
  ],
  [
    'copyright_notice_legal_hold_assessments',
    'proceeding_kind',
    'copyright_notice_legal_hold_assessment_proceeding_kinds',
    false,
  ],
  [
    'copyright_notice_legal_hold_resolutions',
    'resolution_kind',
    'copyright_notice_legal_hold_resolution_kinds',
    false,
  ],
  [
    'copyright_notice_lifecycle_changes',
    'recovery_source',
    'copyright_notice_lifecycle_change_recovery_sources',
    false,
  ],
  [
    'copyright_notice_lifecycle_changes',
    'replay_reason',
    'copyright_notice_lifecycle_change_replay_reasons',
    false,
  ],
  ['copyright_notice_lifecycle_changes', 'review_action', 'copyright_review_actions', false],
  ['copyright_notice_submissions', 'kind', 'copyright_notice_submission_kinds', false],
  [
    'copyright_notice_submissions',
    'source_kind',
    'copyright_notice_submission_source_kinds',
    false,
  ],
  ['copyright_notice_target_images', 'binding_family', 'image_binding_families', false],
  ['copyright_notices', 'jurisdiction', 'copyright_jurisdictions', false],
  ['copyright_notices', 'legal_basis', 'copyright_notice_legal_bases', false],
  [
    'copyright_repeat_infringer_dispositions',
    'disposition',
    'copyright_repeat_infringer_disposition_kinds',
    false,
  ],
  [
    'copyright_repeat_infringer_reviews',
    'outcome',
    'copyright_repeat_infringer_review_outcomes',
    false,
  ],
  [
    'copyright_restrictions',
    'human_review_action',
    'copyright_restriction_human_review_actions',
    false,
  ],
  ['copyright_staydown_matches', 'match_kind', 'copyright_staydown_match_kinds', false],
  [
    'copyright_territorial_decisions',
    'automation_disclosure',
    'copyright_territorial_decision_automation_disclosures',
    false,
  ],
  ['copyright_territorial_decisions', 'jurisdiction', 'copyright_jurisdictions', false],
  ['copyright_territorial_decisions', 'outcome', 'copyright_territorial_decision_outcomes', false],
  ['copyright_territorial_escalations', 'jurisdiction', 'copyright_jurisdictions', false],
  ['copyright_territorial_notice_receipts', 'jurisdiction', 'copyright_jurisdictions', false],
  [
    'copyright_territorial_notice_routings',
    'destination',
    'copyright_territorial_notice_routing_destinations',
    false,
  ],
  [
    'copyright_territorial_redress_decisions',
    'staff_disposition',
    'copyright_territorial_redress_decision_staff_dispositions',
    false,
  ],
  [
    'copyright_territorial_redress_requests',
    'filed_by',
    'copyright_territorial_party_roles',
    false,
  ],
  ['copyright_territorial_redress_requests', 'jurisdiction', 'copyright_jurisdictions', false],
] as const
