export const communityModerationSummaryCopyByLocale = {
  en: {
    preview: 'Community moderation summary for {date}',
    heading: 'Community moderation summary',
    greeting: (userName?: string) => (userName ? `Hi ${userName},` : 'Hi there,'),
    body: 'here is the moderation queue summary for {date}.',
    bodyText: 'Here is the moderation queue summary for {date}.',
    pendingPostReviews: 'Pending post reviews',
    pendingApplications: 'Pending applications',
    pendingReports: 'Pending reports',
    escalatedItems: 'Escalated items',
    suspectedBanEvaders: 'Suspected ban evaders',
    activityHeading: 'Community activity',
    memberChange: 'Member change',
    totalActiveMembers: 'Total active members',
    newDiscussions: 'New discussions',
    newReviews: 'New reviews',
    newDataPoints: 'New data points',
    topDiscussion: 'Top discussion',
    topDiscussionReplies: (count: number) => `${count} repl${count === 1 ? 'y' : 'ies'}`,
    activeMembers: 'Active members',
    itemButton: 'Open Community',
    empty: 'No communities need attention right now.',
    settings: 'Open Moderation Settings',
    unsubscribe: 'Unsubscribe',
    subject: 'Community moderation summary for {date}',
  },
  es: {
    preview: 'Resumen de moderación de comunidades para {date}',
    heading: 'Resumen de moderación de comunidades',
    greeting: (userName?: string) => (userName ? `Hola ${userName},` : 'Hola,'),
    body: 'este es el resumen de la cola de moderación para {date}.',
    bodyText: 'Este es el resumen de la cola de moderación para {date}.',
    pendingPostReviews: 'Revisiones de publicaciones pendientes',
    pendingApplications: 'Solicitudes pendientes',
    pendingReports: 'Reportes pendientes',
    escalatedItems: 'Elementos escalados',
    suspectedBanEvaders: 'Posibles evasores de bloqueo',
    activityHeading: 'Actividad de la comunidad',
    memberChange: 'Cambio de miembros',
    totalActiveMembers: 'Total de miembros activos',
    newDiscussions: 'Nuevos debates',
    newReviews: 'Nuevas reseñas',
    newDataPoints: 'Nuevos datos',
    topDiscussion: 'Debate destacado',
    topDiscussionReplies: (count: number) => `${count} respuesta${count === 1 ? '' : 's'}`,
    activeMembers: 'Miembros activos',
    itemButton: 'Abrir comunidad',
    empty: 'Ninguna comunidad necesita atención ahora.',
    settings: 'Abrir ajustes de moderación',
    unsubscribe: 'Cancelar suscripción',
    subject: 'Resumen de moderación de comunidades para {date}',
  },
  fr: {
    preview: 'Résumé de modération des communautés pour le {date}',
    heading: 'Résumé de modération des communautés',
    greeting: (userName?: string) => (userName ? `Bonjour ${userName},` : 'Bonjour,'),
    body: 'voici le résumé de la file de modération pour le {date}.',
    bodyText: 'Voici le résumé de la file de modération pour le {date}.',
    pendingPostReviews: 'Publications en attente de révision',
    pendingApplications: 'Candidatures en attente',
    pendingReports: 'Signalements en attente',
    escalatedItems: 'Éléments escaladés',
    suspectedBanEvaders: 'Contournements de bannissement suspectés',
    activityHeading: 'Activité de la communauté',
    memberChange: 'Variation des membres',
    totalActiveMembers: 'Total des membres actifs',
    newDiscussions: 'Nouvelles discussions',
    newReviews: 'Nouveaux avis',
    newDataPoints: 'Nouvelles données',
    topDiscussion: 'Discussion phare',
    topDiscussionReplies: (count: number) => `${count} réponse${count === 1 ? '' : 's'}`,
    activeMembers: 'Membres actifs',
    itemButton: 'Ouvrir la communauté',
    empty: 'Aucune communauté ne nécessite votre attention pour le moment.',
    settings: 'Ouvrir les paramètres de modération',
    unsubscribe: 'Se désabonner',
    subject: 'Résumé de modération des communautés pour le {date}',
  },
  pt: {
    preview: 'Resumo de moderação de comunidades para {date}',
    heading: 'Resumo de moderação de comunidades',
    greeting: (userName?: string) => (userName ? `Olá ${userName},` : 'Olá,'),
    body: 'este é o resumo da fila de moderação para {date}.',
    bodyText: 'Este é o resumo da fila de moderação para {date}.',
    pendingPostReviews: 'Revisões de publicações pendentes',
    pendingApplications: 'Solicitações pendentes',
    pendingReports: 'Denúncias pendentes',
    escalatedItems: 'Itens escalados',
    suspectedBanEvaders: 'Possíveis evasores de banimento',
    activityHeading: 'Atividade da comunidade',
    memberChange: 'Variação de membros',
    totalActiveMembers: 'Total de membros ativos',
    newDiscussions: 'Novas discussões',
    newReviews: 'Novas avaliações',
    newDataPoints: 'Novos dados',
    topDiscussion: 'Discussão em destaque',
    topDiscussionReplies: (count: number) => `${count} resposta${count === 1 ? '' : 's'}`,
    activeMembers: 'Membros ativos',
    itemButton: 'Abrir comunidade',
    empty: 'Nenhuma comunidade precisa de atenção agora.',
    settings: 'Abrir configurações de moderação',
    unsubscribe: 'Cancelar inscrição',
    subject: 'Resumo de moderação de comunidades para {date}',
  },
} as const
