export const followTopicsCopyByLocale = {
  en: {
    preview: 'Topics from people you trust',
    heading: 'Follow topics',
    greeting: (userName?: string) => (userName ? `Hi ${userName},` : 'Hi there,'),
    body: 'topics help tune your feed. Follow a few to see more news and posts from people and sources you trust.',
    bodyText:
      'Topics help tune your feed. Follow a few to see more news and posts from people and sources you trust.',
    fallbackReason: 'Open the topic and follow it.',
    empty: 'No topics are ready right now.',
    itemButton: 'Open Topic',
    manage: 'Manage Topic Follows',
    unsubscribe: 'Unsubscribe',
    subject: 'Topics from people you trust',
  },
  es: {
    preview: 'Temas de personas en las que confías',
    heading: 'Seguir temas',
    greeting: (userName?: string) => (userName ? `Hola ${userName},` : 'Hola,'),
    body: 'los temas ayudan a ajustar tu feed. Sigue algunos para ver más noticias y publicaciones de personas y fuentes en las que confías.',
    bodyText:
      'Los temas ayudan a ajustar tu feed. Sigue algunos para ver más noticias y publicaciones de personas y fuentes en las que confías.',
    fallbackReason: 'Abre el tema y síguelo.',
    empty: 'No hay temas listos en este momento.',
    itemButton: 'Abrir tema',
    manage: 'Gestionar temas seguidos',
    unsubscribe: 'Cancelar suscripción',
    subject: 'Temas de personas en las que confías',
  },
  fr: {
    preview: 'Des sujets venant de personnes de confiance',
    heading: 'Suivre des sujets',
    greeting: (userName?: string) => (userName ? `Bonjour ${userName},` : 'Bonjour,'),
    body: 'les sujets aident à ajuster votre fil. Suivez-en quelques-uns pour voir plus d’actualités et de publications de personnes et de sources de confiance.',
    bodyText:
      'Les sujets aident à ajuster votre fil. Suivez-en quelques-uns pour voir plus d’actualités et de publications de personnes et de sources de confiance.',
    fallbackReason: 'Ouvrez le sujet et suivez-le.',
    empty: 'Aucun sujet n’est prêt pour le moment.',
    itemButton: 'Ouvrir le sujet',
    manage: 'Gérer les sujets suivis',
    unsubscribe: 'Se désabonner',
    subject: 'Des sujets venant de personnes de confiance',
  },
  pt: {
    preview: 'Tópicos de pessoas em quem você confia',
    heading: 'Seguir tópicos',
    greeting: (userName?: string) => (userName ? `Olá ${userName},` : 'Olá,'),
    body: 'os tópicos ajudam a ajustar seu feed. Siga alguns para ver mais notícias e publicações de pessoas e fontes em que você confia.',
    bodyText:
      'Os tópicos ajudam a ajustar seu feed. Siga alguns para ver mais notícias e publicações de pessoas e fontes em que você confia.',
    fallbackReason: 'Abra o tópico e siga-o.',
    empty: 'Nenhum tópico está pronto agora.',
    itemButton: 'Abrir tópico',
    manage: 'Gerenciar tópicos seguidos',
    unsubscribe: 'Cancelar inscrição',
    subject: 'Tópicos de pessoas em quem você confia',
  },
} as const
