export const followNewsSourcesCopyByLocale = {
  en: {
    preview: 'News sources from people you trust',
    heading: 'Follow news sources',
    greeting: (userName?: string) => (userName ? `Hi ${userName},` : 'Hi there,'),
    body: 'follow news sources to see articles from people and sources you trust.',
    bodyText: 'Follow news sources to see articles from people and sources you trust.',
    fallbackDescription: 'Open the source and follow it.',
    empty: 'No news sources are ready right now.',
    itemButton: 'Open Source',
    manage: 'Manage News Sources',
    unsubscribe: 'Unsubscribe',
    subject: 'News sources from people you trust',
  },
  es: {
    preview: 'Fuentes de noticias de personas en las que confías',
    heading: 'Seguir fuentes de noticias',
    greeting: (userName?: string) => (userName ? `Hola ${userName},` : 'Hola,'),
    body: 'sigue fuentes de noticias para ver artículos de personas y fuentes en las que confías.',
    bodyText:
      'Sigue fuentes de noticias para ver artículos de personas y fuentes en las que confías.',
    fallbackDescription: 'Abre la fuente y síguela.',
    empty: 'No hay fuentes de noticias listas en este momento.',
    itemButton: 'Abrir fuente',
    manage: 'Gestionar fuentes de noticias',
    unsubscribe: 'Cancelar suscripción',
    subject: 'Fuentes de noticias de personas en las que confías',
  },
  fr: {
    preview: 'Sources d’actualités de personnes de confiance',
    heading: 'Suivre des sources d’actualités',
    greeting: (userName?: string) => (userName ? `Bonjour ${userName},` : 'Bonjour,'),
    body: 'suivez des sources d’actualités pour voir des articles de personnes et de sources de confiance.',
    bodyText:
      'Suivez des sources d’actualités pour voir des articles de personnes et de sources de confiance.',
    fallbackDescription: 'Ouvrez la source et suivez-la.',
    empty: 'Aucune source d’actualités n’est prête pour le moment.',
    itemButton: 'Ouvrir la source',
    manage: 'Gérer les sources d’actualités',
    unsubscribe: 'Se désabonner',
    subject: 'Sources d’actualités de personnes de confiance',
  },
  pt: {
    preview: 'Fontes de notícias de pessoas em quem você confia',
    heading: 'Seguir fontes de notícias',
    greeting: (userName?: string) => (userName ? `Olá ${userName},` : 'Olá,'),
    body: 'siga fontes de notícias para ver artigos de pessoas e fontes em que você confia.',
    bodyText: 'Siga fontes de notícias para ver artigos de pessoas e fontes em que você confia.',
    fallbackDescription: 'Abra a fonte e siga-a.',
    empty: 'Nenhuma fonte de notícias está pronta agora.',
    itemButton: 'Abrir fonte',
    manage: 'Gerenciar fontes de notícias',
    unsubscribe: 'Cancelar inscrição',
    subject: 'Fontes de notícias de pessoas em quem você confia',
  },
} as const
