export const postReferralLinkCopyByLocale = {
  en: {
    preview: 'Referral links from your circle',
    heading: 'Referral links',
    greeting: (userName?: string) => (userName ? `Hi ${userName},` : 'Hi there,'),
    body: 'when you recommend something, people in your circle should see your link first.',
    bodyText: 'When you recommend something, people in your circle should see your link first.',
    fallbackCount: 'Open the program and update your links.',
    activeLinks: (count: number) => `${count} active link${count === 1 ? '' : 's'}`,
    empty: 'No referral programs are ready right now.',
    itemButton: 'Open Program',
    manage: 'Manage Referral Links',
    unsubscribe: 'Unsubscribe',
    subject: 'Referral links from your circle',
  },
  es: {
    preview: 'Enlaces de referido de tu círculo',
    heading: 'Enlaces de referido',
    greeting: (userName?: string) => (userName ? `Hola ${userName},` : 'Hola,'),
    body: 'cuando recomiendas algo, las personas de tu círculo deberían ver primero tu enlace.',
    bodyText: 'Cuando recomiendas algo, las personas de tu círculo deberían ver primero tu enlace.',
    fallbackCount: 'Abre el programa y actualiza tus enlaces.',
    activeLinks: (count: number) =>
      `${count} enlace${count === 1 ? '' : 's'} activo${count === 1 ? '' : 's'}`,
    empty: 'No hay programas de referido listos en este momento.',
    itemButton: 'Abrir programa',
    manage: 'Gestionar enlaces de referido',
    unsubscribe: 'Cancelar suscripción',
    subject: 'Enlaces de referido de tu círculo',
  },
  fr: {
    preview: 'Liens de parrainage de votre cercle',
    heading: 'Liens de parrainage',
    greeting: (userName?: string) => (userName ? `Bonjour ${userName},` : 'Bonjour,'),
    body: 'quand vous recommandez quelque chose, les personnes de votre cercle devraient voir votre lien en premier.',
    bodyText:
      'Quand vous recommandez quelque chose, les personnes de votre cercle devraient voir votre lien en premier.',
    fallbackCount: 'Ouvrez le programme et mettez vos liens à jour.',
    activeLinks: (count: number) =>
      `${count} lien${count === 1 ? '' : 's'} actif${count === 1 ? '' : 's'}`,
    empty: 'Aucun programme de parrainage n’est prêt pour le moment.',
    itemButton: 'Ouvrir le programme',
    manage: 'Gérer les liens de parrainage',
    unsubscribe: 'Se désabonner',
    subject: 'Liens de parrainage de votre cercle',
  },
  pt: {
    preview: 'Links de indicação do seu círculo',
    heading: 'Links de indicação',
    greeting: (userName?: string) => (userName ? `Olá ${userName},` : 'Olá,'),
    body: 'quando você recomenda algo, as pessoas do seu círculo devem ver seu link primeiro.',
    bodyText: 'Quando você recomenda algo, as pessoas do seu círculo devem ver seu link primeiro.',
    fallbackCount: 'Abra o programa e atualize seus links.',
    activeLinks: (count: number) =>
      `${count} link${count === 1 ? '' : 's'} ativo${count === 1 ? '' : 's'}`,
    empty: 'Nenhum programa de indicação está pronto agora.',
    itemButton: 'Abrir programa',
    manage: 'Gerenciar links de indicação',
    unsubscribe: 'Cancelar inscrição',
    subject: 'Links de indicação do seu círculo',
  },
} as const
