/** Established dashboard moderation taxonomy; the unified staff audit has wider coverage. */
export const MODERATION_ANALYTICS_ACTION_TYPES = [
  'remove',
  'approve',
  'reject',
  'ban',
  'lift_ban',
  'activate_restriction',
  'lift_restriction',
  'warn',
  'lock',
  'unlock',
  'pin',
  'unpin',
  'tag',
  'suspend',
  'unsuspend',
  'remove_member',
  'change_role',
  'resolve_report',
  'dismiss_report',
  'resolve_appeal',
  'dismiss_appeal',
] as const
