export * from './ses.mts'
export * from './s3.mts'
export * from './sqs.mts'
export * from './firehose.mts'
export * from './config.mts'
export * from './credentials.mts'
export * from './cloudwatch.mts'
