const jobs = (keys: string): readonly string[] => keys.split(' ')

export const jobInventory = {
  '.github/workflows/actionlint.yml': jobs('actionlint'),
  '.github/workflows/backend.yml': jobs(
    'backend backend-smoke changes codecov coverage publish-backend-images static-backend test-backend-credentialed test-backend-modules test-backend-unit test-explain-analyze test-postgres-schema validate-backend-images',
  ),
  '.github/workflows/cancel-dequeued-merge-group-runs.yml': jobs('cancel'),
  '.github/workflows/cancel-replaced-merge-group-runs.yml': jobs('cancel'),
  '.github/workflows/ci-area-coverage.yml': jobs('coverage'),
  '.github/workflows/cloudflare-worker.yml': jobs(
    'changes cloudflare-worker codecov coverage static-cloudflare-worker test-cloudflare-worker',
  ),
  '.github/workflows/lambdas.yml': jobs(
    'changes codecov coverage lambdas static-lambdas test-lambdas',
  ),
  '.github/workflows/nightly.yml': jobs('backend cloudflare-worker lambdas static tooling web'),
  '.github/workflows/static.yml': jobs('static static-code-analysis'),
  '.github/workflows/tooling.yml': jobs(
    'changes codecov coverage initialize-smoke-test test-portability test-tooling test-ts-shared tooling',
  ),
  '.github/workflows/web.yml': jobs(
    'changes codecov coverage publish-web-images static-web storybook test-playwright test-playwright-credentialed test-web test-web-api test-web-integration validate-web-images web',
  ),
  '.github/workflows/publish-backend-images.yml': jobs('build resolve-main-images'),
  '.github/workflows/publish-web-images.yml': jobs('build resolve-main-images'),
  '.github/workflows/checks-static.yml': jobs(
    'static-backend static-cloudflare static-lambdas static-web',
  ),
  '.github/workflows/checks-backend-smoke.yml': jobs('smoke'),
  '.github/workflows/ci-detect-changes.yml': jobs('detect-changes'),
  '.github/workflows/ci-upload-codecov.yml': jobs('upload-codecov'),
  '.github/workflows/cleanup-artifacts.yml': jobs('cleanup-sweep'),
  '.github/workflows/harness-dispatch.yml': jobs('dispatch'),
  '.github/workflows/fix-dependabot.yml': jobs(
    'check-duplicates comment-session dispatch escalate render-prompt revalidate-dispatch triage-and-rerun',
  ),
  '.github/workflows/fix-issue.yml': jobs('comment-session dispatch escalate gate render-prompt'),
  '.github/workflows/fix-main-self-retry.yml': jobs('escalate-retry-failure retry'),
  '.github/workflows/fix-main.yml': jobs(
    'classify-self-failure dispatch escalate related-candidates render-prompt triage-and-rerun',
  ),
  '.github/workflows/merge-queue-ejection.yml': jobs(
    'comment-session dispatch escalate render-prompt',
  ),
  '.github/workflows/plan.yml': jobs('comment-session dispatch escalate gate render-prompt'),
  '.github/workflows/plan-completion.yml': jobs('audit'),
  '.github/workflows/shepherd.yml': jobs(
    'checkpoint-dispatch dispatch escalate gate render-prompt',
  ),
  '.github/workflows/scheduled-prompts.yml': jobs('dispatch select-prompt'),
  '.github/workflows/docs-publish.yml': jobs('publish'),
  '.github/workflows/dispatch-completed-deploy.yml': jobs('dispatch'),
  '.github/workflows/explain-analyze.yml': jobs('explain-analyze'),
  '.github/workflows/ghcr-cleanup.yml': jobs('cleanup'),
  '.github/workflows/gitleaks.yml': jobs('gitleaks'),
  '.github/workflows/initialize-smoke-test.yml': jobs('initialize-smoke-test'),
  '.github/workflows/label-pr.yml': jobs('label'),
  '.github/workflows/lint-links.yml': jobs('lint-links'),
  '.github/workflows/main-backend.yml': jobs(
    'backend-deploy-intent detect-image-publication publish-backend-images',
  ),
  '.github/workflows/main-cloudflare-worker.yml': jobs('publish-cloudflare-worker'),
  '.github/workflows/main-lambdas.yml': jobs('publish-image-resize'),
  '.github/workflows/main-storybook.yml': jobs('publish-storybook'),
  '.github/workflows/main-web.yml': jobs(
    'detect-image-publication publish-web-images web-deploy-intent',
  ),
  '.github/workflows/pnpm-dedupe.yml': jobs('dedupe'),
  '.github/workflows/postgresql-snapshot-update.yml': jobs('generate prepare publish'),
  '.github/workflows/static-code-analysis.yml': jobs('no-mistakes static-code-analysis'),
  '.github/workflows/storybook.yml': jobs('storybook'),
  '.github/workflows/sync-articles.yml': jobs('publish'),
  '.github/workflows/tests-backend-credentialed.yml': jobs('backend-credentialed-tests'),
  '.github/workflows/tests-backend-modules.yml': jobs('backend-modules'),
  '.github/workflows/tests-backend-unit.yml': jobs('backend-tests prep'),
  '.github/workflows/tests-cloudflare-worker.yml': jobs('cloudflare-worker-tests'),
  '.github/workflows/tests-lambdas.yml': jobs('lambdas-tests'),
  '.github/workflows/tests-playwright-credentialed.yml': jobs('playwright-credentialed-tests'),
  '.github/workflows/tests-playwright.yml': jobs('playwright-tests shards'),
  '.github/workflows/tests-portability.yml': jobs('portability-linux'),
  '.github/workflows/tests-postgres-schema.yml': jobs('postgres-schema-tests'),
  '.github/workflows/tests-tooling.yml': jobs('i18n-route-bounds tooling'),
  '.github/workflows/tests-ts-shared.yml': jobs('ts-shared'),
  '.github/workflows/tests-web-integration.yml': jobs('prep web-integration-tests'),
  '.github/workflows/tests-web-api.yml': jobs('prep web-api-tests'),
  '.github/workflows/tests-web.yml': jobs('prep web-tests'),
} satisfies Record<string, readonly string[]>

export const unlockedWorkflowReasons = {
  '.github/workflows/ci-area-coverage.yml': 'short-lived read-only area coverage check',
  '.github/workflows/static-code-analysis.yml': "runs under its caller's concurrency",
  '.github/workflows/tests-playwright-credentialed.yml': "runs under its caller's concurrency",
  '.github/workflows/tests-playwright.yml': "runs under its caller's concurrency",
  '.github/workflows/tests-portability.yml': "runs under its caller's concurrency",
  '.github/workflows/ci-detect-changes.yml': 'short-lived read-only CI classification',
  '.github/workflows/ci-upload-codecov.yml': 'independent informational coverage upload',
  '.github/workflows/checks-backend-smoke.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/checks-static.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/explain-analyze.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/initialize-smoke-test.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/label-pr.yml': 'idempotent PR labeling',
  '.github/workflows/publish-backend-images.yml':
    "runs under its area or main caller's concurrency",
  '.github/workflows/publish-web-images.yml': "runs under its area or main caller's concurrency",
  '.github/workflows/tests-backend-credentialed.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-backend-modules.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-backend-unit.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-cloudflare-worker.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-lambdas.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-postgres-schema.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-tooling.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-ts-shared.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-web-integration.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-web-api.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-web.yml': 'parallel-safe idempotent manual tests',
} satisfies Record<string, string>
