const jobs = (keys: string): readonly string[] => keys.split(' ')

export const jobInventory = {
  '.github/workflows/actionlint.yml': jobs('actionlint'),
  '.github/workflows/build-backend.yml': jobs('build'),
  '.github/workflows/build-web.yml': jobs('build'),
  '.github/workflows/checks-static.yml': jobs(
    'static-backend static-cloudflare static-lambdas static-web',
  ),
  '.github/workflows/checks-backend-smoke.yml': jobs('smoke'),
  '.github/workflows/ci.yml': jobs(
    'backend-smoke build build-backend build-web ci-record-state detect-changes initialize-smoke-test ready-dedupe select-ci static-backend static-cloudflare-worker static-code-analysis static-lambdas static-web storybook test-backend-credentialed test-backend-modules test-backend-unit test-cloudflare-worker test-coverage test-explain-analyze test-lambdas test-playwright test-playwright-credentialed test-portability test-postgres-schema test-tooling test-ts-shared test-web test-web-api test-web-integration tests tests-processing',
  ),
  '.github/workflows/ci-detect-changes.yml': jobs('detect-changes'),
  '.github/workflows/ci-ready-dedupe.yml': jobs('ready-dedupe report-reused-producers'),
  '.github/workflows/ci-record-state.yml': jobs('record-state'),
  '.github/workflows/ci-select-vitest.yml': jobs('select-ci'),
  '.github/workflows/ci-test-coverage.yml': jobs('test-coverage'),
  '.github/workflows/ci-tests-processing.yml': jobs('tests-processing'),
  '.github/workflows/cleanup-artifacts.yml': jobs('cleanup-run cleanup-sweep'),
  '.github/workflows/harness-dispatch.yml': jobs('dispatch'),
  '.github/workflows/fix-dependabot.yml': jobs(
    'check-duplicates dispatch escalate render-prompt revalidate-dispatch triage-and-rerun',
  ),
  '.github/workflows/fix-issue.yml': jobs('dispatch escalate gate render-prompt'),
  '.github/workflows/fix-main-self-retry.yml': jobs('escalate-retry-failure retry'),
  '.github/workflows/fix-main.yml': jobs(
    'classify-self-failure dispatch escalate related-candidates render-prompt triage-and-rerun',
  ),
  '.github/workflows/plan.yml': jobs('dispatch escalate gate render-prompt'),
  '.github/workflows/shepherd.yml': jobs(
    'checkpoint-dispatch dispatch escalate gate render-prompt',
  ),
  '.github/workflows/scheduled-prompts.yml': jobs('dispatch select-prompt'),
  '.github/workflows/dependabot-pr-automerge.yml': jobs('automerge cleanup-retargeted-automerge'),
  '.github/workflows/docs-publish.yml': jobs('complete'),
  '.github/workflows/dispatch-completed-deploy.yml': jobs('dispatch'),
  '.github/workflows/explain-analyze.yml': jobs('explain-analyze'),
  '.github/workflows/ghcr-cleanup.yml': jobs('cleanup'),
  '.github/workflows/gitleaks.yml': jobs('gitleaks'),
  '.github/workflows/initialize-smoke-test.yml': jobs('initialize-smoke-test'),
  '.github/workflows/label-pr.yml': jobs('label'),
  '.github/workflows/lint-links.yml': jobs('lint-links'),
  '.github/workflows/main-backend.yml': jobs(
    'backend-smoke postgres-schema-tests publish-backend-images static-checks test-backend-credentialed test-backend-modules test-backend-unit',
  ),
  '.github/workflows/main-checks.yml': jobs(
    'cleanup-artifacts explain-analyze select-main-checks tooling-tests ts-shared-tests',
  ),
  '.github/workflows/main-cloudflare-worker.yml': jobs('cloudflare-worker-tests static-checks'),
  '.github/workflows/main-lambdas.yml': jobs('lambdas-tests static-checks'),
  '.github/workflows/main-storybook.yml': jobs('storybook-build'),
  '.github/workflows/main-web.yml': jobs(
    'cleanup-artifacts detect-web-deploy playwright-credentialed-tests playwright-tests static-checks store-playwright-otel test-web test-web-api test-web-integration web-deploy-intent',
  ),
  '.github/workflows/claude-openrouter-code-reviewer.yml': jobs('claude-openrouter-code-reviewer'),
  '.github/workflows/opencode-openrouter-code-review.yml': jobs('opencode-openrouter-review'),
  '.github/workflows/opencode-zen-code-review.yml': jobs('opencode-zen-review'),
  '.github/workflows/pnpm-dedupe.yml': jobs('dedupe'),
  '.github/workflows/static-code-analysis.yml': jobs('no-mistakes-owned static-code-analysis'),
  '.github/workflows/storybook.yml': jobs('storybook'),
  '.github/workflows/sync-articles.yml': jobs('complete'),
  '.github/workflows/tests-backend-credentialed.yml': jobs('backend-credentialed-tests'),
  '.github/workflows/tests-backend-modules.yml': jobs('backend-modules'),
  '.github/workflows/tests-backend-unit.yml': jobs('backend-tests prep'),
  '.github/workflows/tests-cloudflare-worker.yml': jobs('cloudflare-worker-tests'),
  '.github/workflows/tests-lambdas.yml': jobs('lambdas-tests'),
  '.github/workflows/tests-playwright-credentialed.yml': jobs('playwright-credentialed-tests'),
  '.github/workflows/tests-playwright.yml': jobs('playwright-tests select'),
  '.github/workflows/tests-portability.yml': jobs('portability-linux portability-macos'),
  '.github/workflows/tests-postgres-schema.yml': jobs('postgres-schema-tests'),
  '.github/workflows/tests-tooling.yml': jobs('i18n-route-bounds tooling'),
  '.github/workflows/tests-ts-shared.yml': jobs('ts-shared'),
  '.github/workflows/tests-web-integration.yml': jobs('prep web-integration-tests'),
  '.github/workflows/tests-web-api.yml': jobs('prep web-api-tests'),
  '.github/workflows/tests-web.yml': jobs('prep web-tests'),
} satisfies Record<string, readonly string[]>

export const unlockedWorkflowReasons = {
  '.github/workflows/ci-detect-changes.yml': 'short-lived read-only CI classification',
  '.github/workflows/ci-ready-dedupe.yml': 'short-lived read-only CI deduplication',
  '.github/workflows/ci-record-state.yml': 'short-lived permissionless CI state recording',
  '.github/workflows/ci-select-vitest.yml': 'short-lived read-only test selection',
  '.github/workflows/ci-test-coverage.yml': 'short-lived coverage report evaluation',
  '.github/workflows/checks-backend-smoke.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/checks-static.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/explain-analyze.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/initialize-smoke-test.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/label-pr.yml': 'idempotent PR labeling',
  '.github/workflows/tests-backend-credentialed.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-backend-modules.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-backend-unit.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-cloudflare-worker.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-lambdas.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-postgres-schema.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-tooling.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-ts-shared.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-web-integration.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-web-api.yml': 'parallel-safe idempotent manual tests',
  '.github/workflows/tests-web.yml': 'parallel-safe idempotent manual tests',
} satisfies Record<string, string>
